INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Church', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Bound', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Flare', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Equal', 4, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Dusk', 1, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Excel', 2, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Charm', 3, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Free', 4, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Dome', 5, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Concrete Jungle', 'Juror', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Concrete Jungle', 'Idea', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Alpine', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Facet', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Divide', 3, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Bolt', 4, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Join', 5, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metro Magic', 'Copper', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Inner', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Donor', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Forth', 3, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Font', 4, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Derby', 5, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Downtown Discovery', 'Gas', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Grand Boulevard', 'Bridge', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Exit', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Fossil', 2, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Smart Saunter', 'Dean', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Smart Saunter', 'Envoy', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pavement Perspectives', 'Duty', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pavement Perspectives', 'Dragon', 2, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pavement Perspectives', 'Frown', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pavement Perspectives', 'Fill', 4, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Dial', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Blaze', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Freight', 3, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Canal', 4, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Finite', 5, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Fellow', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Essay', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Garage', 3, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Dock', 4, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Borough Best', 'Genius', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Borough Best', 'Birch', 2, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Borough Best', 'Cameo', 3, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Image', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Banner', 2, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Capital Chronicles', 'Bold', 1, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Capital Chronicles', 'Edgecliff', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metropolitan Mosaic', 'Fight', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metropolitan Mosaic', 'Funny', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metropolitan Mosaic', 'Ginger', 3, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Jump', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Flex', 2, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Earth', 3, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Future', 4, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Main Street Memories', 'Bishop', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Main Street Memories', 'Block', 2, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Glad', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Direct', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Driftwood', 3, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Ghost', 4, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Dean', 5, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Town Square Tales', 'Course', 1, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Town Square Tales', 'Depth', 2, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Avenue Adventures', 'Epsilon', 1, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Avenue Adventures', 'Cairo', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Avenue Adventures', 'Golf', 3, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Bound', 1, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Better', 2, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Dewberry', 3, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Jewel', 4, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Soul', 'Font', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Soul', 'Clan', 2, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Cargo', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Cyber', 2, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Focus', 1, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Info', 2, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Daily Grind', 'Beta', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Daily Grind', 'Glad', 2, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sidewalk Stories', 'Feast', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Ethics', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Frown', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Arrow', 3, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Dover', 4, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Ferry', 5, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Public Plaza Parade', 'Dale', 1, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Public Plaza Parade', 'Felt', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Architectural Arc', 'Clermont', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Architectural Arc', 'Frown', 2, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Architectural Arc', 'Effect', 3, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Architectural Arc', 'Eilat', 4, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Architectural Arc', 'Dekel', 5, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Draft', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Item', 2, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Geo', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Coin', 4, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Belo', 5, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neon Nights', 'Falcon', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neon Nights', 'Gaze', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brick & Mortar', 'Frank', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Core', 'Focus', 1, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Core', 'Garlic', 2, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfront Wonders', 'Crown', 1, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dockside Dreams', 'Belo', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dockside Dreams', 'Aero', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dockside Dreams', 'Core', 3, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pier Perspectives', 'Feature', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pier Perspectives', 'Dream', 2, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pier Perspectives', 'Input', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Harbor Highlights', 'Evoke', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Harbor Highlights', 'Elder', 2, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'Arena', 1, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'East', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'Fair', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The High-Rise Hike', 'Final', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The High-Rise Hike', 'Frank', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The High-Rise Hike', 'Arena', 3, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Alleyway Aesthetics', 'Breeze', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Alleyway Aesthetics', 'Joy', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Alleyway Aesthetics', 'Gem', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Alleyway Aesthetics', 'Flint', 4, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Subway Secrets', 'Flora', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Subway Secrets', 'Dry', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Subway Secrets', 'Baron', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Transit Triumphs', 'Arena', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Transit Triumphs', 'Arcadia', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Park & Promenade', 'Eta', 1, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Park & Promenade', 'Gird', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Civic Center', 'Fuse', 1, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Civic Center', 'Fame', 2, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Civic Center', 'Chapel', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Civic Center', 'Drain', 4, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Icon', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Form', 2, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Idol', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Dry', 4, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Chart', 5, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Entertainment District', 'Estate', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Financial Frontier', 'Glass', 1, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Financial Frontier', 'Engine', 2, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Old Town Origins', 'Boost', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Old Town Origins', 'Court', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Old Town Origins', 'Dash', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Belgrave', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Downriver', 2, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Echoes', 'Dusk', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Echoes', 'Calm', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Echoes', 'Fourth', 3, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Echoes', 'Clermont', 4, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Echoes', 'Belfry', 5, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Timeless Traditions', 'Avalon', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Friend', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Delta', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Canal', 3, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Gloom', 4, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Given', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Goal', 2, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Akko', 3, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Good', 4, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Elden', 5, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Finite', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Double', 2, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Coral', 3, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Fine', 4, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Flight', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Flame', 2, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Cell', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Dock', 4, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancestral Avenues', 'Berlin', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancestral Avenues', 'Gloss', 2, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Crossroads', 'Ether', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Crossroads', 'KeenתAdmiral', 2, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Crossroads', 'Armada', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Crossroads', 'Chief', 4, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Folklore Follow', 'Fire', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Folklore Follow', 'Brace', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Folklore Follow', 'Hub', 3, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Downtown', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Garlic', 2, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Entry', 3, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Device', 4, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Elect', 5, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Calm', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Fade', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Central', 3, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Medieval Mysteries', 'Cruz', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Medieval Mysteries', 'Flux', 2, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Medieval Mysteries', 'Flock', 3, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Medieval Mysteries', 'Drain', 4, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Renaissance Revelations', 'Cipher', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Renaissance Revelations', 'Cyber', 2, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Renaissance Revelations', 'Glide', 3, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Renaissance Revelations', 'Disc', 4, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Colonial Chronicles', 'Human', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Fixed', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Elect', 2, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Broad', 3, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Gamma', 4, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Duct', 5, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Museum Mile', 'Case', 1, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Monumental Moments', 'Gill', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sacred Sites', 'Ginger', 1, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Comet', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Gift', 2, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Cross', 3, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Bolt', 4, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Gable', 5, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cathedral Corners', 'Floor', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Fortress Finds', 'Glove', 1, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Fortress Finds', 'Effect', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Castle Conquest', 'Flora', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Castle Conquest', 'General', 2, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Castle Conquest', 'Gaze', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Flora', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Image', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Cause', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Ivory', 4, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Cave', 5, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ruins & Relics', 'Fruit', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ruins & Relics', 'Craft', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ruins & Relics', 'Coast', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ruins & Relics', 'Cross', 4, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Antique Adventures', 'Island', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Golden Age', 'Drain', 1, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Golden Age', 'Food', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vintage Voyage', 'Brave', 1, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vintage Voyage', 'Diamond', 2, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vintage Voyage', 'Freight', 3, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Retro Road', 'Hover', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Retro Road', 'Fifth', 2, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Classic Culture', 'Glencoe', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Classic Culture', 'Found', 2, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Excel', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Bio', 2, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Liberty Lane', 'Fiber', 1, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Liberty Lane', 'Crystal', 2, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Liberty Lane', 'Bounty', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Liberty Lane', 'Ethics', 4, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Aviary', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Floor', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Decal', 3, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Frown', 4, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Ember', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Fund', 2, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Canopy', 3, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Cabin', 1, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Coral', 2, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Dawn', 3, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Victorian Views', 'Crest', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Victorian Views', 'Forest', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Victorian Views', 'Badge', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Victorian Views', 'Flame', 4, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baroque Beauty', 'Blimp', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baroque Beauty', 'Alpha', 2, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Gaze', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Jewel', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Belfry', 3, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Girth', 4, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Engine', 5, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Dome', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Frame', 2, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Aura', 3, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tribal Tracks', 'Chapel', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tribal Tracks', 'Arid', 2, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tribal Tracks', 'Bottom', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tribal Tracks', 'Dock', 4, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Common', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Emblem', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Fancy', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Tradition Trail', 'Elmdale', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Gloss', 1, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Federal', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Epoch', 3, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Frown', 4, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gallery Gazing', 'Eilat', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Curated Culture', 'Human', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Curated Culture', 'Duke', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Curated Culture', 'Gamma', 3, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Hues', 'Dion', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The History Hut', 'East', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Akko', 1, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Camp', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Crystal', 3, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Favor', 4, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Genu', 5, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Device', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Cloak', 2, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Drone', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Disc', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Brook', 3, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Frame', 4, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Fever', 5, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wild Wanderer', 'Breeze', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wild Wanderer', 'Damp', 2, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wild Wanderer', 'Eilat', 3, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wild Wanderer', 'Fade', 4, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Nature’s Nook', 'Focus', 1, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Forest Frontiers', 'Avalon', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Forest Frontiers', 'Double', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Forest Frontiers', 'Evoke', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Mountain Majesty', 'Excel', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Mountain Majesty', 'Ease', 2, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Mountain Majesty', 'Detail', 3, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Valley Views', 'Four', 1, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Canyon Conquest', 'Elder', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('River Rapids', 'Front', 1, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lake Liberty', 'Arid', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lake Liberty', 'Dear', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ocean Odysseys', 'Index', 1, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Eye', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Coin', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Canyon', 3, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Bold', 4, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Captain', 5, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Entry', 1, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Damp', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Delhi', 3, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Classic', 4, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Jungle Jaunt', 'Drain', 1, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Safari Solitude', 'Jade', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Safari Solitude', 'Arena', 2, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Desert Dreams', 'Final', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Desert Dreams', 'Freeze', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Desert Dreams', 'Goal', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Future', 1, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Gloss', 2, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Cedar', 3, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Fino', 4, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Brick', 5, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Summit Seekers', 'Galaxy', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Summit Seekers', 'Armada', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Summit Seekers', 'Elder', 3, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Summit Seekers', 'Charm', 4, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Direct', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Diary', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Dune', 3, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Backcountry Bliss', 'Foot', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Backcountry Bliss', 'County', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Federal', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Edgecliff', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flora & Fauna', 'Input', 1, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flora & Fauna', 'House', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flora & Fauna', 'Joy', 3, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flora & Fauna', 'Armada', 4, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flora & Fauna', 'Amber', 5, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Daring', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Galaxy', 2, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Glide', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Garden Glimpse', 'Daring', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Garden Glimpse', 'Edit', 2, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Garden Glimpse', 'Border', 3, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'Carmel', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'Future', 2, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'Chapel', 3, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'Deck', 4, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Flame', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Common', 2, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Dune', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Drop', 4, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunset Serenity', 'Frown', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunset Serenity', 'Equal', 2, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunset Serenity', 'Arid', 3, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Starlight Sojourn', 'Common', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Starlight Sojourn', 'Diesel', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Starlight Sojourn', 'Crest', 3, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Genius', 1, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Funny', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Gauge', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Hub', 4, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Eco-Explorer', 'Cell', 1, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Eco-Explorer', 'Fish', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Eco-Explorer', 'Cloak', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Eco-Explorer', 'Avalon', 4, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Eco-Explorer', 'Free', 5, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Cadet', 1, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Era', 2, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Finish', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Concord', 4, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sustainable Steps', 'Fame', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sustainable Steps', 'Belfry', 2, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Great Outdoors', 'Horse', 1, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Peak Performance', 'Facet', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Peak Performance', 'Carmel', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ridge Runner', 'Cabin', 1, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ridge Runner', 'Bottom', 2, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ridge Runner', 'Iron', 3, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Meadow Muse', 'Jump', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Meadow Muse', 'Frank', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Meadow Muse', 'Debt', 3, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfall Wonders', 'Flick', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfall Wonders', 'Flag', 2, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfall Wonders', 'Delta', 3, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfall Wonders', 'Gas', 4, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'Ember', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'Film', 2, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Marshland Magic', 'Bonus', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Cliffs', 'Annex', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Cliffs', 'Aster', 2, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'Draft', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'Arid', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'General', 3, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'Fern', 4, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Reef Revelations', 'Curve', 1, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Arctic Adventures', 'Clan', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Arctic Adventures', 'Cameo', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Arctic Adventures', 'Bishop', 3, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Arctic Adventures', 'Glencoe', 4, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Arctic Adventures', 'Dale', 5, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Equal', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Drill', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Corner', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Door', 2, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Input', 3, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Bolt', 4, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Rainforest Rhythms', 'Info', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Woodland Walk', 'Dekel', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Woodland Walk', 'Eye', 2, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pine Path', 'Eta', 1, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pine Path', 'Diary', 2, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Font', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Drum', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Fluid', 3, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Drop', 4, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lowland Loop', 'Epoch', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Earthly Escapes', 'Clermont', 1, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Earthly Escapes', 'Image', 2, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Earthly Escapes', 'Dalton', 3, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Free', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Friend', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Taste Buds Tour', 'Given', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Taste Buds Tour', 'Hour', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Taste Buds Tour', 'Downriver', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Glow', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Chain', 2, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Effect', 3, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Bay', 4, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Gauge', 5, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gourmet Gazette', 'Flour', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flavor Fusion', 'Fairmont', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flavor Fusion', 'Dock', 2, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flavor Fusion', 'Inlet', 3, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flavor Fusion', 'Glow', 4, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'General', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'Fossil', 2, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'Armor', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'KeenתAdmiral', 4, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sweet Street', 'Freight', 1, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Badge', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Frank', 2, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Diver', 3, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baker’s Best', 'Foothill', 1, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baker’s Best', 'Gift', 2, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baker’s Best', 'Eilat', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baker’s Best', 'Drum', 4, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baker’s Best', 'Dual', 5, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Dwarf', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Globe', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Dust', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Folk', 2, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Drink', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Burst', 4, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Flex', 5, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Epoch', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Coast', 2, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Effect', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Calm', 4, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Dream', 5, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Direct', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'File', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Edit', 3, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Fraction', 4, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Dwarf', 5, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Winery Wonders', 'Beyond', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Winery Wonders', 'Eight', 2, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brewery Best', 'Extra', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pub Crawl Classics', 'Gentle', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pub Crawl Classics', 'Canvas', 2, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coffee Culture', 'Felt', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coffee Culture', 'Dynamic', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tea Time Trails', 'Folk', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tea Time Trails', 'Briar', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Food Safari', 'Gentle', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Local Larder', 'Farm', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Local Larder', 'Breeze', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Local Larder', 'Gird', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Local Larder', 'Enza', 4, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Local Larder', 'Flow', 5, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Chef’s Choice', 'Bluff', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Kitchen Kingdom', 'Cadet', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Kitchen Kingdom', 'Flood', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Kitchen Kingdom', 'Elect', 3, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Kitchen Kingdom', 'Compass', 4, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Kitchen Kingdom', 'Dynamic', 5, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epicurean Escape', 'Future', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epicurean Escape', 'Earth', 2, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epicurean Escape', 'Goat', 3, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epicurean Escape', 'Garage', 4, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epicurean Escape', 'Garden', 5, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Tasting Table', 'Badge', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gastronomy Guide', 'Joint', 1, 56);