DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS tourinstance CASCADE;
DROP TABLE IF EXISTS tour CASCADE;
DROP TABLE IF EXISTS station CASCADE;
DROP TABLE IF EXISTS guide CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS tourstation CASCADE;