insert into STATION (s_name, s_address, descrip) values ('Downtown Hub', '76 Springs Center', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Butterfly Bush', '8 Del Sol Point', 'Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Beach', '09 Walton Point', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Wine Vault', '806 Milwaukee Hill', 'Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Beaver Dam', '69 Bartelt Plaza', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Telescope Deck', '945 School Road', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Butterfly Bush', '35 Rieder Place', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Editing Suite', '48 Portage Center', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Midnight Alley', '5702 American Court', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Assembly Line', '71 Buhler Terrace', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Labeling Station', '55541 Lillian Center', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Lab Wing', '2 Hagan Park', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Sand Dune', '2 Monterey Court', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Manufacturing Floor', '20 Nelson Drive', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Fence', '4216 Kensington Alley', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, s_address, descrip) values ('Digital Vault', '9 Anzinger Point', 'Donec semper sapien a libero. Nam dui.');
insert into STATION (s_name, s_address, descrip) values ('Blacksmith Forge', '650 Burrows Court', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Starting Block', '2 Sommers Crossing', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Telescope Deck', '0 Amoth Road', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Smuggler’s Tunnel', '871 Wayridge Avenue', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Central Fountain', '4543 Ruskin Drive', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('City Hall Plaza', '614 Oxford Drive', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Textile Mill', '20005 Huxley Terrace', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Bike Rental Stand', '259 Lakewood Gardens Terrace', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Apple Tree', '346 Warrior Drive', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Bridge', '844 Cascade Plaza', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Stone Circle', '5 American Ash Lane', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Lab Wing', '3 David Drive', 'Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Tactical Bay', '268 Myrtle Center', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Wildflower Field', '9738 Sundown Street', 'Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Excavation Pit', '610 Corscot Road', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into STATION (s_name, s_address, descrip) values ('Armor Rack', '9 Thackeray Circle', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '1107 Parkside Plaza', 'Etiam vel augue.');
insert into STATION (s_name, s_address, descrip) values ('Fox Den', '47 Garrison Plaza', 'Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Ash Plain', '844 Merchant Junction', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Rocky Ridge', '29637 Sherman Court', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Butterfly Bush', '209 Longview Center', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Archaeology Grid', '550 Burning Wood Road', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Pebble Path', '736 Comanche Pass', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Hangar Gate', '69 Hauk Plaza', 'In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Meadow View', '158 Coolidge Pass', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Orchestra Pit', '2 Loeprich Street', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Ice Bath', '17 Rieder Hill', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, s_address, descrip) values ('Suite Entrance', '8044 Magdeline Junction', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Waterfall Base', '21 Service Drive', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Grandstand', '27 Hermina Avenue', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Hangar Gate', '74913 Monterey Junction', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Ridge', '7574 Swallow Park', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Ritual Circle', '72283 Loomis Plaza', 'Donec semper sapien a libero. Nam dui.');
insert into STATION (s_name, s_address, descrip) values ('Interview Wall', '94 Macpherson Court', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Avenue', '4 8th Place', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Engineering Block', '9764 Larry Center', 'Etiam justo.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '575 Upham Court', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Rabbit Hole', '2042 Shoshone Plaza', 'Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Reading Nook', '701 Maryland Way', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Forest', '4792 Arrowood Court', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Cobblestone Alley', '5 School Lane', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Glass Blowing Pit', '2 Brown Junction', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Pirate Cove', '27380 Scoville Crossing', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('VIP Box', '85 Westend Crossing', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Prop Room', '85272 Fallview Way', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Museum Lobby', '5594 Armistice Trail', 'Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Training Ring', '0 Grim Circle', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Tool Workshop', '6038 American Alley', 'Phasellus sit amet erat. Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Oak Grove', '929 Roth Pass', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Balcony', '295 Sommers Trail', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Sunny Glade', '543 Kennedy Hill', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Deck', '9364 Meadow Vale Road', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Cheese Cellar', '41528 Hovde Lane', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Watchtower Top', '05 Bonner Way', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Situation Room', '7864 Stoughton Place', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Valley Floor', '7223 Boyd Place', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Glass Elevator', '8 Sage Place', 'Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Twilight Pier', '54362 Duke Place', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Mathematics Hall', '16080 Bayside Park', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Boarding Gate', '86 Judy Alley', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Beach Bar', '88 Lukken Drive', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Drone Port', '6 Loeprich Avenue', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Modern Art Muse', '695 Holy Cross Center', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Innovation Lab', '0 8th Court', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Apple Tree', '87217 Village Green Drive', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Gourmet Food Hall', '3 Sycamore Park', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Apothecary Shelf', '159 Lighthouse Bay Terrace', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Fashion Boutique', '44258 Cascade Road', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Underwater Cave', '2 Prairie Rose Pass', 'Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Hotel Lounge', '27 Buena Vista Circle', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Hydrotherapy Pool', '2137 Rieder Trail', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Greenhouse Row', '46801 Muir Junction', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Safari Outpost', '86291 Crownhardt Junction', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Misty Valley', '747 Luster Crossing', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Telescope Deck', '6206 Autumn Leaf Avenue', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Modern Art Muse', '4862 Talisman Place', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Landmark', '4 Doe Crossing Drive', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('East Gate', '4 Drewry Drive', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Sauna Entrance', '78837 Welch Alley', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Highway', '7 Gale Plaza', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Sulfur Spring', '33189 Kipling Crossing', 'Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Referee Stand', '804 Autumn Leaf Hill', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Ethics Circle', '2 Sauthoff Junction', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Training Ring', '480 Johnson Park', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Post', '7993 Rockefeller Trail', 'In quis justo.');
insert into STATION (s_name, s_address, descrip) values ('Rail Station Plaza', '997 Walton Street', 'Duis bibendum.');
insert into STATION (s_name, s_address, descrip) values ('Crest', '617 Sherman Street', 'Etiam faucibus cursus urna. Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Canal Bridge', '68 Delladonna Park', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Dig Site', '6 Fordem Center', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Sunken Wreck', '64628 Clarendon Circle', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Bird Watch Tower', '85421 Golf Course Parkway', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Sideline', '1193 Vahlen Way', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Beaver Dam', '33 Sheridan Lane', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Knight’s Table', '173 Myrtle Plaza', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Surgery Suite', '3 8th Alley', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Ring Side', '1779 Porter Trail', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Medical Lab', '1 Blue Bill Park Street', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Records Room', '447 Northland Avenue', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Great Hall', '9148 Veith Avenue', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('South Port', '643 Utah Junction', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Metro Entrance', '39 Nancy Terrace', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Fermentation Lab', '1218 David Way', 'Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Starting Block', '1 Basil Avenue', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Control Room', '49 Kennedy Circle', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Sand Dune', '61752 Steensland Alley', 'Pellentesque viverra pede ac diam.');
insert into STATION (s_name, s_address, descrip) values ('Cellar Door', '837 Knutson Point', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Eco-Trail Marker', '4006 Meadow Ridge Plaza', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Safety Station', '517 Fairview Parkway', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Banquet Hall', '796 Saint Paul Hill', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Launch Pad', '1 Magdeline Center', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Local Artisan Market', '6 Londonderry Center', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Wine Vault', '998 Old Gate Pass', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Meadow View', '56 Cottonwood Point', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Grand Cathedral', '2 Gulseth Trail', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into STATION (s_name, s_address, descrip) values ('Ash Plain', '80 South Avenue', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Trade Post', '36 Mitchell Hill', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Limestone Arch', '5 Kennedy Park', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Fox Den', '1 7th Hill', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Shadow Archway', '03 Erie Hill', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Banquet Hall', '328 Alpine Point', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Permafrost Layer', '9241 Goodland Road', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Beacon', '762 Lakeland Road', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Pantry', '6441 Dwight Road', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Valley Floor', '513 Fordem Terrace', 'Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Path', '7 Thompson Center', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Beach Cove', '4 Ridgeway Alley', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Way', '5 Hauk Way', 'Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Rooftop Deck', '1162 International Center', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '10 Pawling Hill', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, s_address, descrip) values ('Quality Control', '6627 Eastwood Plaza', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Medical Lab', '03 Dorton Center', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Pedestrian Bridge', '50801 Barby Place', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Canal Bridge', '793 Park Meadow Avenue', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Tech Hub', '6 Nevada Hill', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '1 Corry Trail', 'Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Pine Forest', '48 Kinsman Junction', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Armorer’s Bench', '9152 Macpherson Avenue', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Sacred Spring', '97780 Arrowood Road', 'Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Pit Stop', '6340 Parkside Road', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Craft Workshop', '0896 Fairview Hill', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Great Hall', '6 Esker Junction', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Quality Control', '255 Elmside Drive', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Fletcher’s Shop', '9 Kipling Lane', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Foggy Bridge', '6581 Brown Pass', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Reflection Pool', '3 8th Terrace', 'Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Sand Dune', '1085 Veith Plaza', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Al-Expert Hub', '93599 Cardinal Place', 'Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Secret Passage', '59405 Basil Plaza', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Situation Room', '09 Blaine Circle', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Brewery Courtyard', '0 Stephen Street', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Hidden Garden', '1 Schlimgen Hill', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('North Ridge', '48624 Debra Park', 'Morbi a ipsum. Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Genetic Trail', '364 Towne Lane', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Forest Clearing', '814 Badeau Trail', 'Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Hay Loft', '178 Moland Place', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Botanical Garden Pond', '787 Corry Street', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Sheet Music Library', '9 Kedzie Alley', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Cabana Row', '529 Chive Lane', 'Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Mixology Station', '21053 Anhalt Lane', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Study Desk', '63569 Lawn Trail', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Enigma Room', '7704 Donald Way', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Harvest Barn', '42 Clyde Gallagher Parkway', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into STATION (s_name, s_address, descrip) values ('VIP Lounge', '5 Kingsford Pass', 'Integer a nibh. In quis justo.');
insert into STATION (s_name, s_address, descrip) values ('Bottling Line', '147 International Parkway', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Oak Grove', '05 Scofield Pass', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Nomad Camp', '29477 Independence Junction', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Eagle Nest', '5 Straubel Junction', 'Pellentesque eget nunc.');
insert into STATION (s_name, s_address, descrip) values ('Physics Amphitheater', '60 Ronald Regan Way', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Trophy Hall', '91068 Susan Crossing', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Rabbit Hole', '3 Morrow Trail', 'Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Slope', '0 Goodland Court', 'Integer a nibh. In quis justo.');
insert into STATION (s_name, s_address, descrip) values ('Shell Beach', '3925 Columbus Way', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Antique Shop Corner', '4 Dixon Lane', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Lab Wing', '42669 Thierer Hill', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Weaver’s Loom', '28 Sullivan Lane', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Export Dock', '12 Thierer Court', 'Duis bibendum.');
insert into STATION (s_name, s_address, descrip) values ('Grand Cathedral', '34 Linden Junction', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Liberty Square', '3119 Shopko Court', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Farm Stand', '4 Corben Circle', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Boarding Gate', '969 Mockingbird Drive', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Tea House', '16 Elgar Road', 'Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Nightclub Entry', '2243 Straubel Street', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Runway Threshold', '59 Calypso Terrace', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Cryptography Cell', '1839 Pierstorff Lane', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Logistics Center', '86532 Hoepker Plaza', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Attic', '4 Brown Circle', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Stream Crossing', '2 Fairview Street', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Investor Gallery', '2 Goodland Junction', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Foggy Bridge', '36 Atwood Drive', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Triage Center', '21866 Glendale Circle', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Riverfront Pier', '228 Melrose Way', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Academic Atrium', '6766 Thompson Junction', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Medical Lab', '00 Twin Pines Drive', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Ash Plain', '35548 Twin Pines Lane', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('South Port', '541 Everett Street', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Data Farm', '2 Ridgeway Pass', 'Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Bottling Line', '26 Magdeline Crossing', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Secret Passage', '6 Forest Run Plaza', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '99057 Kropf Parkway', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Logistics Center', '49333 Westport Crossing', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Manufacturing Floor', '6607 Shopko Avenue', 'Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Silver Mine', '419 Sugar Circle', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Royal Gardens', '880 Meadow Vale Street', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Knight’s Table', '44 Buhler Circle', 'Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Shell Beach', '54972 Roth Alley', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Deer Track', '44 Debra Park', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Dugout', '98 Rigney Hill', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Archaeology Grid', '4086 Haas Junction', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Media Zone', '96558 Donald Court', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Meditation Rock', '59 Schurz Trail', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Limestone Arch', '47623 Laurel Place', 'Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Customs Office', '604 Atwood Point', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Genetic Trail', '2 6th Point', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Slope', '35372 Onsgard Court', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Blue Hole', '89 Moulton Crossing', 'Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('War Room', '7640 Waubesa Circle', 'In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('West Wing', '32 Declaration Road', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Nomad Camp', '73649 Oakridge Parkway', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Clockwork Square', '891 North Place', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Otter Slide', '63 Bowman Street', 'Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Launch Pad', '7 Prairie Rose Point', 'Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Shore', '179 Spenser Crossing', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Engineering Block', '49274 Scoville Court', 'Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Sign', '09 Corscot Drive', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Shadow Archway', '3179 Nobel Avenue', 'Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Weaving Shed', '9 Golden Leaf Plaza', 'Fusce consequat. Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Coal Seam', '10981 Hanson Place', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Sign', '45652 Corben Crossing', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Server Room', '3048 Truax Circle', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Surgery Suite', '9 Bartillon Plaza', 'Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Alumni Walk', '63324 Nancy Crossing', 'Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Rapid Run', '487 8th Terrace', 'Etiam justo. Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Central Fountain', '7 Moulton Road', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Industrial Loft', '04 Browning Road', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Cobblestone Alley', '77126 Merchant Circle', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Victory Arch', '3722 Brentwood Center', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Treasury Room', '79434 Transport Road', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Sculptural Park', '36 Mcbride Plaza', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Campus Green', '510 Debs Park', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Bear Cave', '28 Rigney Hill', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Records Room', '80027 Oxford Lane', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Cheese Cellar', '489 Talmadge Court', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, s_address, descrip) values ('Lily Pad', '871 Corry Alley', 'Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Hedge', '29 Clove Street', 'Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Glade', '89887 International Parkway', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Peak', '71 Boyd Parkway', 'Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Valley Floor', '50 Lakeland Way', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Harbor Viewpoint', '250 Michigan Point', 'Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Textile Mill', '49 Merrick Circle', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Library Stacks', '4762 Service Crossing', 'Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Diamond Vault', '892 La Follette Drive', 'Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Way', '49 Hansons Drive', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Goal Post', '730 Lakeland Drive', 'Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Greenhouse Row', '76993 Center Parkway', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Sculptural Park', '568 Northview Avenue', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Mews', '05556 7th Road', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Tide Pool', '37806 Cody Road', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Mountain Pass', '71496 Jana Circle', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Slope', '0023 Sutteridge Hill', 'Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Wall', '22 Raven Hill', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Shady Nook', '794 Steensland Parkway', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Brewery Courtyard', '7073 Menomonie Drive', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Soundboard', '3 Cottonwood Parkway', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into STATION (s_name, s_address, descrip) values ('Trail', '00328 Spenser Drive', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Curator’s Secret.', '785 Holmberg Plaza', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '19604 Moose Junction', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Launch Pad', '9221 Blaine Court', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Barrel Room', '4849 Morrow Parkway', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Hidden Garden', '18205 Eggendart Park', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '76860 Portage Road', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Hummingbird Lane', '526 Dapin Junction', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into STATION (s_name, s_address, descrip) values ('Scene Shop', '8268 Scott Trail', 'Suspendisse ornare consequat lectus.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '1 7th Way', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Spa Entrance', '1 Loftsgordon Avenue', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Patent Wall', '74462 Donald Circle', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Cave Entrance', '194 Mesta Street', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Haunted Shack', '08 Springview Place', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Wine Vault', '083 Havey Trail', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Antique Shop Corner', '434 Duke Alley', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Cliffside Stairs', '557 Debra Hill', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Cliff', '00925 Columbus Street', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Timeline Wall', '90 Schmedeman Crossing', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into STATION (s_name, s_address, descrip) values ('Robotics Lab', '12575 Namekagon Street', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Landmark', '27721 Moulton Place', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Medal Stand', '4 Cambridge Avenue', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Post', '974 Elka Way', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Badger Set', '89225 Green Park', 'Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Medal Stand', '97623 Harper Road', 'Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Nightclub Entry', '660 Helena Terrace', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Bank', '03 Del Mar Court', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Fossil Bed', '9 Independence Lane', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Plaque', '4 Burrows Parkway', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Secret Passage', '33047 Red Cloud Road', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Bandit Camp', '1 Montana Hill', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Porch', '14 Hansons Place', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Street Art Wall', '137 Farmco Parkway', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Gourmet Food Hall', '19935 Waxwing Park', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '10551 Union Crossing', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Startup Garage', '382 Dunning Parkway', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Pedestrian Bridge', '78288 Anderson Pass', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Kelp Forest', '56652 Tomscot Avenue', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Restoration Lab', '61 Bonner Hill', 'Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Waterfall Base', '4 Shasta Plaza', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Street', '3 Marquette Hill', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '7181 Dapin Place', 'Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Victory Arch', '346 Welch Lane', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Smithy', '818 Boyd Hill', 'Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Boulevard', '61949 Wayridge Junction', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Manufacturing Floor', '77 Brickson Park Avenue', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Labeling Station', '7 Bunting Circle', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('VR Simulation Room', '4317 Ilene Pass', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '44 Maple Wood Avenue', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Athlete Tunnel', '22062 Scoville Way', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Museum Lobby', '4 Myrtle Center', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Windsock', '47161 Rusk Center', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Diamond Vault', '8 Sauthoff Plaza', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Sunny Glade', '1737 Oakridge Drive', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Sand Bar', '27268 Randy Circle', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Engineering Block', '64782 Kingsford Place', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into STATION (s_name, s_address, descrip) values ('Armor Rack', '52 Linden Way', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Enigma Room', '9 Di Loreto Court', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Philosophy Garden', '44190 Anhalt Court', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Craft Workshop', '9035 Clyde Gallagher Trail', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Ancient Manuscript Room', '9 Claremont Junction', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Shore', '12318 Eggendart Lane', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Squirrel Scramble', '54 Johnson Terrace', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Volleyball Court', '419 Eggendart Plaza', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Slope', '96785 Toban Alley', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Crossing', '5967 Tennyson Parkway', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Patio', '230 Golf View Alley', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Weaving Shed', '25762 Annamark Pass', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Starry Deck', '4328 Heffernan Lane', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Radiology Wing', '319 Hintze Hill', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Yoga Studio', '9 Porter Drive', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Rabbit Hole', '013 Heffernan Place', 'Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Corner Tavern', '411 Saint Paul Crossing', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Mixer Station', '6559 Hoepker Drive', 'Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Cellar Door', '210 Trailsway Plaza', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Transit Lounge', '86377 Kim Plaza', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Alley', '41 Moose Road', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Crescent', '43991 Scofield Plaza', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Rocky Ridge', '89 Anzinger Terrace', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Peak', '43207 North Avenue', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Observatory Dome', '7349 Tony Junction', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Calm Creek', '83 Maryland Trail', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Transit Lounge', '527 Cordelia Junction', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Timeline Wall', '756 Shasta Place', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Stream Crossing', '2769 Straubel Junction', 'Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Street Art Wall', '5 Pennsylvania Street', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Tennis Net', '76 Pierstorff Center', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Badger Set', '294 2nd Street', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Eagle Nest', '0 Holmberg Junction', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Mews', '182 Scoville Alley', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Square', '830 Alpine Street', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Spa Entrance', '92 Warrior Drive', 'Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Sunset Point', '3294 8th Circle', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Rabbit Hole', '5 Truax Crossing', 'Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Observation Tower', '824 Sheridan Park', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('East Gate', '8 Lyons Park', 'Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Innovation Lab', '75 Loftsgordon Place', 'Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Research Archive', '36 Nova Road', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Phantom Lane', '045 Barby Lane', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into STATION (s_name, s_address, descrip) values ('Archive Basement', '22 Lawn Court', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Fossil Bed', '8 Anthes Hill', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Interview Wall', '9 Banding Pass', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '6952 Kinsman Hill', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Tool Crib', '784 Kenwood Alley', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Pedestal', '1523 Southridge Avenue', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Distribution Center', '4 Garrison Pass', 'Pellentesque eget nunc.');
insert into STATION (s_name, s_address, descrip) values ('Yoga Studio', '2643 Eastlawn Point', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Pedestal', '81 Montana Crossing', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Underwater Cave', '78 Becker Alley', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Gold Vein', '2805 Linden Pass', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Zen Garden', '2 Oriole Road', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Lava Tube', '789 Forster Center', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Cave Entrance', '98 Gale Hill', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Recovery Room', '2892 Bultman Road', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Cocktail Bar', '885 Comanche Way', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Knight’s Table', '538 Grasskamp Avenue', 'Donec quis orci eget orci vehicula condimentum.');
insert into STATION (s_name, s_address, descrip) values ('Memorial Statue', '41995 Banding Alley', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Lobby Bar', '176 Crownhardt Place', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Craft Workshop', '19729 Westerfield Plaza', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Dugout', '2095 Delladonna Court', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('First Aid Post', '8584 Old Gate Plaza', 'Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Lab Bench', '988 Colorado Court', 'Morbi a ipsum. Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Fence', '05167 Ronald Regan Alley', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Innovation Lab', '62387 Village Green Avenue', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Cursed Well', '7136 Bashford Drive', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Opera House Foyer', '71864 Knutson Circle', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Basin', '270 Weeping Birch Parkway', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, s_address, descrip) values ('Knight’s Table', '0 Columbus Park', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Spice Market Entrance', '920 Di Loreto Pass', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Eco-Trail Marker', '45323 Glendale Pass', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Rune Stone', '347 Londonderry Court', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Hermit Cave', '7 Heath Trail', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Victorian Row', '67223 Declaration Junction', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Riverfront Pier', '3369 International Alley', 'Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Orchard Gate', '6 Nancy Avenue', 'Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Castle Courtyard', '73 Tomscot Center', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Fuel Depot', '8718 Springview Court', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Great Hall', '562 Main Center', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Press Box', '5 Vernon Trail', 'Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Gourmet Food Hall', '0 Gerald Crossing', 'Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Harbor Viewpoint', '88564 Hudson Road', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Neon Street', '3 Forest Hill', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Lava Tube', '89 Sloan Alley', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Old Mill', '27 Bonner Junction', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Antique Shop Corner', '8065 Stephen Place', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Porch', '6329 Sullivan Trail', 'Integer ac neque. Duis bibendum.');
insert into STATION (s_name, s_address, descrip) values ('Street Art Wall', '5409 Hooker Center', 'Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Museum Lobby', '40999 Northland Center', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Infinity Edge', '15 Steensland Road', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Permafrost Layer', '1773 Sachtjen Plaza', 'Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Hotel Lounge', '6 Forster Terrace', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Ash Plain', '5 Cordelia Plaza', 'Phasellus sit amet erat. Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Parapet', '78 Summerview Hill', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Banner Row', '04335 Forest Terrace', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Boulevard', '03098 Fallview Point', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Podcast Booth', '20377 Waxwing Court', 'Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Ice Berg', '6 Arizona Avenue', 'Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Beach Bar', '43 Kedzie Crossing', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Zen Garden', '75 Fremont Avenue', 'Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Cargo Dock', '02 Bobwhite Circle', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Sauna Entrance', '5181 Hansons Center', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('VIP Box', '52 Rockefeller Trail', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Urban Orchard', '224 Magdeline Terrace', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Orchestra Pit', '27116 Ludington Plaza', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Phantom Lane', '7 Hintze Hill', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Cellar', '4472 Elmside Avenue', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Al-Expert Hub', '34 Hooker Parkway', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Misty Valley', '6 Ridgeway Pass', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Tea House', '74782 Sloan Point', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Rim', '1 Arizona Circle', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Academic Atrium', '0 Macpherson Point', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Basketball Hoop', '7 Elka Terrace', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Thunder Peak', '18 Caliangt Way', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Mud Pot', '65 Union Park', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Overpass', '93 Sunnyside Place', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Dig Site', '874 Schmedeman Center', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Garden Shed', '8 Boyd Crossing', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, s_address, descrip) values ('Underpass', '69 Towne Hill', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Research Archive', '6005 Esch Way', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Tunnel', '9 Anderson Terrace', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Badger Set', '76 Briar Crest Street', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Larder', '21880 Manufacturers Parkway', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Sand Bar', '02941 Warbler Parkway', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Amber Deposit', '86907 Drewry Center', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Modern Art Muse', '20426 Trailsway Hill', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Crest', '26 Beilfuss Crossing', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Port Authority', '36573 Hintze Junction', 'In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Maintenance Bay', '4 Sullivan Circle', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Engineering Block', '4 Welch Street', 'Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Pillar', '68002 Barby Trail', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Gold Vein', '5723 Stoughton Terrace', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Alchemy Table', '18733 Stone Corner Crossing', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Fortress Wall', '185 Farmco Crossing', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Row', '4457 Beilfuss Park', 'Etiam justo. Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Command Post', '4 Village Point', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Runway Threshold', '81733 Bluestem Point', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Attic', '5237 Center Plaza', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Fermentation Lab', '4851 Debra Alley', 'Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Lab Wing', '2039 Chinook Drive', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Ice Bath', '6 Dapin Avenue', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Mountain Trailhead', '17739 Lotheville Drive', 'Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Slope', '0 Glendale Parkway', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Puzzle Box', '405 Hanover Parkway', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Sun Deck', '4691 North Point', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Beach Bar', '1 Barby Junction', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Riverside Path', '360 Pankratz Lane', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Calm Creek', '49 Orin Crossing', 'Morbi a ipsum.');
insert into STATION (s_name, s_address, descrip) values ('East Gate', '2785 Mayer Way', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Situation Room', '4 Gateway Terrace', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Rooftop Deck', '11951 Ridge Oak Trail', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Steam Room', '5027 Heffernan Avenue', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Suite 101', '42 Blue Bill Park Park', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Hedge', '77909 Waxwing Point', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Tea House', '6371 Ohio Crossing', 'Fusce consequat. Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Sunset Point', '6 Stoughton Alley', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Smokehouse', '59 Cardinal Way', 'Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Kelp Forest', '8 Bunker Hill Junction', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Hall of Fame', '03 Southridge Street', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Mud Pot', '8 Darwin Circle', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Windsock', '2657 Aberg Court', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Museum Lobby', '1 Lighthouse Bay Park', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
