insert into STATION (s_name, addres, description) values ('Jewelry Row', '55 Fieldstone Lane', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, addres, description) values ('Glass Elevator', '21 Dovetail Park', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into STATION (s_name, addres, description) values ('Coast', '5752 Donald Street', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, addres, description) values ('Art Gallery Lane', '0 Mcguire Trail', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Dugout', '2 Kedzie Alley', 'Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('Hidden Courtyard', '405 Elmside Center', 'Duis ac nibh.');
insert into STATION (s_name, addres, description) values ('Sideline', '4 Comanche Crossing', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, addres, description) values ('Butterfly Bush', '88 Northridge Circle', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, addres, description) values ('Visitor Center', '2 Lunder Road', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, addres, description) values ('Cellar', '5 Delaware Place', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, addres, description) values ('Diamond Vault', '51 Anderson Point', 'Morbi ut odio.');
insert into STATION (s_name, addres, description) values ('Marble Arch', '08695 Schurz Junction', 'Aenean fermentum.');
insert into STATION (s_name, addres, description) values ('Dean’s Office', '05 John Wall Park', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, addres, description) values ('Throne Room', '45712 Express Lane', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, addres, description) values ('Cliffside Stairs', '08 Superior Junction', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, addres, description) values ('Skywalk Entry', '9 Mariners Cove Court', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, addres, description) values ('Cellar Door', '8 Roxbury Way', 'Nunc purus.');
insert into STATION (s_name, addres, description) values ('Industrial Loft', '98 Merrick Park', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, addres, description) values ('Opera House Foyer', '9 Tennyson Lane', 'Curabitur convallis.');
insert into STATION (s_name, addres, description) values ('Badger Set', '7845 Sutteridge Avenue', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, addres, description) values ('Attic Window', '47018 Blaine Circle', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, addres, description) values ('Passage', '98179 Walton Way', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, addres, description) values ('Bakery Corner', '55405 Banding Park', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, addres, description) values ('Eagle Nest', '0 Eliot Place', 'Nam nulla.');
insert into STATION (s_name, addres, description) values ('Skywalk Entry', '479 Golf View Center', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into STATION (s_name, addres, description) values ('Coworking Courtyard', '1633 6th Trail', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, addres, description) values ('Glacial Path', '334 Dorton Circle', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, addres, description) values ('Valley', '83007 Summit Park', 'Integer ac neque. Duis bibendum.');
insert into STATION (s_name, addres, description) values ('Waterfront Promenade', '1713 Forest Plaza', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, addres, description) values ('Grandstand', '3 Quincy Avenue', 'Nulla justo.');
insert into STATION (s_name, addres, description) values ('Zen Garden', '45219 Derek Court', 'Integer ac neque.');
insert into STATION (s_name, addres, description) values ('Nature Boardwalk', '322 Swallow Trail', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Waterfront Promenade', '964 Arapahoe Way', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, addres, description) values ('Suite 101', '32 Melvin Point', 'Morbi a ipsum.');
insert into STATION (s_name, addres, description) values ('Cinema Row', '4618 Starling Junction', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, addres, description) values ('Bistro Table', '835 Northfield Circle', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, addres, description) values ('Harvest Barn', '31 3rd Court', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Oak Grove', '4604 Melrose Plaza', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Library Steps', '3 Hooker Road', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, addres, description) values ('Squirrel Scramble', '214 Graedel Trail', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Secret Passage', '71282 Sheridan Crossing', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into STATION (s_name, addres, description) values ('Spice Market Entrance', '1 Northridge Road', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, addres, description) values ('Suite 101', '7195 Carey Street', 'Quisque porta volutpat erat.');
insert into STATION (s_name, addres, description) values ('Chef’s Table', '2 Dahle Point', 'Nulla ac enim.');
insert into STATION (s_name, addres, description) values ('Old Mill', '564 Esch Drive', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, addres, description) values ('Fish Ladder', '86 Bunker Hill Circle', 'Nullam varius.');
insert into STATION (s_name, addres, description) values ('Wall', '8658 Colorado Hill', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, addres, description) values ('Sculptural Park', '807 Express Trail', 'Ut tellus.');
insert into STATION (s_name, addres, description) values ('Reading Nook', '9869 Scofield Alley', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into STATION (s_name, addres, description) values ('Secret Passage', '82489 Bunker Hill Point', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, addres, description) values ('Canal Bridge', '899 Hoard Center', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into STATION (s_name, addres, description) values ('Marker', '07 Springview Junction', 'Aenean sit amet justo.');
insert into STATION (s_name, addres, description) values ('Jazz Club Corner', '1 3rd Crossing', 'Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Skywalk Entry', '329 Elgar Junction', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, addres, description) values ('Cliffside Stairs', '60771 Aberg Junction', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, addres, description) values ('Otter Slide', '0 Starling Way', 'Nulla tellus.');
insert into STATION (s_name, addres, description) values ('Foggy Bridge', '932 Westend Crossing', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Path', '43650 4th Junction', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, addres, description) values ('Farm Stand', '669 Jenifer Junction', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, addres, description) values ('Craft Workshop', '17 Bunker Hill Point', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, addres, description) values ('Observation Tower', '882 Sachs Center', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into STATION (s_name, addres, description) values ('Suite Entrance', '20 Oak Valley Center', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('VIP Box', '14182 Packers Crossing', 'Vivamus tortor.');
insert into STATION (s_name, addres, description) values ('Deer Track', '92 Del Mar Way', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, addres, description) values ('Sign', '7 Reinke Alley', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, addres, description) values ('Fortress Wall', '170 Harbort Alley', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Server Room', '952 Marquette Point', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, addres, description) values ('Spa Entrance', '0 Towne Street', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into STATION (s_name, addres, description) values ('Hummingbird Lane', '114 Steensland Pass', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, addres, description) values ('Server Room', '329 Bartelt Park', 'Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, addres, description) values ('Wildflower Field', '14059 Crescent Oaks Trail', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into STATION (s_name, addres, description) values ('Garden Shed', '67773 Moulton Drive', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, addres, description) values ('Lecture Hall', '381 Surrey Parkway', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, addres, description) values ('Runway End', '47 Bluejay Alley', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, addres, description) values ('Mountain Trailhead', '47 Graedel Way', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, addres, description) values ('Podium', '10191 Commercial Place', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, addres, description) values ('Locker Room', '618 Michigan Center', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Glade', '09 Anthes Center', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, addres, description) values ('Victorian Row', '319 Randy Junction', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, addres, description) values ('Meadow View', '8 Dottie Way', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, addres, description) values ('Misty Valley', '0 Russell Alley', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, addres, description) values ('Coffee Roastery', '03164 Hoffman Point', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, addres, description) values ('Lecture Hall', '72747 Lakeland Avenue', 'Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Valley', '003 Erie Road', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, addres, description) values ('Basement Pub', '7618 Tomscot Avenue', 'Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, addres, description) values ('Old Mill', '9942 Heffernan Point', 'Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, addres, description) values ('Sideline', '4 Fieldstone Circle', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, addres, description) values ('Dean’s Office', '173 6th Center', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, addres, description) values ('Mystery Gate', '275 Lotheville Center', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, addres, description) values ('Cinema Row', '852 Pine View Street', 'Integer non velit.');
insert into STATION (s_name, addres, description) values ('Valley', '5 Vernon Place', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, addres, description) values ('Stone Circle', '36 Hauk Center', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Central Fountain', '1316 David Parkway', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Canyon Rim', '13648 Hooker Court', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, addres, description) values ('Pit Stop', '072 Fair Oaks Junction', 'Aenean sit amet justo.');
insert into STATION (s_name, addres, description) values ('Castle Courtyard', '64 1st Drive', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Woods', '6 Buell Park', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, addres, description) values ('Avenue', '28 Lotheville Plaza', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into STATION (s_name, addres, description) values ('Underpass', '0 Crowley Center', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, addres, description) values ('Skyline Balcony', '7 Darwin Drive', 'Sed ante. Vivamus tortor.');
insert into STATION (s_name, addres, description) values ('Badger Set', '6 Longview Drive', 'Nam nulla.');
insert into STATION (s_name, addres, description) values ('Banquet Hall', '01795 Mockingbird Point', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, addres, description) values ('Waterfall Base', '858 Upham Way', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, addres, description) values ('Ancient Stone Bridge', '6 Arizona Circle', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, addres, description) values ('Neon Street', '5 Schmedeman Terrace', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('Ring Side', '96 School Center', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, addres, description) values ('Patio', '52 Mcguire Hill', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, addres, description) values ('Lake Shore', '754 Warner Center', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into STATION (s_name, addres, description) values ('Starting Block', '935 Del Sol Pass', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Avenue', '16325 Northport Park', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, addres, description) values ('Midnight Alley', '7 Rigney Lane', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into STATION (s_name, addres, description) values ('Beaver Dam', '6 Warbler Park', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into STATION (s_name, addres, description) values ('Rim', '9307 Jenna Way', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, addres, description) values ('Fashion Boutique', '2 Bashford Pass', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, addres, description) values ('Hedge', '158 Village Green Place', 'Sed ante.');
insert into STATION (s_name, addres, description) values ('Fish Ladder', '8 Cherokee Plaza', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, addres, description) values ('Coast', '93 Beilfuss Court', 'Proin eu mi.');
insert into STATION (s_name, addres, description) values ('Breezy Point', '8179 Northview Place', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, addres, description) values ('Sand Dune', '65 Moose Junction', 'Etiam faucibus cursus urna.');
insert into STATION (s_name, addres, description) values ('North Ridge', '121 Hauk Trail', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, addres, description) values ('Antique Shop Corner', '2 Lyons Road', 'Duis aliquam convallis nunc.');
insert into STATION (s_name, addres, description) values ('Central Fountain', '42197 Oneill Lane', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, addres, description) values ('Cellar Door', '5321 Mifflin Place', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, addres, description) values ('Chocolate Factory', '110 Everett Court', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, addres, description) values ('Pebble Path', '4069 Eggendart Alley', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, addres, description) values ('Alley', '3547 Chive Way', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam vel augue.');
insert into STATION (s_name, addres, description) values ('Badger Set', '1 Summit Plaza', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, addres, description) values ('Wildflower Field', '2025 Menomonie Road', 'Nam nulla.');
insert into STATION (s_name, addres, description) values ('Marble Arch', '03 David Street', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, addres, description) values ('Junction', '194 Thompson Pass', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, addres, description) values ('Attic Window', '19979 Goodland Parkway', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, addres, description) values ('Peak', '673 Lukken Place', 'Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, addres, description) values ('Border', '879 Bay Road', 'Morbi non lectus.');
insert into STATION (s_name, addres, description) values ('Classroom A', '1 Sauthoff Park', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('West Wing', '8 David Trail', 'Integer ac leo.');
insert into STATION (s_name, addres, description) values ('Twilight Pier', '34771 Gateway Plaza', 'Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Treasury Room', '0 Rieder Street', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, addres, description) values ('Underpass', '04718 Warner Parkway', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, addres, description) values ('Phantom Lane', '15 Shoshone Road', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, addres, description) values ('Shell Beach', '361 Sunnyside Crossing', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Bistro Table', '410 Drewry Parkway', 'Etiam vel augue.');
insert into STATION (s_name, addres, description) values ('Cursed Well', '434 Mayer Hill', 'Integer ac neque.');
insert into STATION (s_name, addres, description) values ('Misty Valley', '27 Tennyson Circle', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, addres, description) values ('North Ridge', '1964 Shoshone Street', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.');
insert into STATION (s_name, addres, description) values ('Pantry', '702 Glacier Hill Pass', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, addres, description) values ('Suite Entrance', '84706 Oxford Terrace', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('Throne Room', '6512 Brickson Park Plaza', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, addres, description) values ('Starting Block', '0729 Gerald Crossing', 'Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, addres, description) values ('Hollow', '9 Shelley Hill', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, addres, description) values ('Foggy Bridge', '97535 Kensington Place', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, addres, description) values ('Peak Summit', '586 Lyons Drive', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into STATION (s_name, addres, description) values ('Terrace Grill', '8 American Ash Parkway', 'Morbi a ipsum. Integer a nibh.');
insert into STATION (s_name, addres, description) values ('Sunny Glade', '21300 Judy Drive', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, addres, description) values ('Road', '5897 Bay Place', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, addres, description) values ('Fish Ladder', '6 Waubesa Hill', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, addres, description) values ('Art Gallery Lane', '0 Anthes Drive', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Pantry', '3 3rd Way', 'Fusce consequat.');
insert into STATION (s_name, addres, description) values ('Coffee Roastery', '208 Nevada Junction', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('Arch', '6942 Sachs Road', 'Aenean sit amet justo.');
insert into STATION (s_name, addres, description) values ('Tea House', '2985 Dwight Pass', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, addres, description) values ('Attic', '4 Anderson Way', 'Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Balcony', '4 Grover Center', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, addres, description) values ('Lab Wing', '57 Bayside Street', 'Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, addres, description) values ('Startup Space', '56854 Dixon Trail', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Spice Market Entrance', '3670 Thierer Parkway', 'Ut tellus.');
insert into STATION (s_name, addres, description) values ('Grandstand', '1 Hollow Ridge Junction', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, addres, description) values ('Local Artisan Market', '793 Vermont Center', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, addres, description) values ('Zen Garden', '6451 American Place', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Mountain Trailhead', '1549 Hagan Alley', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, addres, description) values ('Gourmet Food Hall', '34986 Morningstar Place', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, addres, description) values ('Craft Workshop', '44 Sachtjen Crossing', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, addres, description) values ('Beacon', '307 Mcguire Center', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, addres, description) values ('Bakery Corner', '8122 Hintze Circle', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, addres, description) values ('Crossing', '4342 Merchant Point', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, addres, description) values ('Street Art Wall', '00772 Troy Way', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, addres, description) values ('Pillar', '084 Pearson Way', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, addres, description) values ('Press Box', '305 Moulton Junction', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, addres, description) values ('Mews', '4616 Saint Paul Park', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Nature Boardwalk', '296 Almo Junction', 'Aenean auctor gravida sem.');
insert into STATION (s_name, addres, description) values ('Cave Entrance', '6541 Maple Wood Center', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, addres, description) values ('Rooftop Bar', '82 Maywood Road', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, addres, description) values ('Coral Reef Point', '26 Mallory Place', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, addres, description) values ('Peak', '0646 Norway Maple Pass', 'Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, addres, description) values ('Court Side', '4 Waywood Circle', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, addres, description) values ('Canyon Rim', '36 Homewood Lane', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, addres, description) values ('Column', '7 Saint Paul Junction', 'Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Attic', '4825 Cambridge Pass', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, addres, description) values ('Sand Dune', '16852 Bartelt Street', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, addres, description) values ('Medal Stand', '489 Lyons Hill', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, addres, description) values ('Observation Tower', '7 Sachtjen Pass', 'Suspendisse ornare consequat lectus.');
insert into STATION (s_name, addres, description) values ('Moonlight Path', '32890 Vermont Road', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into STATION (s_name, addres, description) values ('Sideline', '9 Northport Terrace', 'Nunc purus.');
insert into STATION (s_name, addres, description) values ('Court Side', '597 Hazelcrest Terrace', 'Nullam varius.');
insert into STATION (s_name, addres, description) values ('Diamond Vault', '9173 Parkside Alley', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, addres, description) values ('Mews', '4 Arizona Street', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Bridge', '88036 Darwin Hill', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, addres, description) values ('Antique Shop Corner', '9 Swallow Plaza', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, addres, description) values ('Beaver Dam', '9 Morrow Trail', 'Aliquam erat volutpat.');
insert into STATION (s_name, addres, description) values ('Mews', '1922 Spenser Street', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, addres, description) values ('Liberty Square', '90 Vernon Plaza', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into STATION (s_name, addres, description) values ('Willow Pond', '7165 Swallow Pass', 'Aliquam non mauris.');
insert into STATION (s_name, addres, description) values ('Tool Workshop', '58 Warbler Court', 'Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Starting Block', '1725 Clove Avenue', 'Duis mattis egestas metus.');
insert into STATION (s_name, addres, description) values ('Hidden Garden', '5 Bunting Junction', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, addres, description) values ('City Hall Plaza', '34 Kropf Junction', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, addres, description) values ('Downtown Hub', '49860 Maple Alley', 'Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Eagle Nest', '81 Main Point', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, addres, description) values ('Flower Stall', '631 Larry Way', 'Ut tellus.');
insert into STATION (s_name, addres, description) values ('Courtyard', '17 Crownhardt Court', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, addres, description) values ('Frog Pond', '86508 Sauthoff Parkway', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Victorian Row', '516 Messerschmidt Trail', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Beach', '29007 Eastlawn Point', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, addres, description) values ('Dugout', '322 Kim Plaza', 'Etiam faucibus cursus urna.');
insert into STATION (s_name, addres, description) values ('Pillar', '03 Moose Circle', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, addres, description) values ('Sacred Grove', '80296 Kingsford Junction', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, addres, description) values ('Fortress Wall', '255 Dexter Trail', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, addres, description) values ('Alumni Walk', '87 Hintze Hill', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('West Wing', '8 Bunker Hill Crossing', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, addres, description) values ('Armory', '8 Arrowood Junction', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, addres, description) values ('Cellar Door', '46592 Buell Park', 'Nulla facilisi.');
insert into STATION (s_name, addres, description) values ('Smuggler’s Tunnel', '3 Merrick Plaza', 'Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, addres, description) values ('Meditation Hall', '6 Fisk Hill', 'Nulla tellus.');
insert into STATION (s_name, addres, description) values ('Intersection', '834 Marcy Circle', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, addres, description) values ('Waterfront Promenade', '97 Tony Park', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Porch', '10724 Utah Plaza', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('Vault Entry', '82 Sullivan Alley', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, addres, description) values ('Enigma Room', '72 Nelson Road', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Hidden Courtyard', '77 Clyde Gallagher Lane', 'Nunc nisl.');
insert into STATION (s_name, addres, description) values ('Road', '066 Ronald Regan Way', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, addres, description) values ('Edge', '9759 Gerald Alley', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into STATION (s_name, addres, description) values ('Village Square', '540 High Crossing Alley', 'Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Sideline', '80188 Alpine Road', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, addres, description) values ('Theater District Sign', '96 Butternut Lane', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, addres, description) values ('Patio', '7 Bluestem Road', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, addres, description) values ('Passage', '0 Fremont Park', 'Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Weaver’s Loom', '2986 Lukken Crossing', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, addres, description) values ('Thunder Peak', '196 Jay Way', 'Nulla tempus.');
insert into STATION (s_name, addres, description) values ('Misty Valley', '642 Kropf Road', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, addres, description) values ('Launch Pad', '6 Nova Point', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, addres, description) values ('Vault Entry', '3135 Jenifer Court', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, addres, description) values ('Bear Cave', '0 Katie Court', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, addres, description) values ('Training Ground', '17 Continental Center', 'Vivamus tortor.');
insert into STATION (s_name, addres, description) values ('Nomad Camp', '55 North Point', 'Nulla tempus.');
insert into STATION (s_name, addres, description) values ('Trail', '8 Schurz Parkway', 'Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Safari Outpost', '7 Barby Road', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into STATION (s_name, addres, description) values ('Waterfall Base', '54 Everett Terrace', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Reading Nook', '31117 Blaine Trail', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, addres, description) values ('South Port', '843 Troy Plaza', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, addres, description) values ('Summit', '76758 Melody Plaza', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, addres, description) values ('Lab Wing', '3835 Park Meadow Center', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, addres, description) values ('Scholar’s Hall', '7 Grover Plaza', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, addres, description) values ('Cellar', '126 Talmadge Park', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, addres, description) values ('Skyline Balcony', '00219 Nelson Center', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, addres, description) values ('Dungeon Cell', '9 Mccormick Street', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, addres, description) values ('Morning Terrace', '66720 Fordem Road', 'Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Antique Shop Corner', '8448 Melrose Drive', 'Aenean lectus.');
insert into STATION (s_name, addres, description) values ('Hedge', '7 Ryan Center', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, addres, description) values ('Post', '81971 Eagan Drive', 'Donec ut dolor.');
insert into STATION (s_name, addres, description) values ('Ballet Studio', '85283 Toban Lane', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Scholar’s Hall', '22 5th Junction', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, addres, description) values ('Arch', '70 Crownhardt Alley', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, addres, description) values ('Press Box', '782 Corry Alley', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Practice Field', '9210 Carioca Crossing', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, addres, description) values ('Main Entrance', '6 Atwood Road', 'Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, addres, description) values ('Frog Pond', '22428 Grasskamp Terrace', 'Nunc nisl.');
insert into STATION (s_name, addres, description) values ('Local Artisan Market', '39954 East Circle', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into STATION (s_name, addres, description) values ('Canal Bridge', '2595 Morningstar Street', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, addres, description) values ('City Hall Plaza', '290 Merrick Terrace', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('Cellar Door', '0 Sheridan Street', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, addres, description) values ('Alumni Walk', '51814 Rieder Trail', 'Nulla facilisi.');
insert into STATION (s_name, addres, description) values ('Glacial Path', '0 Gale Court', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, addres, description) values ('Server Room', '51333 Spenser Parkway', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, addres, description) values ('Hollow', '5 Sundown Court', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, addres, description) values ('Mystery Gate', '2 Springs Drive', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, addres, description) values ('Riverside Path', '73 Steensland Crossing', 'Proin eu mi.');
insert into STATION (s_name, addres, description) values ('Ridge', '8 Fair Oaks Terrace', 'Etiam justo. Etiam pretium iaculis justo.');
insert into STATION (s_name, addres, description) values ('Nature Boardwalk', '526 Caliangt Plaza', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Training Ground', '86 Clove Place', 'Aenean lectus.');
insert into STATION (s_name, addres, description) values ('Sand Dune', '22 Carberry Trail', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, addres, description) values ('Suite 101', '45 Green Ridge Parkway', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, addres, description) values ('Trail', '0 Reindahl Park', 'Duis mattis egestas metus.');
insert into STATION (s_name, addres, description) values ('Starting Block', '303 Londonderry Pass', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, addres, description) values ('Coffee Roastery', '415 Dawn Pass', 'Sed ante.');
insert into STATION (s_name, addres, description) values ('Attic', '4 Debs Lane', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, addres, description) values ('Toy Store Window', '52624 North Trail', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into STATION (s_name, addres, description) values ('Craft Workshop', '2 Arkansas Terrace', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, addres, description) values ('Coast', '4 Moose Drive', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('Lane', '1 Grim Circle', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, addres, description) values ('Greenhouse Row', '0984 Mendota Drive', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Basin', '9 Westerfield Court', 'Donec posuere metus vitae ipsum.');
insert into STATION (s_name, addres, description) values ('Metro Entrance', '9 Schlimgen Crossing', 'In sagittis dui vel nisl.');
insert into STATION (s_name, addres, description) values ('Pine Forest', '798 Pierstorff Terrace', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Road', '577 Fordem Parkway', 'Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, addres, description) values ('Campus Green', '02 Melby Center', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, addres, description) values ('Wall', '3 Montana Hill', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Tech Hub', '3 Fremont Parkway', 'Morbi a ipsum.');
insert into STATION (s_name, addres, description) values ('West Wing', '5 Basil Alley', 'Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Moonlight Path', '51 Old Shore Point', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, addres, description) values ('Botanical Greenhouse', '74 Knutson Circle', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, addres, description) values ('Corner Tavern', '72237 2nd Way', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, addres, description) values ('Blacksmith Forge', '8 Springs Crossing', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into STATION (s_name, addres, description) values ('Coast', '803 Morningstar Parkway', 'In blandit ultrices enim.');
insert into STATION (s_name, addres, description) values ('Valley', '95350 Southridge Terrace', 'Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Secret Passage', '4 Towne Point', 'Nullam varius.');
insert into STATION (s_name, addres, description) values ('Spa Entrance', '8 Daystar Crossing', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, addres, description) values ('Vault Entry', '2563 Nelson Center', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, addres, description) values ('Hidden Garden', '57 Knutson Avenue', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, addres, description) values ('Overpass', '7 Walton Plaza', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, addres, description) values ('Cellar', '1 Spaight Court', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, addres, description) values ('Forest Clearing', '13 School Park', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Bistro Table', '781 Autumn Leaf Circle', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, addres, description) values ('Greenhouse Row', '360 Blackbird Pass', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, addres, description) values ('Meditation Hall', '2 Boyd Lane', 'Nam nulla.');
insert into STATION (s_name, addres, description) values ('Shady Nook', '1 Derek Parkway', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, addres, description) values ('Bank', '31 Gina Terrace', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, addres, description) values ('Coworking Courtyard', '1 Daystar Court', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, addres, description) values ('Cave Entrance', '38122 Elgar Parkway', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, addres, description) values ('Antique Shop Corner', '0881 Truax Circle', 'Sed ante. Vivamus tortor.');
insert into STATION (s_name, addres, description) values ('Crescent', '6924 Thackeray Drive', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, addres, description) values ('Cafe Patio', '75 Homewood Street', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, addres, description) values ('Modern Art Muse', '140 Sherman Circle', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, addres, description) values ('Potter’s Studio', '59214 Sunnyside Crossing', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, addres, description) values ('Podium', '749 Lien Place', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into STATION (s_name, addres, description) values ('Beach Cove', '51 Messerschmidt Point', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, addres, description) values ('Knight’s Table', '8 Ludington Park', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, addres, description) values ('Bakery Corner', '2906 Armistice Pass', 'Pellentesque at nulla.');
insert into STATION (s_name, addres, description) values ('Old City Gate', '5 Melody Junction', 'In blandit ultrices enim.');
insert into STATION (s_name, addres, description) values ('Wolf Path', '8 Scott Plaza', 'Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, addres, description) values ('Treasury Room', '07 Luster Drive', 'Mauris sit amet eros.');
insert into STATION (s_name, addres, description) values ('Reading Nook', '9 Menomonie Avenue', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, addres, description) values ('Orchard Gate', '1 Morningstar Pass', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Tailor’s Shop', '0 Cordelia Park', 'Nullam varius.');
insert into STATION (s_name, addres, description) values ('Balcony', '66 Dryden Junction', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, addres, description) values ('Squirrel Scramble', '9 Lindbergh Street', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Puppet Theater', '82941 Goodland Place', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, addres, description) values ('Larder', '6838 Comanche Pass', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, addres, description) values ('Woods', '4797 Kennedy Circle', 'Etiam justo. Etiam pretium iaculis justo.');
insert into STATION (s_name, addres, description) values ('Wilds.', '40 Crownhardt Drive', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, addres, description) values ('Main Entrance', '0 Northwestern Road', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into STATION (s_name, addres, description) values ('Pine Forest', '7237 Riverside Court', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, addres, description) values ('Orchard Gate', '666 Sheridan Crossing', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, addres, description) values ('Badger Set', '213 Anzinger Avenue', 'Aenean auctor gravida sem.');
insert into STATION (s_name, addres, description) values ('Victory Arch', '1323 Green Street', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, addres, description) values ('Passage', '8 Canary Parkway', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, addres, description) values ('Balcony', '3954 Helena Avenue', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, addres, description) values ('Ring Side', '7114 Evergreen Road', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, addres, description) values ('Cliffside Stairs', '4 Fulton Alley', 'Nulla tellus.');
insert into STATION (s_name, addres, description) values ('Harvest Barn', '9221 Lyons Circle', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, addres, description) values ('Safari Outpost', '4 Sundown Avenue', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, addres, description) values ('Fox Den', '581 Main Trail', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, addres, description) values ('Rooftop Bar', '3221 Longview Avenue', 'Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Coral Reef Point', '0 Garrison Plaza', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, addres, description) values ('Oasis Well', '08645 Redwing Terrace', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, addres, description) values ('Shell Beach', '70603 Upham Center', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, addres, description) values ('Arch', '39706 Declaration Avenue', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into STATION (s_name, addres, description) values ('Meadow View', '60146 Bashford Street', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Hummingbird Lane', '9433 Buell Street', 'Sed sagittis.');
insert into STATION (s_name, addres, description) values ('Coast', '85944 Cardinal Avenue', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, addres, description) values ('Control Room', '6 2nd Hill', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, addres, description) values ('South Port', '6489 Hoard Place', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, addres, description) values ('North Ridge', '158 Mcguire Pass', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, addres, description) values ('Main Entrance', '00 Tony Junction', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, addres, description) values ('Coffee Roastery', '91 Nevada Center', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, addres, description) values ('Yoga Studio', '1 Lindbergh Hill', 'Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('Safari Outpost', '2 Quincy Place', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, addres, description) values ('Rim', '1384 Bobwhite Plaza', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Knight’s Table', '91 Stuart Circle', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, addres, description) values ('Larder', '85 Northport Crossing', 'Pellentesque eget nunc.');
insert into STATION (s_name, addres, description) values ('Silent Corridor', '956 Chive Circle', 'Nulla ac enim.');
insert into STATION (s_name, addres, description) values ('Wolf Path', '32 Everett Place', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, addres, description) values ('Court Side', '48 Bay Avenue', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, addres, description) values ('Evening Balcony', '2766 Sauthoff Drive', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, addres, description) values ('Cliff', '1538 Forster Way', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, addres, description) values ('Basement Pub', '6096 Southridge Circle', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, addres, description) values ('Butterfly Bush', '52042 Debra Court', 'Duis at velit eu est congue elementum.');
insert into STATION (s_name, addres, description) values ('Rocky Ridge', '6 David Road', 'Ut tellus.');
insert into STATION (s_name, addres, description) values ('Way', '4 Maple Wood Place', 'Pellentesque ultrices mattis odio.');
insert into STATION (s_name, addres, description) values ('Desert Oasis', '85218 Dapin Place', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, addres, description) values ('Outlaw Hideout', '73 Oakridge Drive', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, addres, description) values ('Harbor Viewpoint', '6584 Hollow Ridge Pass', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, addres, description) values ('Lily Pad', '7328 Ramsey Plaza', 'Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('Botanical Garden Pond', '009 Warbler Place', 'Donec posuere metus vitae ipsum.');
insert into STATION (s_name, addres, description) values ('Marker', '51968 Barby Parkway', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, addres, description) values ('Forest', '283 Hovde Pass', 'In congue. Etiam justo.');
insert into STATION (s_name, addres, description) values ('Trophy Hall', '8 Fieldstone Street', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, addres, description) values ('Rail Station Plaza', '606 8th Plaza', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, addres, description) values ('Library Stacks', '1031 Eggendart Drive', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, addres, description) values ('Jewelry Row', '40 Hazelcrest Alley', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into STATION (s_name, addres, description) values ('Meadow View', '82 Sutteridge Road', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, addres, description) values ('Cafe Patio', '20 Thackeray Terrace', 'Integer non velit.');
insert into STATION (s_name, addres, description) values ('Hidden Door', '3924 Ruskin Avenue', 'Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('Neon Street', '6358 Pine View Lane', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('East Gate', '805 Kipling Center', 'Morbi non lectus.');
insert into STATION (s_name, addres, description) values ('Trail', '2 Eastwood Junction', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, addres, description) values ('Circle', '14 Lawn Point', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, addres, description) values ('Waterfront Promenade', '4 Mallory Road', 'Integer ac neque. Duis bibendum.');
insert into STATION (s_name, addres, description) values ('Nature Boardwalk', '4 Crowley Drive', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, addres, description) values ('Twilight Pier', '65 Macpherson Drive', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, addres, description) values ('Eco-Trail Marker', '2 Meadow Valley Trail', 'Phasellus sit amet erat.');
insert into STATION (s_name, addres, description) values ('Rail Station Plaza', '029 American Drive', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, addres, description) values ('Suite Entrance', '3420 Texas Avenue', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, addres, description) values ('Botanical Greenhouse', '9474 Columbus Plaza', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, addres, description) values ('Morning Terrace', '36362 Continental Terrace', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, addres, description) values ('Weaver’s Loom', '2 Cardinal Street', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, addres, description) values ('Victory Arch', '81994 Dayton Hill', 'Sed ante. Vivamus tortor.');
insert into STATION (s_name, addres, description) values ('Botanical Greenhouse', '647 Bonner Street', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, addres, description) values ('Canal Bridge', '333 Cody Parkway', 'Aliquam erat volutpat.');
insert into STATION (s_name, addres, description) values ('Sand Dune', '3 Schiller Terrace', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, addres, description) values ('Suite Entrance', '0 Morrow Plaza', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, addres, description) values ('Reading Nook', '16 Evergreen Lane', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, addres, description) values ('Campus Green', '58 8th Terrace', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Panoramic Lookout', '714 Eggendart Alley', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('City Hall Plaza', '44 Springview Alley', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, addres, description) values ('Runway End', '39 Hansons Street', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, addres, description) values ('Harvest Barn', '5905 Columbus Circle', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, addres, description) values ('Industrial Loft', '779 Prairie Rose Way', 'Aliquam non mauris.');
insert into STATION (s_name, addres, description) values ('Twilight Pier', '4 Crownhardt Center', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, addres, description) values ('Track', '83 Lakewood Trail', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, addres, description) values ('Bank', '79843 Westend Street', 'Integer a nibh. In quis justo.');
insert into STATION (s_name, addres, description) values ('Highway', '5 Melby Park', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, addres, description) values ('Lily Pad', '70 Oxford Avenue', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into STATION (s_name, addres, description) values ('Beach Cove', '93440 Carpenter Terrace', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, addres, description) values ('Gourmet Food Hall', '5580 Fremont Drive', 'Integer ac neque.');
insert into STATION (s_name, addres, description) values ('Art Gallery Lane', '44221 Pine View Circle', 'Mauris sit amet eros.');
insert into STATION (s_name, addres, description) values ('Trade Post', '382 Fulton Terrace', 'Duis bibendum.');
insert into STATION (s_name, addres, description) values ('Path', '69 Goodland Hill', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, addres, description) values ('Larder', '70490 Macpherson Street', 'Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, addres, description) values ('Sign', '94525 Hayes Road', 'Morbi non lectus.');
insert into STATION (s_name, addres, description) values ('Twilight Pier', '96953 2nd Place', 'Aliquam erat volutpat.');
insert into STATION (s_name, addres, description) values ('Clockwork Square', '24 Ohio Avenue', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, addres, description) values ('Bus Terminal Hub', '751 Esker Point', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, addres, description) values ('Local Artisan Market', '909 Express Lane', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus.');
insert into STATION (s_name, addres, description) values ('Visitor Center', '870 Ruskin Plaza', 'Duis aliquam convallis nunc.');
insert into STATION (s_name, addres, description) values ('Bank', '23172 Emmet Road', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, addres, description) values ('Track', '0307 Sachtjen Road', 'Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, addres, description) values ('Historic Clock Tower', '114 Messerschmidt Junction', 'Quisque ut erat.');
insert into STATION (s_name, addres, description) values ('Rim', '42 Clarendon Parkway', 'Phasellus in felis.');
insert into STATION (s_name, addres, description) values ('Hedge', '96 Jenna Crossing', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, addres, description) values ('Pirate Cove', '6287 Warner Hill', 'Donec dapibus.');
insert into STATION (s_name, addres, description) values ('Terrace Grill', '929 Barnett Hill', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, addres, description) values ('Bakery Corner', '7242 Merrick Center', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, addres, description) values ('Shady Nook', '1497 Saint Paul Court', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, addres, description) values ('Bakery Corner', '33832 John Wall Parkway', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, addres, description) values ('Coral Reef Point', '982 Luster Pass', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, addres, description) values ('Wolf Path', '678 Dixon Pass', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, addres, description) values ('Riddle Wall', '4 School Center', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, addres, description) values ('Riverside Path', '4 Mcguire Place', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, addres, description) values ('Riverfront Pier', '33 Pine View Street', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, addres, description) values ('Jewelry Row', '90 Colorado Road', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, addres, description) values ('Willow Pond', '2899 Cascade Hill', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, addres, description) values ('Bridge', '557 Declaration Plaza', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, addres, description) values ('Square', '03187 Forest Dale Point', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, addres, description) values ('Stream Crossing', '82168 Killdeer Plaza', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, addres, description) values ('Beacon', '91039 Bobwhite Terrace', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, addres, description) values ('Fox Den', '0778 Aberg Parkway', 'Curabitur convallis.');
insert into STATION (s_name, addres, description) values ('Enigma Room', '39 Jay Plaza', 'Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Throne Room', '2 Scott Parkway', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, addres, description) values ('Brewery Courtyard', '8305 Carioca Court', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into STATION (s_name, addres, description) values ('Eagle Nest', '18 Dahle Plaza', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, addres, description) values ('Fence', '6 Northfield Avenue', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Oak Grove', '4069 Bunker Hill Park', 'Praesent lectus.');
insert into STATION (s_name, addres, description) values ('Canyon Rim', '63337 Michigan Park', 'Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, addres, description) values ('Frog Pond', '82722 Logan Alley', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, addres, description) values ('Glass Elevator', '79 Golf View Road', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, addres, description) values ('Chef’s Table', '84454 Green Ridge Court', 'Aliquam erat volutpat.');
insert into STATION (s_name, addres, description) values ('Trade Post', '75370 Sloan Point', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, addres, description) values ('West Wing', '67 Valley Edge Crossing', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, addres, description) values ('Castle Courtyard', '95 Golf Trail', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, addres, description) values ('Art Gallery Lane', '5 Basil Avenue', 'Integer non velit.');
insert into STATION (s_name, addres, description) values ('Pantry', '57 Nancy Parkway', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, addres, description) values ('Stream Crossing', '18 Raven Avenue', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, addres, description) values ('Foggy Bridge', '6 Bunker Hill Parkway', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, addres, description) values ('Beaver Dam', '87761 Hoard Trail', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, addres, description) values ('Column', '9584 Lotheville Avenue', 'Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, addres, description) values ('Riddle Wall', '87 Dahle Lane', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, addres, description) values ('Rocky Ridge', '75 Hanson Terrace', 'Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, addres, description) values ('Wildflower Field', '13 Pleasure Road', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, addres, description) values ('Lab Wing', '33 Meadow Valley Junction', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, addres, description) values ('Apple Tree', '51 Autumn Leaf Avenue', 'Nulla tempus.');
insert into STATION (s_name, addres, description) values ('Banner Row', '992 Myrtle Street', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, addres, description) values ('Rooftop Bar', '54 Service Point', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, addres, description) values ('Ring Side', '60966 Roth Circle', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, addres, description) values ('Armory', '8 Hoard Trail', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, addres, description) values ('Cliff', '56459 Carioca Way', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, addres, description) values ('Boulevard', '9560 Carpenter Street', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, addres, description) values ('Enigma Room', '9693 Fairfield Junction', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into STATION (s_name, addres, description) values ('Deck', '86 Knutson Way', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, addres, description) values ('Street', '106 Caliangt Court', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, addres, description) values ('Veranda', '7 Cottonwood Plaza', 'Nullam varius.');
insert into STATION (s_name, addres, description) values ('Tunnel', '366 Fallview Place', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, addres, description) values ('Path', '5139 Alpine Circle', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, addres, description) values ('Peak Summit', '77369 Katie Lane', 'Aenean sit amet justo.');
insert into STATION (s_name, addres, description) values ('Jungle Canopy', '51 Mandrake Pass', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, addres, description) values ('Oasis Well', '6 Fair Oaks Pass', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, addres, description) values ('Skyline Balcony', '19 Glacier Hill Park', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, addres, description) values ('West Wing', '0 Oriole Place', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, addres, description) values ('Rooftop Bar', '356 Bowman Court', 'Nulla nisl.');
insert into STATION (s_name, addres, description) values ('Smuggler’s Tunnel', '1 Valley Edge Point', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into STATION (s_name, addres, description) values ('University Quad', '8 Graedel Place', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, addres, description) values ('Metro Entrance', '88 Lerdahl Terrace', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
