insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Moonlight Meadow', 25, 175, 'Sightseeing', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Maker’s Mile', 23, 120, 'Hiking', 'Provence', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Exclusive Echoes', 46, 52, 'Sightseeing', 'Paris Montmartre', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bouldering Best', 43, 114, 'Hiking', 'Hong Kong Island', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Funky Frontier', 17, 131, 'Sightseeing', 'Reykjavik', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pavement Perspectives', 35, 250, 'Hiking', 'Istanbul Sultanahmet', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Palette Path', 41, 117, 'Sightseeing', 'Vienna City Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Downtown Discovery', 29, 68, 'Sightseeing', 'Cairo Giza', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Taste Buds Tour', 30, 243, 'Hiking', 'Amalfi Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Quirky Quarters', 39, 73, 'Sightseeing', 'Sydney Harbour', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Century Circuit', 37, 168, 'Sightseeing', 'Cairo Giza', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Handcrafted Highlights', 10, 226, 'Hiking', 'Istanbul Sultanahmet', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Shadow Sojourn', 47, 214, 'Hiking', 'New Orleans', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Yacht Yard', 28, 181, 'Sightseeing', 'Swiss Alps', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Chef’s Choice', 11, 200, 'Hiking', 'Hong Kong Island', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Peak Performance', 14, 6, 'Hiking', 'Machu Picchu', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Safari Solitude', 25, 216, 'Hiking', 'Barcelona Gothic Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Easy Breezy', 38, 224, 'Hiking', 'London South Bank', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Library Lore', 48, 30, 'Sightseeing', 'Machu Picchu', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Desert Dreams', 50, 161, 'Hiking', 'Edinburgh Royal Mile', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sweet Street', 30, 30, 'Sightseeing', 'Scottish Highlands', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Castle Conquest', 20, 166, 'Sightseeing', 'Seoul City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pattern Path', 39, 116, 'Hiking', 'Jerusalem Old City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Toy Town Tour', 49, 67, 'Sightseeing', 'Santorini', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cultural Crossroads', 33, 112, 'Sightseeing', 'Athens Acropolis', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Steampunk Steps', 15, 249, 'Hiking', 'French Quarter', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cheese Circuit', 39, 91, 'Hiking', 'Edinburgh Royal Mile', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Spirits of the Past', 26, 82, 'Sightseeing', 'Old Town Prague', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Industrial Icons', 50, 76, 'Sightseeing', 'Edinburgh Royal Mile', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Colonial Chronicles', 40, 8, 'Hiking', 'Istanbul Sultanahmet', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Great Outdoors', 50, 218, 'Hiking', 'French Quarter', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pastry Path', 36, 37, 'Hiking', 'Old Town Prague', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gothic Ghost Walk', 45, 20, 'Hiking', 'Istanbul Sultanahmet', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nightfall Nuances', 15, 16, 'Hiking', 'Machu Picchu', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Shadow Steps', 43, 3, 'Hiking', 'Santorini', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Kite Krusade', 33, 7, 'Hiking', 'Barcelona Las Ramblas', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bloom & Blossom', 24, 8, 'Sightseeing', 'Petra', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Harvest Highlights', 39, 180, 'Sightseeing', 'Reykjavik', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Trailblazer Tracks', 37, 123, 'Hiking', 'Rome City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Handcrafted Highlights', 11, 75, 'Hiking', 'Prague Castle District', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Baroque Beauty', 44, 173, 'Hiking', 'Lisbon Hills', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nautical Night', 26, 213, 'Hiking', 'Florence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sweet Shop Sojourn', 27, 22, 'Hiking', 'Tokyo Shibuya', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Artistic Avenues', 21, 124, 'Sightseeing', 'Scottish Highlands', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Riddle Routes', 30, 39, 'Sightseeing', 'Cairo Giza', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Urban Oasis Hunt', 30, 105, 'Sightseeing', 'Petra', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sandy Shores', 26, 155, 'Sightseeing', 'Central Park', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Hidden Gems', 30, 46, 'Hiking', 'Santorini', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Future Frontiers', 26, 188, 'Hiking', 'Paris Montmartre', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Harvest Highlights', 20, 34, 'Sightseeing', 'Hong Kong Island', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Wonderland Walk', 37, 63, 'Sightseeing', 'Patagonia', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Exclusive Echoes', 15, 170, 'Hiking', 'Munich Old Town', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Yacht Yard', 38, 159, 'Sightseeing', 'Patagonia', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Marshland Magic', 33, 109, 'Hiking', 'Cairo Giza', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Toy Town Tour', 15, 169, 'Sightseeing', 'Yosemite Valley', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Oasis Observations', 44, 64, 'Hiking', 'Yosemite Valley', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Stream Side Saunter', 47, 178, 'Sightseeing', 'Amsterdam Canals', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Magic Mile', 18, 151, 'Hiking', 'Machu Picchu', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Spa Serenity', 13, 112, 'Sightseeing', 'Seoul City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Monumental Moments', 19, 46, 'Sightseeing', 'Tokyo Shibuya', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Treasure Trove', 37, 167, 'Sightseeing', 'Yellowstone Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Hidden Gems', 11, 179, 'Sightseeing', 'Paris Montmartre', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ski Slope Safari', 39, 213, 'Sightseeing', 'Jerusalem Old City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Hotel Highlights', 10, 15, 'Sightseeing', 'Vancouver Waterfront', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flea Market Follow', 49, 113, 'Hiking', 'Dublin City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Victory Voyage', 39, 16, 'Sightseeing', 'Hong Kong Island', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Stream Side Saunter', 30, 214, 'Sightseeing', 'Athens Acropolis', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Chilling Chronicles', 30, 22, 'Hiking', 'Santorini', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tech Trek', 34, 217, 'Sightseeing', 'Machu Picchu', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Brunch Bunch', 18, 197, 'Hiking', 'Manhattan', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flora & Fauna', 45, 69, 'Sightseeing', 'Santorini', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Aerial Adventures', 24, 127, 'Sightseeing', 'Lisbon Hills', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Time Traveler’s Trek', 11, 127, 'Hiking', 'Jerusalem Old City', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Inspiration Island', 36, 113, 'Sightseeing', 'Tel Aviv Coastline', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Haunted Highlights', 13, 123, 'Hiking', 'Athens Acropolis', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Green Getaway', 21, 47, 'Sightseeing', 'Provence', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Puzzling Path', 39, 109, 'Hiking', 'Paris Montmartre', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cryptic Circuit', 29, 107, 'Hiking', 'Barcelona Las Ramblas', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Eerie Echoes', 37, 82, 'Sightseeing', 'Dublin Liberties', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Geometry Gaze', 36, 65, 'Sightseeing', 'Athens Acropolis', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Main Street Memories', 20, 244, 'Hiking', 'Jerusalem Old City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bizarre Boulevard', 44, 88, 'Sightseeing', 'Seoul City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Twilight Trails', 23, 98, 'Hiking', 'Sydney Harbour', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Classic Culture', 22, 180, 'Hiking', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Retail Revelations', 46, 198, 'Hiking', 'Venice Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Savory Steps', 21, 229, 'Hiking', 'New Orleans', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Brunch Bunch', 37, 37, 'Sightseeing', 'Scottish Highlands', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Classic Culture', 13, 181, 'Sightseeing', 'New Orleans', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nerd Night', 48, 223, 'Sightseeing', 'Reykjavik', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Midnight Murmurs', 36, 147, 'Hiking', 'Central Park', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Diamond District', 48, 142, 'Sightseeing', 'Athens Acropolis', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Wizard’s Walk', 23, 35, 'Hiking', 'Berlin Mitte', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Empire Eras', 33, 180, 'Sightseeing', 'Old Town Prague', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Wild Wanderer', 30, 176, 'Sightseeing', 'Provence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pub Crawl Classics', 38, 218, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Magic Mile', 39, 169, 'Sightseeing', 'Tel Aviv Coastline', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Avenue Adventures', 17, 162, 'Sightseeing', 'London South Bank', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Peak Performance', 15, 153, 'Hiking', 'Florence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mythic Moments', 48, 12, 'Sightseeing', 'Jerusalem Old City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Botanical Best', 40, 52, 'Hiking', 'Dublin Liberties', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Picnic Parade', 50, 198, 'Hiking', 'Bali Jungles', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Robot Routes', 19, 36, 'Hiking', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Literary Legend', 49, 95, 'Hiking', 'Athens Acropolis', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Detective District', 36, 127, 'Hiking', 'Barcelona Gothic Quarter', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Waterfall Wonders', 39, 201, 'Sightseeing', 'Tokyo Shibuya', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Tradition Trail', 15, 78, 'Hiking', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sacred Sites', 19, 226, 'Hiking', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nautical Night', 13, 184, 'Sightseeing', 'New Orleans', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Strange Steps', 29, 193, 'Hiking', 'Reykjavik', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Aerial Adventures', 13, 135, 'Hiking', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('War & Peace Walk', 31, 145, 'Hiking', 'Yellowstone Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ruins & Relics', 49, 79, 'Sightseeing', 'Tel Aviv Coastline', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mindful Movements', 17, 29, 'Sightseeing', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rare Routes', 12, 82, 'Hiking', 'Florence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Leisurely Loop', 49, 89, 'Hiking', 'Istanbul Sultanahmet', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Paddle Path', 49, 96, 'Sightseeing', 'Vancouver Waterfront', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Prehistoric Path', 17, 98, 'Sightseeing', 'Provence', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Orchard Outing', 37, 249, 'Sightseeing', 'Istanbul Sultanahmet', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Savory Steps', 29, 134, 'Hiking', 'Munich Old Town', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Antique Arc', 42, 213, 'Hiking', 'Paris Montmartre', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Quirky Quarters', 30, 132, 'Sightseeing', 'Tokyo Shibuya', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Studio Steps', 12, 167, 'Hiking', 'Machu Picchu', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('BBQ Belt', 28, 11, 'Hiking', 'Sydney Harbour', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Aquarium Arc', 26, 86, 'Hiking', 'Reykjavik', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fairground Finds', 12, 111, 'Hiking', 'Patagonia', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Town Square Tales', 19, 166, 'Hiking', 'Amsterdam Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Landmark Loop', 20, 151, 'Sightseeing', 'Amsterdam Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Coastal Cliffs', 27, 237, 'Hiking', 'Florence', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Glamour Gaze', 34, 2, 'Sightseeing', 'Athens Acropolis', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Entertainment District', 25, 101, 'Hiking', 'Kyoto Temples', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Record Road', 31, 4, 'Sightseeing', 'New Orleans', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sporty Spectacle', 34, 120, 'Hiking', 'Jerusalem Old City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gold Mine Gaze', 14, 77, 'Hiking', 'San Francisco Bay', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Collector’s Choice', 44, 160, 'Sightseeing', 'Yellowstone Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Kitsch Kingdom', 21, 47, 'Hiking', 'Munich Old Town', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Exclusive Echoes', 34, 124, 'Sightseeing', 'Scottish Highlands', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cemetery Secrets', 50, 184, 'Hiking', 'Hong Kong Island', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pottery Path', 29, 76, 'Sightseeing', 'Old Town Prague', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Morning Morsels', 34, 59, 'Hiking', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Puzzling Path', 14, 216, 'Hiking', 'Petra', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Vintage Vibes', 15, 109, 'Hiking', 'Dublin Liberties', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ancient Artifacts', 35, 196, 'Hiking', 'London South Bank', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Garden Glimpse', 18, 1, 'Hiking', 'Scottish Highlands', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rolling Routes', 20, 160, 'Hiking', 'Vienna City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Acoustic Adventures', 31, 202, 'Sightseeing', 'Tokyo Shibuya', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Trailblazer Tracks', 18, 244, 'Sightseeing', 'Florence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Vogue Voyage', 15, 169, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sky-High Views', 41, 197, 'Hiking', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rolling Routes', 20, 192, 'Hiking', 'Seoul City', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Snorkel Steps', 10, 116, 'Sightseeing', 'Yosemite Valley', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('High Society Sojourn', 40, 103, 'Sightseeing', 'Tokyo Shibuya', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sustainable Steps', 25, 166, 'Sightseeing', 'Singapore Marina', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Golden Glimpse', 48, 245, 'Hiking', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('History Unveiled', 30, 86, 'Hiking', 'Edinburgh Royal Mile', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Acoustic Adventures', 46, 65, 'Hiking', 'Machu Picchu', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Elegant Escapes', 43, 217, 'Sightseeing', 'Central Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Coastal Currents', 36, 172, 'Sightseeing', 'Scottish Highlands', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sky-High Views', 35, 110, 'Sightseeing', 'Dubai Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pastry Path', 27, 54, 'Sightseeing', 'Rome City Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bouldering Best', 22, 80, 'Hiking', 'Reykjavik', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Glamour Gaze', 39, 100, 'Sightseeing', 'Madrid Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bandit Best', 38, 128, 'Sightseeing', 'Dubai Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nerd Night', 11, 221, 'Sightseeing', 'Manhattan', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Baroque Beauty', 39, 244, 'Hiking', 'Central Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ocean Odysseys', 13, 215, 'Sightseeing', 'Munich Old Town', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Illusion Island', 47, 2, 'Hiking', 'Singapore Marina', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rainforest Rhythms', 14, 33, 'Hiking', 'Machu Picchu', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Startup Safari', 15, 173, 'Hiking', 'Cairo Giza', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Serene Sojourn', 19, 144, 'Sightseeing', 'Swiss Alps', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mirror Magic', 39, 181, 'Sightseeing', 'Dubai Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Forest Frontiers', 28, 28, 'Hiking', 'Tokyo Shibuya', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Balloon Best', 12, 153, 'Sightseeing', 'Grand Canyon', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Traditional Tastes', 12, 230, 'Sightseeing', 'Yellowstone Park', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tech Trek', 24, 25, 'Hiking', 'Amalfi Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Patriot Path', 18, 66, 'Sightseeing', 'Prague Castle District', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Skyline Shadows', 25, 183, 'Sightseeing', 'Dubai Marina', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Theater Thrills', 20, 189, 'Hiking', 'Jerusalem Old City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Zip-Line Zeal', 33, 184, 'Sightseeing', 'Sydney Harbour', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Wellness Walk', 25, 5, 'Hiking', 'Edinburgh Royal Mile', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Noir Night', 44, 108, 'Hiking', 'Barcelona Gothic Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Champion’s Choice', 28, 24, 'Hiking', 'Manhattan', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Kitsch Kingdom', 21, 63, 'Hiking', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ancestral Avenues', 39, 22, 'Sightseeing', 'Machu Picchu', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Jazz Jaunt', 41, 133, 'Hiking', 'Berlin Mitte', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Underwater Universe', 18, 42, 'Sightseeing', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Balloon Boulevard', 11, 249, 'Hiking', 'London South Bank', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Maker’s Mile', 40, 41, 'Sightseeing', 'Istanbul Sultanahmet', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nightcap Nibbles', 44, 145, 'Hiking', 'Amalfi Coast', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mythic Moments', 32, 47, 'Sightseeing', 'Barcelona Las Ramblas', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Maze Magic', 38, 107, 'Sightseeing', 'Patagonia', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Concrete Jungle', 45, 12, 'Sightseeing', 'Central Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Twilight Trails', 18, 219, 'Hiking', 'Athens Acropolis', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Backcountry Bliss', 10, 40, 'Sightseeing', 'Athens Acropolis', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gothic Glories', 39, 210, 'Sightseeing', 'Istanbul Sultanahmet', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gallery Glow', 35, 153, 'Hiking', 'Vienna City Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Financial Frontier', 22, 68, 'Hiking', 'Lisbon Hills', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Zip-Line Zeal', 21, 2, 'Hiking', 'Machu Picchu', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Moonlight Meadow', 31, 60, 'Sightseeing', 'Cairo Giza', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Balloon Boulevard', 11, 199, 'Sightseeing', 'Edinburgh Royal Mile', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The High-Rise Hike', 14, 184, 'Sightseeing', 'Florence', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The High-Rise Hike', 23, 109, 'Hiking', 'Seoul City', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Weird & Wonderful', 16, 221, 'Sightseeing', 'Athens Acropolis', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pottery Path', 11, 131, 'Hiking', 'Barcelona Las Ramblas', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Berry Best', 27, 77, 'Hiking', 'Patagonia', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Theme Park Thrills', 31, 134, 'Hiking', 'New Orleans', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Artisan Appetizers', 13, 162, 'Hiking', 'New Orleans', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cryptic Circuit', 50, 113, 'Hiking', 'Central Park', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Studio Steps', 27, 26, 'Hiking', 'Vienna City Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Legacy Path', 27, 94, 'Hiking', 'New Orleans', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cemetery Secrets', 25, 169, 'Sightseeing', 'Barcelona Las Ramblas', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Coastal Cliffs', 37, 83, 'Hiking', 'Scottish Highlands', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Capital Chronicles', 38, 27, 'Sightseeing', 'Grand Canyon', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Echo Exploration', 33, 159, 'Sightseeing', 'Old Town Prague', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Retail Revelations', 29, 90, 'Sightseeing', 'Madrid Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Market Munchies', 42, 185, 'Sightseeing', 'Petra', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Estate Explorations', 24, 243, 'Hiking', 'Swiss Alps', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Creative Currents', 42, 16, 'Hiking', 'Dublin City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Orchard Outing', 27, 60, 'Sightseeing', 'Rome City Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Weird & Wonderful', 23, 26, 'Hiking', 'Yosemite Valley', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Spirits of the Past', 32, 196, 'Sightseeing', 'Barcelona Las Ramblas', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tea Time Trails', 23, 82, 'Hiking', 'Provence', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Taste Buds Tour', 40, 24, 'Hiking', 'French Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Backstage Bliss', 25, 165, 'Sightseeing', 'Hong Kong Island', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Grand Boulevard', 45, 1, 'Hiking', 'Yellowstone Park', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Posh Path', 34, 112, 'Hiking', 'Machu Picchu', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Champion’s Choice', 46, 219, 'Sightseeing', 'Grand Canyon', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Luxury Lane', 29, 28, 'Sightseeing', 'Kyoto Temples', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Main Street Memories', 45, 7, 'Sightseeing', 'Yosemite Valley', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rare Routes', 44, 199, 'Hiking', 'Seoul City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Medieval Mysteries', 35, 71, 'Hiking', 'New Orleans', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Evening Elegance', 34, 6, 'Sightseeing', 'Prague Castle District', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Goal Line Gaze', 39, 4, 'Sightseeing', 'Reykjavik', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sorcerer’s Sojourn', 11, 189, 'Hiking', 'Florence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bike & Brew', 44, 148, 'Sightseeing', 'Cape Town Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rainforest Rhythms', 19, 188, 'Sightseeing', 'Patagonia', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Snapshot Safari', 50, 220, 'Hiking', 'Barcelona Gothic Quarter', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Strange Steps', 41, 221, 'Sightseeing', 'Cape Town Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Civic Center', 29, 87, 'Sightseeing', 'Amalfi Coast', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tea Time Trails', 17, 147, 'Hiking', 'Yosemite Valley', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Vogue Voyage', 48, 162, 'Hiking', 'Santorini', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tombstone Tales', 19, 164, 'Sightseeing', 'Berlin Mitte', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Backcountry Bliss', 33, 230, 'Sightseeing', 'Manhattan', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Dockside Dreams', 47, 37, 'Hiking', 'Rome City Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pattern Path', 40, 147, 'Hiking', 'Petra', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flea Market Follow', 50, 94, 'Sightseeing', 'Madrid Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Concrete Jungle', 22, 2, 'Hiking', 'Grand Canyon', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sculpture Safari', 39, 144, 'Sightseeing', 'Dublin Liberties', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Supernatural Saunter', 16, 245, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Surf & Sand', 36, 48, 'Hiking', 'Prague Castle District', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fortress Finds', 22, 135, 'Hiking', 'Yellowstone Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Picnic Parade', 28, 131, 'Hiking', 'Edinburgh Royal Mile', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Epicurean Escape', 40, 118, 'Sightseeing', 'Grand Canyon', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cinema Circuit', 47, 58, 'Sightseeing', 'Seoul City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Shadow Sojourn', 16, 244, 'Hiking', 'Munich Old Town', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tea Time Trails', 50, 152, 'Sightseeing', 'Singapore Marina', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Orchard Outing', 40, 135, 'Hiking', 'Vienna City Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Castle Conquest', 36, 82, 'Sightseeing', 'Manhattan', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Knight’s Quest', 27, 217, 'Hiking', 'Prague Castle District', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Texture Trails', 16, 49, 'Sightseeing', 'Amalfi Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Hidden History', 19, 212, 'Hiking', 'Athens Acropolis', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Taste Buds Tour', 39, 54, 'Hiking', 'Swiss Alps', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Moonlit Mysteries', 36, 227, 'Sightseeing', 'Madrid Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Skydiving Sojourn', 43, 96, 'Sightseeing', 'Machu Picchu', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Town Square Tales', 39, 199, 'Hiking', 'Dublin City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Limousine Lore', 46, 196, 'Hiking', 'Jerusalem Old City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Picnic Parade', 22, 83, 'Sightseeing', 'London South Bank', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sandy Shores', 32, 38, 'Sightseeing', 'New Orleans', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pizza Path', 22, 122, 'Hiking', 'Old Town Prague', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Alleyway Aesthetics', 32, 38, 'Sightseeing', 'Amsterdam Canals', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Science Secrets', 49, 31, 'Hiking', 'Kyoto Temples', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Enigma Escape', 28, 52, 'Sightseeing', 'French Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nightcap Nibbles', 50, 200, 'Sightseeing', 'Scottish Highlands', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bike & Brew', 46, 80, 'Hiking', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Street Art Safari', 38, 233, 'Sightseeing', 'Amsterdam Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Planetarium Path', 31, 4, 'Hiking', 'Paris Montmartre', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pastry Path', 20, 16, 'Hiking', 'Patagonia', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Crafty Circuit', 49, 191, 'Hiking', 'Dubai Marina', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tranquility Trail', 21, 103, 'Sightseeing', 'London South Bank', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Island Intervals', 33, 226, 'Sightseeing', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Harbor Highlights', 41, 220, 'Sightseeing', 'Bali Jungles', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sculpture Safari', 50, 94, 'Sightseeing', 'Edinburgh Royal Mile', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Abstract Adventures', 11, 82, 'Sightseeing', 'Old Town Prague', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Runway Routes', 27, 210, 'Hiking', 'Petra', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mystical Muse', 21, 19, 'Sightseeing', 'Cape Town Coast', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('War & Peace Walk', 21, 21, 'Hiking', 'Cape Town Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Funky Frontier', 23, 13, 'Hiking', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Forest Frontiers', 42, 56, 'Hiking', 'Paris Montmartre', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Reflection Routes', 49, 63, 'Sightseeing', 'Amalfi Coast', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Entertainment District', 49, 117, 'Sightseeing', 'Santorini', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Shadow Sojourn', 16, 30, 'Hiking', 'Munich Old Town', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Oracle Outing', 11, 175, 'Sightseeing', 'Reykjavik', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Coffee Culture', 34, 104, 'Hiking', 'Munich Old Town', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fan Frontier', 42, 183, 'Hiking', 'Vienna City Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Landscape Lore', 17, 4, 'Sightseeing', 'Patagonia', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Manor Muse', 29, 176, 'Hiking', 'Grand Canyon', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fashion Forward', 16, 13, 'Sightseeing', 'Paris Montmartre', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Offbeat Outing', 22, 97, 'Hiking', 'Patagonia', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ghostly Gaze', 19, 214, 'Hiking', 'Vienna City Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cemetery Secrets', 26, 152, 'Hiking', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Alchemist’s Arc', 11, 24, 'Sightseeing', 'Yellowstone Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Active Adventures', 50, 29, 'Hiking', 'Bali Jungles', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Private Paradise', 25, 217, 'Sightseeing', 'Seoul City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cinema Circuit', 47, 102, 'Hiking', 'Singapore Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('High Society Sojourn', 17, 3, 'Hiking', 'Santorini', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Island Intervals', 43, 68, 'Sightseeing', 'Lisbon Hills', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Garden Glimpse', 44, 51, 'Hiking', 'San Francisco Bay', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bridge & Tunnel', 15, 129, 'Sightseeing', 'Central Park', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Game On Garden', 17, 221, 'Hiking', 'Tel Aviv Coastline', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Eccentric Escapes', 11, 107, 'Hiking', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tapas Trek', 49, 85, 'Hiking', 'Prague Castle District', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Coastal Currents', 39, 149, 'Sightseeing', 'Dublin City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Toy Box Trek', 46, 205, 'Sightseeing', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sweet Street', 44, 220, 'Hiking', 'French Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mansion Magic', 23, 72, 'Sightseeing', 'Petra', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pastry Path', 17, 120, 'Sightseeing', 'New Orleans', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tombstone Tales', 33, 78, 'Sightseeing', 'Venice Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Puzzling Path', 25, 207, 'Hiking', 'Manhattan', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Baroque Beauty', 42, 172, 'Sightseeing', 'Swiss Alps', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flora & Fauna', 36, 113, 'Hiking', 'Venice Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Entertainment District', 46, 86, 'Sightseeing', 'Central Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Riddle Routes', 49, 17, 'Hiking', 'Barcelona Gothic Quarter', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Civic Center', 30, 248, 'Sightseeing', 'Dubai Marina', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Seafood Sojourn', 34, 143, 'Hiking', 'Petra', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Concrete Jungle', 28, 215, 'Hiking', 'Yosemite Valley', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Hidden Gems', 27, 108, 'Hiking', 'Cape Town Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Reef Revelations', 11, 14, 'Sightseeing', 'Madrid Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Legacy Path', 36, 62, 'Sightseeing', 'London South Bank', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Twilight Toast', 47, 177, 'Sightseeing', 'Tokyo Shibuya', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Portrait Parade', 41, 215, 'Sightseeing', 'Florence', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Artistic Avenues', 25, 207, 'Hiking', 'Athens Acropolis', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Liberty Lane', 11, 210, 'Hiking', 'Vienna City Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Writer’s Walk', 19, 70, 'Hiking', 'Vancouver Waterfront', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ruins & Relics', 32, 199, 'Hiking', 'Amalfi Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gastronomy Guide', 16, 141, 'Sightseeing', 'Singapore Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pizza Path', 20, 213, 'Hiking', 'Madrid Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tech Trek', 40, 199, 'Sightseeing', 'Paris Montmartre', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bookworm Boulevard', 33, 147, 'Hiking', 'Amsterdam Canals', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fashion Forward', 17, 205, 'Hiking', 'Reykjavik', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Twilight Toast', 16, 223, 'Sightseeing', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fantasy Frontier', 41, 214, 'Hiking', 'Madrid Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mystery Mile', 25, 105, 'Hiking', 'Tokyo Shibuya', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Zoo Zone', 22, 54, 'Sightseeing', 'Yellowstone Park', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('City Pulse Walk', 21, 89, 'Hiking', 'Patagonia', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Writer’s Walk', 43, 211, 'Hiking', 'Machu Picchu', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nerd Night', 48, 209, 'Sightseeing', 'Yellowstone Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Aerial Adventures', 46, 14, 'Sightseeing', 'San Francisco Bay', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Dark District', 37, 210, 'Hiking', 'Dublin City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Puzzling Path', 15, 49, 'Sightseeing', 'Bali Jungles', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Transit Triumphs', 34, 164, 'Hiking', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Champion’s Choice', 40, 152, 'Sightseeing', 'Paris Montmartre', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gallery Glow', 27, 214, 'Hiking', 'Edinburgh Royal Mile', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rainforest Rhythms', 24, 51, 'Sightseeing', 'Edinburgh Royal Mile', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Retreat Routes', 44, 34, 'Hiking', 'London South Bank', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flavor Fusion', 28, 174, 'Hiking', 'Kyoto Temples', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Masterpiece Muse', 32, 197, 'Hiking', 'Vienna City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Aquarium Arc', 20, 171, 'Hiking', 'Kyoto Temples', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Visionary Views', 27, 236, 'Sightseeing', 'Venice Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tranquility Trail', 28, 221, 'Hiking', 'Kyoto Temples', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flavor Fusion', 48, 187, 'Sightseeing', 'Yosemite Valley', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Kitchen Kingdom', 36, 209, 'Sightseeing', 'Amalfi Coast', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Happy Hour Hunt', 37, 7, 'Sightseeing', 'Munich Old Town', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Flea Market Follow', 20, 165, 'Sightseeing', 'Barcelona Las Ramblas', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Local Larder', 18, 75, 'Sightseeing', 'Edinburgh Royal Mile', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Kayak Quest', 11, 173, 'Hiking', 'Grand Canyon', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Wildlife Watch', 46, 241, 'Hiking', 'Florence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mindful Movements', 27, 4, 'Sightseeing', 'Paris Montmartre', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Epicurean Escape', 17, 107, 'Sightseeing', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Financial Frontier', 46, 102, 'Sightseeing', 'Dubai Marina', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Calm Currents', 36, 238, 'Sightseeing', 'Grand Canyon', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Medieval Mysteries', 28, 238, 'Hiking', 'San Francisco Bay', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Literary Legend', 21, 50, 'Sightseeing', 'Cape Town Coast', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Jungle Jaunt', 32, 7, 'Sightseeing', 'Vienna City Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Past Perfect', 50, 188, 'Hiking', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Palace Perspectives', 37, 219, 'Sightseeing', 'Petra', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ancestral Avenues', 30, 244, 'Hiking', 'Swiss Alps', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Zoo Zone', 12, 160, 'Hiking', 'Berlin Mitte', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Smuggler’s Secret', 20, 167, 'Hiking', 'Singapore Marina', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Quirky Quarters', 46, 191, 'Sightseeing', 'Edinburgh Royal Mile', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('High-Wire Hike', 35, 15, 'Hiking', 'New Orleans', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Downtown Discovery', 26, 24, 'Hiking', 'Seoul City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tarot Trails', 19, 71, 'Sightseeing', 'Machu Picchu', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bridge & Tunnel', 31, 109, 'Sightseeing', 'Cape Town Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Curious Circuit', 30, 201, 'Hiking', 'Patagonia', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Stadium Stars', 15, 217, 'Sightseeing', 'Swiss Alps', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mystery Mile', 37, 222, 'Sightseeing', 'Cairo Giza', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bridge & Tunnel', 42, 165, 'Sightseeing', 'Dublin Liberties', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Calm Currents', 31, 111, 'Sightseeing', 'Patagonia', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pattern Path', 48, 1, 'Sightseeing', 'Singapore Marina', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Elegant Escapes', 18, 86, 'Hiking', 'Petra', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sorcerer’s Sojourn', 10, 190, 'Hiking', 'San Francisco Bay', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Resort Revelations', 10, 4, 'Sightseeing', 'Old Town Prague', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Peak Performance', 20, 246, 'Sightseeing', 'Athens Acropolis', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Time Traveler’s Trek', 12, 40, 'Sightseeing', 'French Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ruins & Relics', 24, 171, 'Sightseeing', 'Central Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Vinyl Voyage', 43, 1, 'Sightseeing', 'Munich Old Town', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tarot Trails', 25, 117, 'Hiking', 'Swiss Alps', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Operatic Odyssey', 36, 78, 'Sightseeing', 'Petra', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Style Saunter', 35, 151, 'Sightseeing', 'Dublin City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Arctic Adventures', 49, 116, 'Hiking', 'Lisbon Hills', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Snapshot Safari', 33, 233, 'Sightseeing', 'Central Park', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sprint Steps', 33, 196, 'Sightseeing', 'Bali Jungles', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Playful Path', 10, 168, 'Hiking', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Reef Revelations', 33, 117, 'Hiking', 'San Francisco Bay', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Soundscape Safari', 31, 175, 'Hiking', 'Lisbon Hills', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cursed Corners', 40, 181, 'Hiking', 'Barcelona Gothic Quarter', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Innovation Island', 46, 4, 'Hiking', 'Venice Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mythic Moments', 34, 216, 'Sightseeing', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Bookworm Boulevard', 34, 22, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Renaissance Revelations', 36, 242, 'Hiking', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Math Magic', 40, 20, 'Sightseeing', 'Manhattan', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sandy Shores', 29, 68, 'Hiking', 'Cairo Giza', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Street Food Safari', 42, 38, 'Sightseeing', 'Kyoto Temples', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Harbor Highlights', 49, 224, 'Sightseeing', 'Cape Town Coast', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Playground Parade', 45, 111, 'Sightseeing', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Portrait Parade', 17, 250, 'Sightseeing', 'Munich Old Town', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Peculiar Path', 21, 129, 'Sightseeing', 'Florence', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fashion Frontier', 35, 74, 'Sightseeing', 'Berlin Mitte', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Main Street Memories', 40, 21, 'Sightseeing', 'Vienna City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cathedral Corners', 46, 119, 'Sightseeing', 'Grand Canyon', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Modern Muse', 46, 132, 'Hiking', 'Singapore Marina', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Future Frontiers', 10, 84, 'Hiking', 'Manhattan', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Seafood Sojourn', 32, 96, 'Sightseeing', 'Madrid Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Main Street Memories', 50, 168, 'Hiking', 'London South Bank', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Entertainment District', 34, 30, 'Sightseeing', 'Barcelona Las Ramblas', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rolling Routes', 27, 145, 'Sightseeing', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Waterfall Wonders', 43, 12, 'Hiking', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cathedral Corners', 34, 168, 'Sightseeing', 'Berlin Mitte', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gothic Ghost Walk', 19, 110, 'Sightseeing', 'Cape Town Coast', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Calm Currents', 34, 151, 'Hiking', 'Yellowstone Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gastronomy Guide', 22, 158, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Performance Path', 47, 239, 'Sightseeing', 'Paris Montmartre', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Discovery District', 50, 105, 'Sightseeing', 'Tokyo Shibuya', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Subway Secrets', 48, 191, 'Hiking', 'Lisbon Hills', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Foggy Frontier', 40, 11, 'Sightseeing', 'Rome City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Artisan Appetizers', 36, 249, 'Sightseeing', 'Edinburgh Royal Mile', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Baker’s Best', 37, 222, 'Hiking', 'Grand Canyon', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Marshland Magic', 35, 219, 'Hiking', 'Cairo Giza', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Hidden Gems', 28, 178, 'Hiking', 'Athens Acropolis', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Science Secrets', 21, 119, 'Sightseeing', 'Patagonia', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Brewery Best', 44, 103, 'Sightseeing', 'Venice Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Retro Road', 28, 51, 'Hiking', 'Patagonia', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Supernatural Saunter', 44, 14, 'Sightseeing', 'Dublin City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Eerie Echoes', 19, 136, 'Hiking', 'Amalfi Coast', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Canvas Culture', 37, 79, 'Sightseeing', 'New Orleans', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Fermentation Find', 42, 209, 'Hiking', 'Cairo Giza', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Visual Voyage', 28, 131, 'Sightseeing', 'Munich Old Town', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Nautical Night', 25, 145, 'Sightseeing', 'Central Park', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Brewery Best', 25, 106, 'Hiking', 'Amalfi Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Dreamy Destinations', 15, 172, 'Sightseeing', 'Athens Acropolis', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Epoch Explorations', 10, 218, 'Hiking', 'Kyoto Temples', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Abstract Adventures', 34, 181, 'Sightseeing', 'London South Bank', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Offbeat Outing', 29, 80, 'Hiking', 'Machu Picchu', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Color Conquest', 23, 168, 'Sightseeing', 'Vancouver Waterfront', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Dockside Dreams', 25, 127, 'Hiking', 'Barcelona Gothic Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Rock & Roll Road', 12, 190, 'Hiking', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Dockside Dreams', 18, 216, 'Hiking', 'Vancouver Waterfront', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Moonlit Mysteries', 40, 230, 'Sightseeing', 'Amalfi Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Boutique Best', 28, 52, 'Sightseeing', 'Venice Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('History Unveiled', 12, 130, 'Sightseeing', 'Istanbul Sultanahmet', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ski Slope Safari', 12, 222, 'Sightseeing', 'Berlin Mitte', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Runway Routes', 38, 57, 'Sightseeing', 'Patagonia', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tranquility Trail', 16, 76, 'Sightseeing', 'Dublin Liberties', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Gallery Glow', 10, 137, 'Hiking', 'French Quarter', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Knight’s Quest', 20, 189, 'Sightseeing', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Cemetery Secrets', 30, 109, 'Hiking', 'Old Town Prague', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sweet Shop Sojourn', 47, 167, 'Sightseeing', 'Lisbon Hills', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Stream Side Saunter', 29, 32, 'Hiking', 'Scottish Highlands', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Playful Path', 21, 123, 'Hiking', 'Central Park', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Alleyway Aesthetics', 20, 69, 'Hiking', 'Madrid Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Modern Metropolis', 10, 220, 'Hiking', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Peaceful Path', 16, 107, 'Sightseeing', 'Tokyo Shibuya', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ruins & Relics', 21, 123, 'Hiking', 'Cairo Giza', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sommelier’s Secret', 19, 66, 'Sightseeing', 'Amalfi Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Coastal Currents', 27, 37, 'Hiking', 'Barcelona Las Ramblas', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Eco-Explorer', 14, 248, 'Sightseeing', 'Vancouver Waterfront', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Crafty Circuit', 37, 81, 'Hiking', 'Yellowstone Park', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Antique Adventures', 29, 121, 'Sightseeing', 'Vancouver Waterfront', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Mansion Magic', 42, 57, 'Hiking', 'Machu Picchu', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Snapshot Safari', 50, 25, 'Hiking', 'Dubai Marina', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Central Circuit', 27, 15, 'Hiking', 'Berlin Mitte', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Ocean Odysseys', 19, 203, 'Hiking', 'Machu Picchu', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Spice Route', 13, 239, 'Hiking', 'Istanbul Sultanahmet', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Spirits of the Past', 22, 220, 'Sightseeing', 'New Orleans', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('War & Peace Walk', 44, 159, 'Sightseeing', 'Patagonia', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Strange Steps', 16, 172, 'Sightseeing', 'Tel Aviv Coastline', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Chilling Chronicles', 39, 71, 'Hiking', 'Provence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Distilled Dreams', 17, 195, 'Hiking', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Tombstone Tales', 11, 65, 'Sightseeing', 'Old Town Prague', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Smuggler’s Secret', 37, 57, 'Hiking', 'Barcelona Gothic Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Planetarium Path', 20, 9, 'Sightseeing', 'Vancouver Waterfront', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('The Tradition Trail', 32, 4, 'Hiking', 'Patagonia', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Dessert Discovery', 37, 201, 'Hiking', 'Scottish Highlands', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Steampunk Steps', 34, 19, 'Hiking', 'Grand Canyon', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Old Town Origins', 29, 15, 'Hiking', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Serenity Steps', 11, 103, 'Hiking', 'Swiss Alps', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Riddle Routes', 14, 37, 'Hiking', 'Florence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Pattern Path', 35, 139, 'Hiking', 'French Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Victory Voyage', 34, 45, 'Hiking', 'Dubai Marina', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Chilling Chronicles', 20, 28, 'Hiking', 'Cape Town Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, level) values ('Sorcerer’s Sojourn', 37, 121, 'Hiking', 'Athens Acropolis', 0, 1);
