INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'VIP Box', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Stone Circle', 2, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Breezy Point', 3, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Canyon Rim', 4, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Pulse Walk', 'Glass Elevator', 5, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Ceramic Kiln', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Glade', 2, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Runway Backstage', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Balcony', 4, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Legends Tour', 'Squirrel Scramble', 5, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Concrete Jungle', 'Throne Room', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Concrete Jungle', 'Liberty Square', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Concrete Jungle', 'Glass Elevator', 3, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Concrete Jungle', 'Control Room', 4, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Starting Block', 1, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Butterfly Bush', 2, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Lab Wing', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Spectacle', 'Temple Altar', 4, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metro Magic', 'Canal Bridge', 1, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metro Magic', 'Campus Green', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metro Magic', 'Hall of Fame', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metro Magic', 'Hotel Lounge', 4, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metro Magic', 'Hedge', 5, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Press Box', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Outlaw Hideout', 2, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Phantom Lane', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Drone Port', 4, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Hidden Alleys', 'Vineyard Row', 5, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Downtown Discovery', 'Runway Threshold', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Downtown Discovery', 'Alley', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Downtown Discovery', 'Row', 3, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Downtown Discovery', 'Pebble Path', 4, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Grand Boulevard', 'Smokehouse', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Bank', 1, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Landmark', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Library Steps', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Data Farm', 4, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('City Lights & Nights', 'Costume Trunk', 5, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Smart Saunter', 'Thunder Peak', 1, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Smart Saunter', 'Squirrel Scramble', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Smart Saunter', 'Industrial Loft', 3, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Street Smart Saunter', 'Locker Room', 4, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pavement Perspectives', 'Science Plaza', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Caravan Stop', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Flower Stall', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Ethics Circle', 3, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Landmark Loop', 'Manufacturing Floor', 4, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Cellar', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Reef Edge', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Twilight Pier', 3, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Dungeon Cell', 4, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Central Circuit', 'Lane', 5, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Borough Best', 'Antique Shop Corner', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Borough Best', 'Fish Ladder', 2, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Eco-Trail Marker', 1, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Tool Crib', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Gourmet Food Hall', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Rocky Ridge', 4, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('District Delights', 'Fashion Atelier', 5, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Capital Chronicles', 'Telescope Deck', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Capital Chronicles', 'Twilight Pier', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metropolitan Mosaic', 'Shield Wall', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metropolitan Mosaic', 'Underwater Cave', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Metropolitan Mosaic', 'Scene Shop', 3, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Garden Shed', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Clockwork Square', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sky-High Views', 'Startup Garage', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Main Street Memories', 'Training Ground', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Main Street Memories', 'Bistro Table', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Terrace Grill', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Vibrant Village', 'Street', 2, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Town Square Tales', 'Cryptography Cell', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Town Square Tales', 'Interview Wall', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Town Square Tales', 'DJ Booth', 3, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Town Square Tales', 'Data Farm', 4, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Avenue Adventures', 'Intersection', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Maintenance Bay', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Royal Gardens', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Cliff', 3, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Phantom Lane', 4, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Modern Metropolis', 'Tunnel', 5, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Soul', 'Verge', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Soul', 'Hummingbird Lane', 2, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Soul', 'Armor Rack', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Soul', 'Science Plaza', 4, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Library Steps', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Archive Basement', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Coral Reef Point', 3, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Cyber Security Center', 4, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Urban Oasis Hunt', 'Apple Tree', 5, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Bird Watch Tower', 1, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Fletcher’s Shop', 2, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Badger Set', 3, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Plaza', 4, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neighborhood Nuances', 'Jewelry Row', 5, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Daily Grind', 'Mews', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Daily Grind', 'Sheet Music Library', 2, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Daily Grind', 'Duty Free Lane', 3, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Daily Grind', 'Beach Bar', 4, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sidewalk Stories', 'Tactical Bay', 1, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sidewalk Stories', 'Porch', 2, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sidewalk Stories', 'Mixer Station', 3, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Glacial Path', 1, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Crosswalk Culture', 'Wine Cellar Door', 2, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Public Plaza Parade', 'Patio', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Architectural Arc', 'Fashion Boutique', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Hidden Garden', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Skyline Shadows', 'Industrial Loft', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neon Nights', 'Heritage House', 1, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neon Nights', 'Export Dock', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neon Nights', 'Rocky Ridge', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Neon Nights', 'Butterfly Bush', 4, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brick & Mortar', 'Modern Art Muse', 1, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brick & Mortar', 'Peak', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brick & Mortar', 'Cobblestone Alley', 3, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brick & Mortar', 'Watchtower Top', 4, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brick & Mortar', 'Spa Entrance', 5, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Core', 'Sand Bar', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The City Core', 'Temple Altar', 2, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfront Wonders', 'Clockwork Square', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfront Wonders', 'Goal Post', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfront Wonders', 'Stream Bed', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfront Wonders', 'Soundboard', 4, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dockside Dreams', 'Peak', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pier Perspectives', 'VR Simulation Room', 1, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Harbor Highlights', 'Cheese Cellar', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Harbor Highlights', 'Cocktail Bar', 2, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'South Port', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'Squirrel Scramble', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'Server Room', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bridge & Tunnel', 'Enigma Room', 4, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The High-Rise Hike', 'Suite Entrance', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The High-Rise Hike', 'Forest Clearing', 2, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The High-Rise Hike', 'Nightclub Entry', 3, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Alleyway Aesthetics', 'Modern Art Muse', 1, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Alleyway Aesthetics', 'Crescent', 2, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Subway Secrets', 'Opera House Foyer', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Subway Secrets', 'Ballet Studio', 2, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Transit Triumphs', 'Control Room', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Transit Triumphs', 'Lecture Hall', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Transit Triumphs', 'Tech Hub', 3, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Park & Promenade', 'Surgery Suite', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Park & Promenade', 'Row', 2, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Park & Promenade', 'Hidden Courtyard', 3, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Civic Center', 'Data Farm', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Civic Center', 'Archive Basement', 2, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Boarding Gate', 1, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Pitch Deck', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Quarter', 'Hilltop Chapel', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Entertainment District', 'City Hall Plaza', 1, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Financial Frontier', 'Suite 101', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Financial Frontier', 'Tool Crib', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Old Town Origins', 'Instrument Vault', 1, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Old Town Origins', 'Banquet Hall', 2, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Old Town Origins', 'Wellness Spa', 3, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Blacksmith Forge', 1, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Media Studio', 2, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Prop Room', 3, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Ethics Circle', 4, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Highlights', 'Secret Passage', 5, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Echoes', 'Breezy Point', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Timeless Traditions', 'Library Steps', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Parapet', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Flower Stall', 2, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Pit Stop', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Legacy Path', 'Wall', 4, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Observatory Dome', 1, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Border', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Roots & Routes', 'Media Zone', 3, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Mentorship Lounge', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Farm Stand', 2, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('History Unveiled', 'Visitor Center', 3, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Smokehouse', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Darkroom', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Fence', 3, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Past Perfect', 'Heritage House', 4, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancestral Avenues', 'Sideline', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Crossroads', 'Enigma Room', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cultural Crossroads', 'Supply Chain Hub', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Folklore Follow', 'Corner Tavern', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Folklore Follow', 'Banquet Hall', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Makeup Mirror', 1, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Mystery Gate', 2, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Dynasty Discovery', 'Canal Bridge', 3, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Lab Wing', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Export Dock', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Quality Control', 3, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Outlaw Hideout', 4, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Empire Eras', 'Alley', 5, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Medieval Mysteries', 'Urban Orchard', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Medieval Mysteries', 'Stream Crossing', 2, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Renaissance Revelations', 'Telescope Deck', 1, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Renaissance Revelations', 'Data Farm', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Colonial Chronicles', 'Basketball Hoop', 1, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Colonial Chronicles', 'Ring Side', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Colonial Chronicles', 'Highway', 3, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Colonial Chronicles', 'Prop Room', 4, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Stream Crossing', 1, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Track', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Intersection', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Harvest Barn', 4, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Landmark Lore', 'Banquet Hall', 5, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Museum Mile', 'Instrument Vault', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Museum Mile', 'Riverside Path', 2, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Monumental Moments', 'Piano Room', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Monumental Moments', 'Barrel Room', 2, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Monumental Moments', 'Tide Pool', 3, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Monumental Moments', 'VIP Lounge', 4, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sacred Sites', 'West Wing', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sacred Sites', 'Eco-Trail Marker', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Orchard Gate', 1, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Temple Trails', 'Pitch Deck', 2, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cathedral Corners', 'Sign', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Cathedral Corners', 'Biology Greenhouse', 2, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Fortress Finds', 'Greenhouse Row', 1, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Castle Conquest', 'Fuel Depot', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Castle Conquest', 'Keep Entrance', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Castle Conquest', 'Control Room', 3, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Lily Pad', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Bleachers', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Palace Perspectives', 'Starting Block', 3, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ruins & Relics', 'Eagle Nest', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Antique Adventures', 'Sun Deck', 1, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Antique Adventures', 'Cinema Row', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Antique Adventures', 'Pilgrim Path', 3, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Antique Adventures', 'Moonlight Path', 4, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Golden Age', 'Stone Circle', 1, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Golden Age', 'Vineyard Row', 2, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Golden Age', 'Lighthouse Trail', 3, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vintage Voyage', 'Founder’s Hall', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vintage Voyage', 'Kelp Forest', 2, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vintage Voyage', 'Medal Stand', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Retro Road', 'Fashion Atelier', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Retro Road', 'Scoreboard', 2, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Classic Culture', 'Shady Nook', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Classic Culture', 'Larder', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Classic Culture', 'Research Archive', 3, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Hidden Door', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Veranda', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Coach’s Bench', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Toy Store Window', 4, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Patriot Path', 'Vineyard Row', 5, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Liberty Lane', 'Crescent', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Liberty Lane', 'Lab Bench', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Tech Hub', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Timeline Wall', 2, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Trail', 3, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Misty Valley', 4, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Freedom Frontier', 'Silent Corridor', 5, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Botanical Garden Gate', 1, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Media Zone', 2, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Orchard Gate', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('War & Peace Walk', 'Safety Station', 4, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Windsock', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Sculpture Foundry', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Underpass', 3, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Industrial Icons', 'Cinema Row', 4, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Victorian Views', 'Surgery Suite', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Victorian Views', 'Glass Elevator', 2, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baroque Beauty', 'Rocky Ridge', 1, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baroque Beauty', 'Launch Pad', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Weaver’s Loom', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Hilltop Chapel', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Rehearsal Hall', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Woods', 4, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gothic Glories', 'Paddock Gate', 5, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Export Dock', 1, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Wine Cellar Door', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Mystery Gate', 3, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Assembly Line', 4, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ancient Artifacts', 'Jungle Canopy', 5, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tribal Tracks', 'Spice Market Entrance', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Craft Workshop', 1, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Porch', 2, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Lane', 3, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Garage Bay', 4, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Indigenous Insight', 'Press Conference Room', 5, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Tradition Trail', 'Armor Rack', 1, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Tradition Trail', 'Harvest Barn', 2, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Arch', 1, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Dean’s Office', 2, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Tide Pool', 3, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Masterpiece Morning', 'Spare Parts Rack', 4, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gallery Gazing', 'Sunken Wreck', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gallery Gazing', 'Pine Forest', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gallery Gazing', 'Cheese Aging Room', 3, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gallery Gazing', 'Old Mill', 4, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gallery Gazing', 'Wall', 5, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Curated Culture', 'Cellar Door', 1, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Curated Culture', 'Apothecary Shelf', 2, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Curated Culture', 'Trail', 3, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Hues', 'Sign', 1, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Hues', 'Control Room', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Heritage Hues', 'Old City Gate', 3, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The History Hut', 'Forest Clearing', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Hermit Cave', 1, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Theater District Sign', 2, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Epoch Explorations', 'Hilltop Chapel', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Spice Market Entrance', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Scene Shop', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Oasis Well', 3, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Coworking Courtyard', 4, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Century Circuit', 'Flower Stall', 5, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Operations Center', 1, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Time Traveler’s Trek', 'Eco-Trail Marker', 2, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wild Wanderer', 'Mentorship Lounge', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wild Wanderer', 'Quality Control', 2, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Nature’s Nook', 'Smithy', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Nature’s Nook', 'Local Artisan Market', 2, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Nature’s Nook', 'Street Art Wall', 3, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Forest Frontiers', 'Medical Lab', 1, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Mountain Majesty', 'Spa Entrance', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Mountain Majesty', 'Fermentation Lab', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Valley Views', 'Edge', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Valley Views', 'Royal Gardens', 2, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Valley Views', 'Art Gallery Lane', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Valley Views', 'Hidden Garden', 4, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Canyon Conquest', 'Lane', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Canyon Conquest', 'Courtyard', 2, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Canyon Conquest', 'Rabbit Hole', 3, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Canyon Conquest', 'Biology Greenhouse', 4, 45);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Canyon Conquest', 'Foggy Bridge', 5, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('River Rapids', 'Timeline Wall', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lake Liberty', 'Great Hall', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lake Liberty', 'Hilltop Chapel', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lake Liberty', 'Lecture Hall', 3, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lake Liberty', 'Cursed Well', 4, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ocean Odysseys', 'Campus Green', 1, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ocean Odysseys', 'Hay Loft', 2, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ocean Odysseys', 'Badger Set', 3, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ocean Odysseys', 'Scene Shop', 4, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Cursed Well', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Moat Edge', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Pine Forest', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Neon Street', 4, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Currents', 'Chocolate Factory', 5, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Flower Stall', 1, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Mountain Pass', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Hotel Lounge', 3, 35);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Press Conference Room', 4, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Island Intervals', 'Botanical Garden Pond', 5, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Jungle Jaunt', 'Incubator Wing', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Jungle Jaunt', 'Opera House Foyer', 2, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Jungle Jaunt', 'Victory Arch', 3, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Safari Solitude', 'Distillation Column', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Safari Solitude', 'Hollow', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Safari Solitude', 'Investor Gallery', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Safari Solitude', 'Smokehouse', 4, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Desert Dreams', 'Evening Balcony', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Desert Dreams', 'Sunny Glade', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Desert Dreams', 'Botanical Garden Pond', 3, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Assembly Line', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Botanical Greenhouse', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Ancient Manuscript Room', 3, 22);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Oasis Observations', 'Valley', 4, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Summit Seekers', 'Fuel Depot', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Basement Pub', 1, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Costume Trunk', 2, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Beach', 3, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Sacred Spring', 4, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Trailblazer Tracks', 'Grove', 5, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Backcountry Bliss', 'Sand Dune', 1, 56);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Jazz Club Corner', 1, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Riverfront Pier', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Fish Ladder', 3, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Old Mill', 4, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Wilderness Way', 'Tunnel', 5, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flora & Fauna', 'Hidden Courtyard', 1, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Hotel Lounge', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Surgery Suite', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Skyline Balcony', 3, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Academic Atrium', 4, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Botanical Best', 'Botanical Garden Pond', 5, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Garden Glimpse', 'Ethics Circle', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Garden Glimpse', 'Crescent', 2, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Garden Glimpse', 'Medal Stand', 3, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'Sacred Grove', 1, 40);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'University Quad', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Bloom & Blossom', 'Greenhouse Row', 3, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Beach', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Podium', 2, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Editing Suite', 3, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Junction', 4, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunrise Safari', 'Misty Valley', 5, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sunset Serenity', 'Avionics Bay', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Starlight Sojourn', 'Scoreboard', 1, 23);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Oracle Seat', 1, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Avionics Bay', 2, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Kitchen Hearth', 3, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Moonlight Meadow', 'Stream Crossing', 4, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Eco-Explorer', 'Starting Block', 1, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Wildflower Field', 1, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Runway Backstage', 2, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Flower Stall', 3, 27);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Green Getaway', 'Startup Space', 4, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sustainable Steps', 'Butterfly Bush', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sustainable Steps', 'Press Conference Room', 2, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Great Outdoors', 'Basketball Hoop', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Great Outdoors', 'Meditation Rock', 2, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Peak Performance', 'Coach’s Bench', 1, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ridge Runner', 'Riverfront Pier', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Ridge Runner', 'Light', 2, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Meadow Muse', 'Metro Entrance', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Meadow Muse', 'Lily Pad', 2, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfall Wonders', 'Tea House', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Waterfall Wonders', 'Gourmet Food Hall', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'Hollow', 1, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'Apothecary Shelf', 2, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'VIP Lounge', 3, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'Labeling Station', 4, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Stream Side Saunter', 'Philosophy Garden', 5, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Marshland Magic', 'Crossing', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Cliffs', 'Instrument Vault', 1, 43);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coastal Cliffs', 'Owl Tree', 2, 49);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'Pitch Deck', 1, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'West Wing', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'Orchard Gate', 3, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sandy Shores', 'Medal Stand', 4, 28);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Reef Revelations', 'Maintenance Bay', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Reef Revelations', 'Robotics Lab', 2, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Reef Revelations', 'Library Steps', 3, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Reef Revelations', 'Cobblestone Alley', 4, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Reef Revelations', 'Island Jetty', 5, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Arctic Adventures', 'Cinema Row', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Old Mill', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Armor Rack', 2, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Sun Deck', 3, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Corner Tavern', 4, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tundra Trails', 'Surgery Suite', 5, 60);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Crescent', 1, 42);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Command Post', 2, 50);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Startup Garage', 3, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savanna Stroll', 'Craft Workshop', 4, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Rainforest Rhythms', 'Botanical Garden Pond', 1, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Woodland Walk', 'Recovery Room', 1, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Woodland Walk', 'Arch', 2, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pine Path', 'Caravan Stop', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pine Path', 'Hedge', 2, 52);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pine Path', 'Al-Expert Hub', 3, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Hollow', 1, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Puppet Theater', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Highland Hike', 'Vineyard Row', 3, 32);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lowland Loop', 'Sand Dune', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lowland Loop', 'Marketing Loft', 2, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lowland Loop', 'Green Room', 3, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Lowland Loop', 'Fish Ladder', 4, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Earthly Escapes', 'Hydrotherapy Pool', 1, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Earthly Escapes', 'Bandit Camp', 2, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Peak', 1, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Instrument Vault', 2, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Operations Center', 3, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Thunder Peak', 4, 41);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Horizon Hunt', 'Armorer’s Bench', 5, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Taste Buds Tour', 'Server Room', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Phantom Lane', 1, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Cyber Security Center', 2, 57);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Industrial Loft', 3, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Culinary Conquest', 'Court Side', 4, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gourmet Gazette', 'Bridge', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gourmet Gazette', 'Junction', 2, 37);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gourmet Gazette', 'Textile Mill', 3, 47);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Gourmet Gazette', 'Tide Pool', 4, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flavor Fusion', 'Attic Window', 1, 16);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Flavor Fusion', 'Farm Stand', 2, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'Botanical Garden Pond', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'Spare Parts Rack', 2, 44);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'Square', 3, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Savory Steps', 'Hangar Gate', 4, 54);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sweet Street', 'Quality Control', 1, 53);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sweet Street', 'Safety Station', 2, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sweet Street', 'DJ Booth', 3, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sweet Street', 'Spare Parts Rack', 4, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Sweet Street', 'Legend Statues', 5, 33);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Landmark', 1, 26);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Crescent', 2, 24);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Rune Stone', 3, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pastry Path', 'Press Conference Room', 4, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Baker’s Best', 'UX Workshop', 1, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Mountain Trailhead', 1, 58);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Fox Den', 2, 15);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Ridge', 3, 36);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Hay Loft', 4, 29);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('The Spice Route', 'Haunted Shack', 5, 51);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Dance Floor', 1, 19);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Market Munchies', 'Drone Port', 2, 38);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Otter Slide', 1, 17);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Customs Office', 2, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Farm to Fork', 'Herbalist Garden', 3, 34);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Orchestra Pit', 1, 25);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Vineyard Row', 2, 48);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Bird Watch Tower', 3, 20);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Vineyard Voyage', 'Watchtower Top', 4, 46);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Winery Wonders', 'Attic Window', 1, 21);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Winery Wonders', 'Avionics Bay', 2, 59);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Winery Wonders', 'Dungeon Cell', 3, 30);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brewery Best', 'Stream Crossing', 1, 55);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Brewery Best', 'Keep Entrance', 2, 18);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Pub Crawl Classics', 'Desert Oasis', 1, 39);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Coffee Culture', 'Summit', 1, 31);
INSERT INTO TOURSTATION (t_name, s_name, t_index, s_during) VALUES ('Tea Time Trails', 'Transit Lounge', 1, 46);