insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Snorkel Steps', 'Pirate Cove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 0, 'Metropolitan Mosaic', 'Overpass');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Forbidden Finds', 'Local Artisan Market');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'Sandy Shores', 'Deer Track');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Street Art Safari', 'Visitor Center');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Design District', 'Road');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Sail Away', 'Dungeon Cell');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Wilderness Way', 'Zen Garden');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Ancient Anathemata', 'Tool Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Jungle Jaunt', 'Downtown Hub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Ridge Runner', 'Sand Dune');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Classic Culture', 'Armory');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Ice Cream Island', 'Circle');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'District Delights', 'Border');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Candy Cane Lane', 'Squirrel Scramble');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Library Lore', 'Hedge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Kitsch Kingdom', 'Trail');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Skydiving Sojourn', 'Puppet Theater');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Urban Oasis Hunt', 'Lake Shore');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Climb & Conquer', 'Beach Cove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Picnic Parade', 'Hollow');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Hidden Gems', 'Puppet Theater');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 1, 'Aerial Adventures', 'Cursed Well');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Abstract Adventures', 'Launch Pad');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 1, 'Sommelier’s Secret', 'Antique Shop Corner');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Secret Societies', 'Medal Stand');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Treasure Trove', 'Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Fashion Frontier', 'Cursed Well');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Mural Magic', 'Bus Terminal Hub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 2, 'Knight’s Quest', 'Road');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Style Saunter', 'Art Gallery Lane');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Active Adventures', 'Vault Entry');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Rogue Roads', 'Wolf Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Entertainment District', 'South Port');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Skyline Shadows', 'Metro Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Sustainable Steps', 'Clockwork Square');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Shopaholic Safari', 'Coffee Roastery');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Chilling Chronicles', 'Haunted Shack');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 0, 'Elite Escapades', 'Sunny Patch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Crime & Consequence', 'Deer Track');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Resort Revelations', 'Spiral Stairs');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Forest Frontiers', 'Caravan Stop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Nightcap Nibbles', 'Junction');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Arena Arc', 'Court Side');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Rainforest Rhythms', 'Bistro Table');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Artisan Appetizers', 'Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Brewery Best', 'Foggy Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Maze Magic', 'Marker');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Vogue Voyage', 'South Port');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Ancient Anathemata', 'Thunder Peak');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Gourmet Gazette', 'Coral Reef Point');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Sorcerer’s Sojourn', 'Neon Street');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Antique Adventures', 'Castle Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Game On Garden', 'Shady Nook');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 2, 'Bookworm Boulevard', 'Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Sunset Serenity', 'Canal Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 1, 'After Dark Adventures', 'Treasury Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Silk Road Saunter', 'Moonlight Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Quirky Quarters', 'Spa Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Oddity Odyssey', 'Botanical Garden Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 2, 'Safari Solitude', 'Woods');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Woodland Walk', 'Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Hidden History', 'Shady Nook');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Ghostly Gaze', 'Locker Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Playground Parade', 'Sign');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Fermentation Find', 'Craft Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Film Frame Follow', 'Shady Nook');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Chilling Chronicles', 'Lab Bench');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Main Street Memories', 'Pedestrian Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Pastry Path', 'Sign');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Sunny Side Up', 'Glacial Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Champion’s Choice', 'West Wing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Bewitched Boulevard', 'Fortress Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'High-Wire Hike', 'Street Art Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Sunset Serenity', 'Royal Gardens');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Meadow Muse', 'Medal Stand');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Quirky Quarters', 'Banquet Hall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Fashion Frontier', 'Bakery Corner');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 2, 'Gentle Gaze', 'Suite 101');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Eerie Echoes', 'Wolf Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Rainforest Rhythms', 'Control Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Fashion Frontier', 'Tailor’s Shop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Savanna Stroll', 'Historic Clock Tower');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Vineyard Voyage', 'Hollow');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Shopaholic Safari', 'Scholar’s Hall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Meadow Muse', 'Silent Corridor');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Dark District', 'Valley');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Subway Secrets', 'Lighthouse Trail');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Central Circuit', 'Tech Hub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'Aerial Adventures', 'Brewery Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Public Plaza Parade', 'Pillar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Surf & Sand', 'Larder');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Pine Path', 'Garden Shed');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Hobby Horse Hunt', 'Museum Lobby');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Starlight Sojourn', 'Vault Entry');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Shopaholic Safari', 'Kitchen Counter');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Ocean Odysseys', 'Intersection');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'Twilight Toast', 'Bus Terminal Hub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Vogue Voyage', 'Plaza');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Island Intervals', 'Royal Gardens');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 0, 'Ridge Runner', 'Garage Bay');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Enigma Escape', 'Alumni Walk');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Jogger’s Jaunt', 'Avenue');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Sommelier’s Secret', 'Brewery Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Oddity Odyssey', 'Throne Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Cheese Circuit', 'Central Fountain');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Wonderland Walk', 'Cellar Door');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Cycle Circuit', 'Banner Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Handcrafted Highlights', 'Evening Balcony');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'The Grand Boulevard', 'Bleachers');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Ice Rink Routes', 'Passage');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 1, 'Carefree Circuit', 'Fence');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'River Rapids', 'Suite Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Old Town Origins', 'Theater District Sign');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Town Square Tales', 'Hidden Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Elegant Escapes', 'Glade');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Puzzling Path', 'Frog Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Active Adventures', 'Valley');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Enigma Escape', 'Skywalk Entry');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Retro Road', 'Court Side');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 3, 'The Great Outdoors', 'Midnight Alley');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Toy Town Tour', 'Grandstand');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Winery Wonders', 'Banner Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Sunny Side Up', 'Harbor Viewpoint');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Retail Revelations', 'Midnight Alley');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 1, 'Prehistoric Path', 'Morning Terrace');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Sustainable Steps', 'Modern Art Muse');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Ridge Runner', 'Patio');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Oddity Odyssey', 'Dean’s Office');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Heritage Highlights', 'Shady Nook');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 0, 'BBQ Belt', 'Spiral Stairs');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Diamond District', 'Marker');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Ice Rink Routes', 'Blacksmith Forge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'The History Hut', 'Theater District Sign');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Mindful Movements', 'Port Authority');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Color Conquest', 'Glass Elevator');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Sweet Street', 'Lobby Bar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Superhero Steps', 'Zen Garden');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Coffee Culture', 'Toy Store Window');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'After Dark Adventures', 'Campus Green');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Island Intervals', 'Clockwork Square');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Artistic Avenues', 'Court Side');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Ancient Artifacts', 'Cellar Door');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Rare Routes', 'Shell Beach');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Knight’s Quest', 'Woods');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Strange Steps', 'Tea House');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Pizza Path', 'Patio');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Past Perfect', 'Hidden Garden');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Game Day Glimpse', 'Chef’s Table');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Dreamy Destinations', 'Light');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Balloon Boulevard', 'Lily Pad');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Balloon Boulevard', 'Bistro Table');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Picnic Parade', 'Calm Creek');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Smuggler’s Secret', 'VIP Box');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Meadow Muse', 'Thunder Peak');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Dark District', 'Way');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 0, 'The Tasting Table', 'Royal Gardens');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Victory Voyage', 'Deck');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'High Society Sojourn', 'Peak');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Harbor Highlights', 'Badger Set');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Coffee Culture', 'Stream Crossing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 1, 'Noodle Night', 'Bear Cave');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Peculiar Path', 'Pirate Cove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'The Daily Grind', 'Track');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Street Food Safari', 'Kitchen Counter');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Spa Serenity', 'Pantry');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Main Street Memories', 'Study Desk');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Echo Exploration', 'Coffee Roastery');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Bewitched Boulevard', 'Fox Den');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Slow Lane Saunter', 'Castle Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Inspiration Island', 'Diamond Vault');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Cursed Corners', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Midnight Murmurs', 'Ballet Studio');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'First Class Follow', 'Shady Nook');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Manor Muse', 'Founder’s Hall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Fantasy Frontier', 'Botanical Garden Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Toy Town Tour', 'Chocolate Factory');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Estate Explorations', 'Basin');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Safari Solitude', 'Old Mill');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Paraglide Path', 'Street Art Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Geek Gaze', 'Lobby Bar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Acoustic Adventures', 'Sunset Point');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Reflection Routes', 'Reflection Pool');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Geek Gaze', 'Breezy Point');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Harbor Highlights', 'Rocky Ridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Sail Away', 'Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Science Secrets', 'Twilight Pier');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Stadium Stars', 'Hidden Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Vineyard Voyage', 'Spa Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Cycle Circuit', 'Corner Tavern');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Entertainment District', 'Cave Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Sweet Street', 'Craft Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Scuba Safari', 'Apple Tree');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Industrial Icons', 'Evening Balcony');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Nightcap Nibbles', 'Lake Shore');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'First Class Follow', 'Willow Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 3, 'Wild Wanderer', 'Dugout');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Brewery Best', 'Pillar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Curiosities Circuit', 'Blacksmith Forge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Mansion Magic', 'Stream Crossing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Offbeat Outing', 'Summit');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Paranormal Parade', 'Marker');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Waterfront Wonders', 'Shady Nook');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Pedal Power', 'Jewelry Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Baker’s Best', 'Training Ground');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Downtown Discovery', 'Garage Bay');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Snorkel Steps', 'Terrace Grill');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'The City Soul', 'Rooftop Bar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Steampunk Steps', 'Wolf Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Farm to Fork', 'Spice Market Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Sweet Shop Sojourn', 'Marker');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Polyglot Parade', 'Glass Elevator');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Jungle Jaunt', 'Starry Deck');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Nerd Night', 'Glade');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'Riddle Routes', 'Pedestrian Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 0, 'Underworld Unveiled', 'Nature Boardwalk');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Noir Night', 'Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Sprint Steps', 'Oasis Well');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Ski Slope Safari', 'Suite 101');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Marathon Mile', 'Pine Forest');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Earthly Escapes', 'Canal Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Neighborhood Nuances', 'Street');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Antique Adventures', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Orchard Outing', 'Porch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 2, 'Kitchen Kingdom', 'Zen Garden');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Lake Liberty', 'Plaza');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Forest Frontiers', 'Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Creative Corners', 'Ballet Studio');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Yacht Yard', 'Circle');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Peaceful Path', 'Metro Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Green Getaway', 'Intersection');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Stadium Stars', 'Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Mystery Mile', 'Bus Terminal Hub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Noodle Night', 'Shell Beach');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Zoo Zone', 'Central Fountain');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Skydiving Sojourn', 'Edge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 1, 'Curated Culture', 'Pine Forest');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Cryptic Circuit', 'Skyline Balcony');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Silk Road Saunter', 'Bear Cave');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'The City Soul', 'Control Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'First Class Follow', 'Frog Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Spooky Steps', 'Foggy Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'Broadway Best', 'Rocky Ridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Pavement Perspectives', 'Badger Set');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Noir Night', 'Fox Den');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Sidewalk Stories', 'Bandit Camp');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Evening Elegance', 'Candy Shop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Ancestral Avenues', 'Tool Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Brunch Bunch', 'Opera House Foyer');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Vogue Voyage', 'Oak Grove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Masterpiece Muse', 'Study Desk');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Spa Serenity', 'Evening Balcony');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'Dino Discovery', 'Rooftop Bar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'Kitchen Kingdom', 'Campus Green');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Flea Market Follow', 'Locker Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Downtown Discovery', 'Metro Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Exotic Eats', 'Wildflower Field');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Diamond District', 'Marker');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Sculpture Safari', 'Fox Den');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Sunset Serenity', 'Metro Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Literary Legend', 'Botanical Garden Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 1, 'Sidewalk Stories', 'Meditation Hall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Downtown Discovery', 'Panoramic Lookout');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Visual Voyage', 'Mountain Trailhead');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Dynasty Discovery', 'Locker Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Serenity Steps', 'Ancient Stone Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Highland Hike', 'Botanical Garden Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'The Vibrant Village', 'Porch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Masterpiece Morning', 'Library Steps');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Pattern Path', 'Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Noir Night', 'Tool Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Orchard Outing', 'Urban Orchard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Paranormal Parade', 'Modern Art Muse');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 2, 'Startup Safari', 'Moonlight Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Cryptic Circuit', 'Luxury Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Rainforest Rhythms', 'Toy Store Window');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Bewitched Boulevard', 'Lane');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Graffiti Gaze', 'Calm Creek');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Mythic Moments', 'Deer Track');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Palette Path', 'Runway End');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Spirits of the Past', 'Grove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Dinner District', 'Wolf Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'Creative Currents', 'Coffee Roastery');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Math Magic', 'Lighthouse Trail');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Capital Chronicles', 'Library Stacks');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Artisan Appetizers', 'Local Artisan Market');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Two-Wheel Trek', 'Breezy Point');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Vegan Ventures', 'Square');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Cursed Corners', 'Intersection');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Fortress Finds', 'Attic');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Animal Adventures', 'Morning Terrace');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 1, 'Brushstroke Best', 'Tower Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Gastronomy Guide', 'Edge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Lowland Loop', 'Fish Ladder');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Cemetery Secrets', 'Willow Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Puppet Parade', 'Candy Shop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Creative Corners', 'Hidden Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Spa Serenity', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Curated Culture', 'Thunder Peak');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Nightfall Nuances', 'Art Gallery Lane');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Epicurean Escape', 'Art Gallery Lane');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Mythic Moments', 'Lab Bench');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Dessert Discovery', 'Craft Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Oddity Odyssey', 'Victory Arch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Fossil Find', 'Junction');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Fitness Frontier', 'Panoramic Lookout');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Elegant Escapes', 'Spiral Stairs');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'River Rapids', 'Phantom Lane');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Retreat Routes', 'Wilds.');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Traditional Tastes', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 2, 'Monumental Moments', 'City Hall Plaza');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Backcountry Bliss', 'Post');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Oddity Odyssey', 'East Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'The Full Plate', 'Pillar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Family Fun Fest', 'Library Steps');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Medieval Mysteries', 'Arch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Hidden History', 'Hollow');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Puzzling Path', 'Rim');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Pirate’s Path', 'Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 2, 'Serenity Steps', 'Weaver’s Loom');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Shadow Steps', 'Fortress Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Easy Breezy', 'Fashion Boutique');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Waterfront Wonders', 'Sunset Point');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Ice Cream Island', 'Suite 101');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Family Fun Fest', 'Liberty Square');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Secret Societies', 'Pit Stop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Velvet Voyage', 'Alley');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Island Intervals', 'Campus Green');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Zen Zone', 'VIP Box');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Dinner District', 'Coworking Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 2, 'Soundscape Safari', 'Rooftop Bar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 0, 'Victorian Views', 'Deer Track');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Acoustic Adventures', 'Startup Space');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Farm to Fork', 'Larder');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 2, 'Fashion Frontier', 'Willow Pond');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Crime & Consequence', 'Dean’s Office');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Earthly Escapes', 'Control Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Park & Promenade', 'Roundabout');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Industrial Icons', 'Crescent');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Vinyl Voyage', 'Bakery Corner');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Victorian Views', 'Village Square');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'Echo Exploration', 'Plaza');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Evening Elegance', 'Rooftop Bar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Ski Slope Safari', 'Throne Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Alchemist’s Arc', 'Dungeon Cell');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Trailblazer Tracks', 'Industrial Loft');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Pavement Perspectives', 'Dungeon Cell');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Mural Magic', 'Neon Street');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Diamond District', 'Skyline Balcony');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Broadway Best', 'Craft Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'The Folklore Follow', 'Wilds.');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Valley Views', 'Wine Vault');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Exclusive Echoes', 'Botanical Greenhouse');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Artistic Avenues', 'Cliff');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Puzzle Park', 'Marble Arch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'Tea Time Trails', 'Hilltop Chapel');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Ghostly Gaze', 'Startup Space');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Limousine Lore', 'Pirate Cove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'After Dark Adventures', 'Deer Track');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Sunset Serenity', 'Banner Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Cartoon Circuit', 'Reflection Pool');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Garden Glimpse', 'Cursed Well');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Retro Revival', 'Canyon Rim');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Farm to Fork', 'Server Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 4, 'Oasis Observations', 'Bank');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Neon Nights', 'Peak');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 3, 'Inventor’s Island', 'Antique Shop Corner');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Alchemist’s Arc', 'Runway End');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Velvet Voyage', 'Sand Dune');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 0, 'Time Traveler’s Trek', 'Sign');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'Illusion Island', 'Cinema Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Waterfall Wonders', 'Botanical Garden Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Illusion Island', 'Rooftop Deck');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Magic Mile', 'Armory');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'Avenue Adventures', 'Hidden Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Poet’s Path', 'Eagle Nest');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'Cultural Quarter', 'Passage');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Bouldering Best', 'Bird Watch Tower');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Quiet Quarters', 'Fox Den');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Hidden History', 'Forest');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 3, 'Limousine Lore', 'Crescent');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Local Larder', 'Phantom Lane');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Picnic Parade', 'Cursed Well');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Supernatural Saunter', 'Wolf Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Slow Lane Saunter', 'Practice Field');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Resort Revelations', 'Coral Reef Point');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Penthouse Perspectives', 'Porch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Digital District', 'Rail Station Plaza');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Easy Breezy', 'Trade Post');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Vintage Vibes', 'Hangar Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Fashion Forward', 'Junction');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'Surrealism Sojourn', 'Safari Outpost');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 0, 'Hobby Horse Hunt', 'Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Canyon Conquest', 'Dugout');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Sail Away', 'Cursed Well');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Bouldering Best', 'Spa Entrance');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Manor Muse', 'Owl Tree');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'Backcountry Bliss', 'Eagle Nest');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Skyline Spectacle', 'Fish Ladder');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Entertainment District', 'Riverfront Pier');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Berry Best', 'Opera House Foyer');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Dynasty Discovery', 'Sign');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 0, 'Dark District', 'Caravan Stop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Berry Best', 'Shore');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 1, 'Spirits of the Past', 'Glade');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Spa Serenity', 'Overpass');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'Vintage Voyage', 'Study Desk');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'High-Wire Hike', 'Apple Tree');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Bridge & Tunnel', 'Coworking Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'The Tasting Table', 'Sculptural Park');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Sculpture Safari', 'Lighthouse Trail');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'Bloom & Blossom', 'Deck');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Tarot Trails', 'Victorian Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Texture Trails', 'Skyline Balcony');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Funky Frontier', 'Ancient Stone Bridge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Portrait Parade', 'Fashion Boutique');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 0, 'Knight’s Quest', 'Wolf Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 2, 'Wildlife Watch', 'Port Authority');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Playground Parade', 'Underpass');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 1, 'Ruins & Relics', 'Verge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Operatic Odyssey', 'Runway End');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 1, 'Color Conquest', 'Pillar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Horizon Hunt', 'Pit Stop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 0, 'Bubble Boulevard', 'Rim');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Final Frontier', 'Hangar Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Zip-Line Zeal', 'Canyon Rim');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'The Daily Grind', 'Training Ground');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 2, 'Bizarre Boulevard', 'Weaver’s Loom');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'The Daily Grind', 'Beacon');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 4, 'Paranormal Parade', 'Alumni Walk');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Puzzling Path', 'Startup Space');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 0, 'Creative Corners', 'Royal Gardens');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Library Lore', 'Dean’s Office');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 3, 'The Architectural Arc', 'Bistro Table');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'The Great Outdoors', 'Circle');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Gothic Glories', 'Tower Room');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 1, 'Balloon Best', 'Flower Stall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Pizza Path', 'Local Artisan Market');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Nightcap Nibbles', 'Valley');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 2, 'Echo Exploration', 'Boulevard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 1, 'Tombstone Tales', 'Yoga Studio');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Knight’s Quest', 'Sacred Grove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Mystery Mile', 'Crossing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Exclusive Echoes', 'Gourmet Food Hall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'District Delights', 'Lake Shore');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Robot Routes', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 0, 'The Vibrant Village', 'Forest Clearing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Midnight Murmurs', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 3, 'The Museum Mile', 'Library Steps');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Gastronomy Guide', 'Campus Green');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 1, 'Retro Road', 'Street Art Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Cycle Circuit', 'Desert Oasis');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Rhythm Routes', 'Arch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 3, 'Berry Best', 'Diamond Vault');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 0, 'Retreat Routes', 'Post');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 4, 'Math Magic', 'Street');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Canvas Culture', 'Fish Ladder');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Vogue Voyage', 'Secret Passage');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Sunset Spirits', 'West Wing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (9, 3, 'Vegan Ventures', 'Brewery Courtyard');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'The Full Plate', 'Court Side');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 3, 'Olympic Odyssey', 'Rail Station Plaza');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 1, 'Dockside Dreams', 'Cheese Cellar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Inventor’s Island', 'Pirate Cove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Wellness Wonders', 'Craft Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'Supernatural Saunter', 'Medal Stand');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 1, 'Outlaw Odysseys', 'Hotel Lounge');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Savory Steps', 'University Quad');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Wellness Walk', 'Runway End');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 4, 'Color Conquest', 'Opera House Foyer');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Pavement Perspectives', 'Lab Bench');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Metro Magic', 'Hidden Garden');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Climb & Conquer', 'Basement Pub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 1, 'Nautical Night', 'Weaver’s Loom');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Tundra Trails', 'Highway');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 0, 'Wellness Wonders', 'Museum Lobby');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Indigenous Insight', 'Greenhouse Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 4, 'Vintage Voyage', 'Potter’s Studio');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Winter Wonderland', 'East Gate');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 0, 'Fossil Find', 'Riddle Wall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 3, 'Space Safari', 'Craft Workshop');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 4, 'Flea Market Follow', 'Island Jetty');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 2, 'Resort Revelations', 'Porch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 3, 'Flora & Fauna', 'Peak');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'The History Hut', 'Lab Wing');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 1, 'Pirate’s Path', 'Pillar');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Pastry Path', 'Starry Deck');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (4, 4, 'Ski Slope Safari', 'Press Box');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (2, 2, 'Island Intervals', 'Sacred Grove');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 4, 'Vegan Ventures', 'Passage');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (10, 4, 'Posh Path', 'Pine Forest');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 3, 'Woodland Walk', 'Pantry');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (7, 2, 'Ice Rink Routes', 'Basement Pub');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 4, 'Prehistoric Path', 'Row');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (3, 2, 'Aesthetic Arc', 'Path');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (5, 2, 'Artisan Appetizers', 'Porch');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 3, 'Tundra Trails', 'Spiral Stairs');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (6, 0, 'The Golden Age', 'Lecture Hall');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (1, 1, 'Discovery District', 'Knight’s Table');
insert into TOURSTATION (t_index, s_during, t_name, s_name) values (8, 2, 'Musical Magic', 'Coffee Roastery');
