insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (1, 'Magdalen', 'Domoni', '312-231-5995', 'mdomoni0@dmoz.org', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (2, 'Fernanda', 'Cornils', '298-990-4142', 'fcornils1@comsenz.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (3, 'Becka', 'Grafham', '324-389-0793', 'bgrafham2@github.com', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (4, 'Miranda', 'Gregor', '980-101-8611', 'mgregor3@dedecms.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (5, 'Vicky', 'Striker', '400-478-2515', 'vstriker4@dyndns.org', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (6, 'Jesus', 'Skermer', '999-995-2939', 'jskermer5@ehow.com', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (7, 'Teodorico', 'Buske', '960-335-1712', 'tbuske6@goodreads.com', 'Metropolitan Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (8, 'Fraser', 'Bewley', '953-270-1147', 'fbewley7@seattletimes.com', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (9, 'Morgana', 'Messam', '793-950-4126', 'mmessam8@163.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (10, 'Abigael', 'Blamphin', '316-201-4041', 'ablamphin9@wufoo.com', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (11, 'Cherida', 'Gannon', '945-269-5036', 'cgannona@linkedin.com', 'National Park Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (12, 'Ray', 'Molesworth', '986-220-0692', 'rmolesworthb@rakuten.co.jp', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (13, 'Taffy', 'Olechnowicz', '374-344-3326', 'tolechnowiczc@themeforest.net', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (14, 'Zane', 'Waggitt', '194-796-3477', 'zwaggittd@cdbaby.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (15, 'Gareth', 'Salle', '612-381-5607', 'gsallee@omniture.com', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (16, 'Vania', 'Ecclestone', '257-247-1623', 'vecclestonef@kickstarter.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (17, 'Sarajane', 'Fincham', '287-749-2094', 'sfinchamg@pcworld.com', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (18, 'Jemmy', 'Checo', '779-519-5134', 'jchecoh@networkadvertising.org', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (19, 'Courtnay', 'Howsley', '603-358-0190', 'chowsleyi@icio.us', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (20, 'Cordelie', 'Anfossi', '965-541-1715', 'canfossij@dropbox.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (21, 'Darbee', 'Merwood', '900-326-8579', 'dmerwoodk@weebly.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (22, 'Livvy', 'McGarvey', '425-561-5590', 'lmcgarveyl@netvibes.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (23, 'Kimberli', 'Savins', '834-852-7824', 'ksavinsm@house.gov', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (24, 'Barclay', 'O''Glassane', '695-634-1999', 'boglassanen@twitpic.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (25, 'Kristal', 'Foxley', '255-523-2861', 'kfoxleyo@europa.eu', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (26, 'Murial', 'MacNelly', '431-749-4249', 'mmacnellyp@mashable.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (27, 'Hammad', 'Grinley', '202-798-9010', 'hgrinleyq@netscape.com', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (28, 'Erminia', 'Gehrtz', '667-348-0359', 'egehrtzr@chronoengine.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (29, 'Allx', 'Straine', '859-464-5750', 'astraines@washingtonpost.com', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (30, 'Ardeen', 'Dowthwaite', '229-890-8863', 'adowthwaitet@exblog.jp', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (31, 'Lane', 'Ricarde', '729-249-8546', 'lricardeu@deviantart.com', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (32, 'Arnuad', 'Trolley', '808-364-6978', 'atrolleyv@noaa.gov', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (33, 'Ogdon', 'Manicom', '633-900-0721', 'omanicomw@salon.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (34, 'Sayres', 'Cridge', '719-782-0139', 'scridgex@ftc.gov', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (35, 'Chloette', 'Gluyas', '122-654-8814', 'cgluyasy@4shared.com', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (36, 'Bryn', 'McArthur', '285-363-8858', 'bmcarthurz@umich.edu', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (37, 'Amelita', 'Grenfell', '538-440-8078', 'agrenfell10@discovery.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (38, 'Steward', 'Strother', '333-922-3351', 'sstrother11@youku.com', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (39, 'Jeana', 'Simakov', '324-952-7016', 'jsimakov12@live.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (40, 'Armstrong', 'Baukham', '613-141-1822', 'abaukham13@ox.ac.uk', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (41, 'Helenka', 'Grason', '111-654-4410', 'hgrason14@springer.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (42, 'Augy', 'Gallaher', '896-760-9302', 'agallaher15@bloomberg.com', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (43, 'Glad', 'Gleaves', '262-726-5388', 'ggleaves16@stanford.edu', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (44, 'Dell', 'McCorley', '452-113-8136', 'dmccorley17@google.ca', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (45, 'Theo', 'Baldung', '397-267-9789', 'tbaldung18@barnesandnoble.com', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (46, 'Abelard', 'Beswetherick', '426-301-6883', 'abeswetherick19@de.vu', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (47, 'Roanne', 'Claisse', '477-175-9412', 'rclaisse1a@zdnet.com', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (48, 'Dom', 'Greschke', '240-418-1837', 'dgreschke1b@sciencedaily.com', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (49, 'Elvira', 'Jiricka', '444-884-4759', 'ejiricka1c@virginia.edu', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (50, 'Kenny', 'Luto', '740-891-1468', 'kluto1d@1und1.de', 'Expedition Leader School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (51, 'Karlotte', 'Bahls', '916-602-8446', 'kbahls1e@bbb.org', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (52, 'Ophelie', 'Nann', '712-830-6892', 'onann1f@craigslist.org', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (53, 'Nicoli', 'Stretton', '265-148-9284', 'nstretton1g@squidoo.com', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (54, 'Nikolaos', 'Sansbury', '912-312-6864', 'nsansbury1h@zimbio.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (55, 'Feodor', 'Mowson', '116-414-0612', 'fmowson1i@omniture.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (56, 'Dannel', 'O''Loughlin', '927-362-3632', 'doloughlin1j@guardian.co.uk', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (57, 'Michaelina', 'Belamy', '806-868-5906', 'mbelamy1k@etsy.com', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (58, 'Lynn', 'Pretswell', '234-174-5849', 'lpretswell1l@google.co.jp', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (59, 'Constantine', 'Knightly', '206-291-4223', 'cknightly1m@wsj.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (60, 'Marthe', 'Brosini', '767-923-4947', 'mbrosini1n@1und1.de', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (61, 'Lee', 'Furbank', '513-658-3580', 'lfurbank1o@histats.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (62, 'Holmes', 'Bilbie', '869-172-8438', 'hbilbie1p@drupal.org', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (63, 'Florry', 'Behrend', '344-708-5431', 'fbehrend1q@cdbaby.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (64, 'Wilden', 'Bowfin', '959-350-9055', 'wbowfin1r@marriott.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (65, 'Audrey', 'Martinets', '163-941-7629', 'amartinets1s@nymag.com', 'Expedition Leader School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (66, 'Jeff', 'Mcmanaman', '594-481-4720', 'jmcmanaman1t@yolasite.com', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (67, 'Saxe', 'Garrit', '773-738-1938', 'sgarrit1u@admin.ch', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (68, 'Corbin', 'Lared', '146-853-4153', 'clared1v@dmoz.org', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (69, 'Crysta', 'Deschelle', '454-375-5159', 'cdeschelle1w@gravatar.com', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (70, 'Rabi', 'Kenn', '336-412-0746', 'rkenn1x@qq.com', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (71, 'Gram', 'Minnock', '150-399-3889', 'gminnock1y@google.com.hk', 'Expedition Leader School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (72, 'Barry', 'Lozano', '650-583-8734', 'blozano1z@eventbrite.com', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (73, 'Jennilee', 'Beecker', '596-538-3616', 'jbeecker20@blogger.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (74, 'Reginauld', 'Gervaise', '472-760-3387', 'rgervaise21@newsvine.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (75, 'Ashleigh', 'Dummer', '502-583-6029', 'adummer22@bbc.co.uk', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (76, 'Rhianna', 'Kettles', '153-633-5487', 'rkettles23@de.vu', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (77, 'Anni', 'Bolwell', '207-719-9650', 'abolwell24@pen.io', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (78, 'Kilian', 'Kropach', '334-731-6908', 'kkropach25@psu.edu', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (79, 'Nadiya', 'Hayer', '477-266-4375', 'nhayer26@newyorker.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (80, 'Thane', 'Towlson', '181-611-2784', 'ttowlson27@webeden.co.uk', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (81, 'Emylee', 'Stanyland', '419-546-4468', 'estanyland28@domainmarket.com', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (82, 'Effie', 'Gilhouley', '707-835-0585', 'egilhouley29@tinyurl.com', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (83, 'Sherill', 'Camili', '879-957-6705', 'scamili2a@hud.gov', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (84, 'Lavena', 'Rugge', '131-498-3792', 'lrugge2b@un.org', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (85, 'Staci', 'Martyn', '142-421-2690', 'smartyn2c@livejournal.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (86, 'Ludvig', 'Rosenthal', '846-284-7359', 'lrosenthal2d@last.fm', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (87, 'Noelyn', 'Northin', '627-645-9725', 'nnorthin2e@miibeian.gov.cn', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (88, 'Delmer', 'Scobbie', '575-844-0286', 'dscobbie2f@jimdo.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (89, 'Cristian', 'Ducrow', '757-950-5189', 'cducrow2g@mozilla.org', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (90, 'Samuele', 'Brunicke', '979-329-1933', 'sbrunicke2h@princeton.edu', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (91, 'Wilfrid', 'McDermott-Row', '743-142-1656', 'wmcdermottrow2i@eepurl.com', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (92, 'Carie', 'Shapcott', '379-443-4790', 'cshapcott2j@state.tx.us', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (93, 'Temp', 'Bengochea', '827-788-9652', 'tbengochea2k@fotki.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (94, 'Gustave', 'Blaszczak', '571-791-9891', 'gblaszczak2l@over-blog.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (95, 'Abbot', 'Glenfield', '885-951-5090', 'aglenfield2m@ca.gov', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (96, 'Hamlin', 'Giraudoux', '718-705-4343', 'hgiraudoux2n@elegantthemes.com', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (97, 'Mart', 'Rallin', '246-107-4736', 'mrallin2o@jugem.jp', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (98, 'Charline', 'Asher', '289-370-6143', 'casher2p@google.co.jp', 'World Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (99, 'Nate', 'Kynsey', '987-830-9976', 'nkynsey2q@abc.net.au', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (100, 'Judith', 'Ambresin', '160-960-3307', 'jambresin2r@mysql.com', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (101, 'Wallace', 'Scatchar', '645-241-5333', 'wscatchar2s@google.nl', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (102, 'Deane', 'Beviss', '821-556-5050', 'dbeviss2t@princeton.edu', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (103, 'Pierrette', 'Llywarch', '804-343-5815', 'pllywarch2u@independent.co.uk', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (104, 'Fitzgerald', 'Vaun', '579-951-3890', 'fvaun2v@over-blog.com', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (105, 'Theo', 'Faughey', '882-864-4013', 'tfaughey2w@noaa.gov', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (106, 'Clementina', 'Larcher', '144-647-6153', 'clarcher2x@creativecommons.org', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (107, 'Mead', 'Cavozzi', '193-499-5491', 'mcavozzi2y@pen.io', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (108, 'Nicholas', 'Spiring', '210-485-8990', 'nspiring2z@wikimedia.org', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (109, 'Claiborne', 'Batt', '104-353-3053', 'cbatt30@trellian.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (110, 'Feodor', 'Charleston', '495-239-7314', 'fcharleston31@cnet.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (111, 'Winona', 'Postlethwaite', '898-508-5590', 'wpostlethwaite32@answers.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (112, 'Janeczka', 'Vanyushin', '227-319-7116', 'jvanyushin33@rakuten.co.jp', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (113, 'Fredia', 'Breukelman', '484-359-5341', 'fbreukelman34@auda.org.au', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (114, 'Ingeberg', 'Baiden', '295-650-2665', 'ibaiden35@cbc.ca', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (115, 'Cissiee', 'Haswall', '652-256-2923', 'chaswall36@discovery.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (116, 'Ralf', 'Yelyashev', '616-139-6345', 'ryelyashev37@huffingtonpost.com', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (117, 'Dara', 'Twaite', '852-405-7326', 'dtwaite38@lulu.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (118, 'Evin', 'Tubble', '714-267-0680', 'etubble39@drupal.org', 'Modern Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (119, 'Mona', 'Falk', '212-673-1678', 'mfalk3a@arizona.edu', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (120, 'Conant', 'Gethyn', '738-868-5648', 'cgethyn3b@zimbio.com', 'Landmark Interpretation Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (121, 'Mord', 'McFadin', '261-472-6097', 'mmcfadin3c@histats.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (122, 'Emmalee', 'Hadgraft', '305-957-8770', 'ehadgraft3d@histats.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (123, 'Woodrow', 'Sharratt', '900-276-6510', 'wsharratt3e@mysql.com', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (124, 'Pauli', 'Cason', '117-959-1024', 'pcason3f@salon.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (125, 'Toby', 'Cummins', '482-164-1972', 'tcummins3g@npr.org', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (126, 'Valentine', 'Elkins', '504-283-7063', 'velkins3h@umich.edu', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (127, 'Aldin', 'Farncombe', '368-493-7194', 'afarncombe3i@histats.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (128, 'Aeriell', 'Douglass', '634-758-7007', 'adouglass3j@noaa.gov', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (129, 'Christoforo', 'Rennison', '703-876-3523', 'crennison3k@youtu.be', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (130, 'Melamie', 'Pfleger', '830-417-2255', 'mpfleger3l@wired.com', 'Landmark Interpretation Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (131, 'Cinnamon', 'Rainforth', '830-144-4329', 'crainforth3m@ft.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (132, 'Alfie', 'Seiler', '473-160-9728', 'aseiler3n@cloudflare.com', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (133, 'Barbie', 'Kienlein', '664-671-0004', 'bkienlein3o@hao123.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (134, 'Melamie', 'Fozard', '796-619-1316', 'mfozard3p@businessweek.com', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (135, 'Jory', 'Hartwright', '846-710-5001', 'jhartwright3q@bluehost.com', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (136, 'Maximilian', 'Yetts', '566-381-3787', 'myetts3r@wikipedia.org', 'World Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (137, 'Clarissa', 'Verralls', '660-282-9597', 'cverralls3s@hao123.com', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (138, 'Harley', 'Blackboro', '274-282-5122', 'hblackboro3t@discovery.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (139, 'Lani', 'Eykelhof', '618-195-3567', 'leykelhof3u@ocn.ne.jp', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (140, 'Jenifer', 'Urlich', '718-760-9872', 'jurlich3v@epa.gov', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (141, 'Alta', 'Darleston', '357-199-1264', 'adarleston3w@soup.io', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (142, 'Lucias', 'Saffen', '580-602-2377', 'lsaffen3x@goo.ne.jp', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (143, 'Arabele', 'Nisen', '456-454-4946', 'anisen3y@oracle.com', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (144, 'Carina', 'Boleyn', '274-918-4495', 'cboleyn3z@washington.edu', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (145, 'De witt', 'Klugman', '387-265-2470', 'dklugman40@tumblr.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (146, 'Natka', 'Maggiori', '735-357-0172', 'nmaggiori41@gizmodo.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (147, 'Von', 'Anthoney', '472-787-8391', 'vanthoney42@google.co.jp', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (148, 'Hermione', 'Spinelli', '948-522-5598', 'hspinelli43@cornell.edu', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (149, 'Keri', 'Upshall', '869-516-5630', 'kupshall44@theglobeandmail.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (150, 'Glenda', 'Loughrey', '575-260-4345', 'gloughrey45@google.ca', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (151, 'Valeda', 'Moncrefe', '696-669-0407', 'vmoncrefe46@ycombinator.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (152, 'Jorrie', 'O''Carney', '380-188-6940', 'jocarney47@fastcompany.com', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (153, 'Cassi', 'Phythien', '250-807-4225', 'cphythien48@blinklist.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (154, 'Crista', 'Schmidt', '864-631-6832', 'cschmidt49@google.it', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (155, 'Issie', 'Humblestone', '853-368-5248', 'ihumblestone4a@google.nl', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (156, 'Emmott', 'Rother', '274-959-1345', 'erother4b@netscape.com', 'Modern Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (157, 'Obidiah', 'Abelovitz', '114-520-6346', 'oabelovitz4c@google.co.jp', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (158, 'Kennith', 'Tilmouth', '253-852-9971', 'ktilmouth4d@icq.com', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (159, 'Arron', 'Mallabar', '231-103-6089', 'amallabar4e@sohu.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (160, 'Ailyn', 'Arrigucci', '735-209-5029', 'aarrigucci4f@lycos.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (161, 'Liam', 'Shafto', '476-391-8613', 'lshafto4g@cbc.ca', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (162, 'Vale', 'Ghiotto', '501-761-5628', 'vghiotto4h@reuters.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (163, 'Hanni', 'Aubrun', '872-950-7527', 'haubrun4i@weebly.com', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (164, 'Pen', 'Bowman', '314-259-4486', 'pbowman4j@a8.net', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (165, 'Hervey', 'Wadhams', '636-637-8455', 'hwadhams4k@privacy.gov.au', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (166, 'Elora', 'Howick', '335-544-3734', 'ehowick4l@rambler.ru', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (167, 'Anatollo', 'Jennaroy', '932-331-7452', 'ajennaroy4m@symantec.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (168, 'Chane', 'Hyndley', '873-287-6682', 'chyndley4n@google.ca', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (169, 'Tanya', 'Whodcoat', '133-340-6264', 'twhodcoat4o@hao123.com', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (170, 'Violetta', 'Vercruysse', '871-865-8302', 'vvercruysse4p@geocities.jp', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (171, 'Edythe', 'Layfield', '967-870-8517', 'elayfield4q@google.nl', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (172, 'Car', 'Bigglestone', '816-214-4427', 'cbigglestone4r@blogspot.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (173, 'Arlinda', 'Brushneen', '204-193-4355', 'abrushneen4s@t-online.de', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (174, 'Siana', 'Polhill', '580-953-0071', 'spolhill4t@independent.co.uk', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (175, 'Belvia', 'Rappoport', '531-359-1360', 'brappoport4u@mapy.cz', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (176, 'Kim', 'Guirardin', '788-962-9414', 'kguirardin4v@nasa.gov', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (177, 'Bettina', 'Tripp', '328-592-6969', 'btripp4w@twitpic.com', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (178, 'Kristina', 'Campes', '632-599-8753', 'kcampes4x@drupal.org', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (179, 'Ingaberg', 'Forsdike', '497-469-6309', 'iforsdike4y@tuttocitta.it', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (180, 'Ram', 'Vinas', '776-599-7474', 'rvinas4z@hostgator.com', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (181, 'Fiann', 'Blasi', '681-265-2341', 'fblasi50@hubpages.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (182, 'Isacco', 'Scoggan', '593-211-1032', 'iscoggan51@ucsd.edu', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (183, 'Perry', 'Melledy', '344-497-8731', 'pmelledy52@ehow.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (184, 'Bobby', 'Goldwater', '150-127-0855', 'bgoldwater53@tumblr.com', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (185, 'Samson', 'Sibary', '322-357-8972', 'ssibary54@sakura.ne.jp', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (186, 'Rafaelia', 'Mattin', '480-757-0741', 'rmattin55@patch.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (187, 'Padraic', 'Satterlee', '658-494-1587', 'psatterlee56@list-manage.com', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (188, 'Farris', 'Towsie', '650-950-1433', 'ftowsie57@youtu.be', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (189, 'Anstice', 'Pardy', '562-264-2726', 'apardy58@nymag.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (190, 'Warden', 'Dodding', '785-623-5950', 'wdodding59@ox.ac.uk', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (191, 'Fiona', 'Howe', '401-925-7534', 'fhowe5a@canalblog.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (192, 'Anni', 'Hallen', '995-805-7652', 'ahallen5b@umn.edu', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (193, 'Dana', 'Blaske', '474-752-3155', 'dblaske5c@taobao.com', 'World Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (194, 'Leroy', 'Gully', '550-967-1760', 'lgully5d@youtube.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (195, 'Hadlee', 'Charlton', '448-720-5537', 'hcharlton5e@people.com.cn', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (196, 'Herculie', 'Jacquemard', '508-286-6057', 'hjacquemard5f@statcounter.com', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (197, 'Rubi', 'Fernier', '698-160-6985', 'rfernier5g@berkeley.edu', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (198, 'Kimmy', 'Winning', '594-108-5315', 'kwinning5h@bloomberg.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (199, 'Elfreda', 'Coathup', '272-589-6517', 'ecoathup5i@paginegialle.it', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (200, 'Iorgos', 'Sellman', '605-621-2211', 'isellman5j@yolasite.com', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (201, 'Corrine', 'Do Rosario', '505-546-5338', 'cdorosario5k@ted.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (202, 'Millie', 'Fricker', '668-953-2727', 'mfricker5l@oaic.gov.au', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (203, 'Ethyl', 'Miskelly', '262-668-2740', 'emiskelly5m@bing.com', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (204, 'Mabelle', 'Freer', '233-362-4163', 'mfreer5n@artisteer.com', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (205, 'Prue', 'Easen', '412-775-6087', 'peasen5o@cocolog-nifty.com', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (206, 'Roxy', 'Parmley', '827-280-4353', 'rparmley5p@pagesperso-orange.fr', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (207, 'Ebony', 'Marval', '311-879-9376', 'emarval5q@intel.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (208, 'Lynette', 'Farish', '942-781-2059', 'lfarish5r@ftc.gov', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (209, 'Zollie', 'Bilbrey', '950-137-9364', 'zbilbrey5s@alibaba.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (210, 'Malissia', 'Meritt', '537-137-2548', 'mmeritt5t@goo.gl', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (211, 'Sapphire', 'Jereatt', '724-209-1147', 'sjereatt5u@cloudflare.com', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (212, 'Ignacio', 'Svanetti', '340-655-2722', 'isvanetti5v@barnesandnoble.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (213, 'Ann', 'Snassell', '530-319-6710', 'asnassell5w@walmart.com', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (214, 'Domenico', 'Jiru', '352-573-8187', 'djiru5x@usnews.com', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (215, 'Essa', 'Hayselden', '163-451-4668', 'ehayselden5y@wikipedia.org', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (216, 'Juanita', 'Gammill', '378-140-4157', 'jgammill5z@creativecommons.org', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (217, 'Bee', 'Hoyte', '694-927-0331', 'bhoyte60@mayoclinic.com', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (218, 'Anita', 'Fateley', '799-212-6304', 'afateley61@cafepress.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (219, 'Engracia', 'Harwin', '290-840-0614', 'eharwin62@miibeian.gov.cn', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (220, 'Thorsten', 'Solomon', '458-683-2463', 'tsolomon63@bing.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (221, 'Franz', 'Poundsford', '193-421-3431', 'fpoundsford64@foxnews.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (222, 'Lucina', 'Farnfield', '636-943-7677', 'lfarnfield65@indiatimes.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (223, 'Barbabra', 'Adamthwaite', '656-590-7301', 'badamthwaite66@webeden.co.uk', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (224, 'Perla', 'Salvin', '430-196-8358', 'psalvin67@tripadvisor.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (225, 'Rubie', 'Reddings', '164-546-5484', 'rreddings68@icio.us', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (226, 'Christy', 'Bachshell', '526-487-8838', 'cbachshell69@plala.or.jp', 'Metropolitan Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (227, 'Karlyn', 'Sawkins', '395-780-6904', 'ksawkins6a@japanpost.jp', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (228, 'Klement', 'Corriea', '585-262-0835', 'kcorriea6b@alexa.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (229, 'Wanids', 'Thackham', '966-371-9920', 'wthackham6c@goodreads.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (230, 'Bank', 'Wolfenden', '850-942-4826', 'bwolfenden6d@lulu.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (231, 'Maxwell', 'Dowbiggin', '445-905-0684', 'mdowbiggin6e@economist.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (232, 'Gertie', 'Aaronson', '370-207-4618', 'gaaronson6f@t.co', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (233, 'Giff', 'Rudge', '493-502-3229', 'grudge6g@economist.com', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (234, 'Cob', 'Kenshole', '753-642-3747', 'ckenshole6h@nymag.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (235, 'Elysha', 'Smethurst', '512-382-7672', 'esmethurst6i@wsj.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (236, 'Durward', 'Peckett', '843-844-5144', 'dpeckett6j@springer.com', 'National Park Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (237, 'Wolfgang', 'Astupenas', '678-458-8835', 'wastupenas6k@aol.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (238, 'Shea', 'McGiveen', '701-115-9198', 'smcgiveen6l@blogger.com', 'Landmark Interpretation Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (239, 'Toinette', 'Oglethorpe', '628-822-4221', 'toglethorpe6m@cocolog-nifty.com', 'World Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (240, 'Dorothea', 'Christescu', '919-571-7814', 'dchristescu6n@ihg.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (241, 'Tomkin', 'Botler', '183-633-9623', 'tbotler6o@eepurl.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (242, 'Carmelina', 'Sellors', '794-210-9503', 'csellors6p@joomla.org', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (243, 'Bryn', 'Geach', '780-536-5636', 'bgeach6q@wunderground.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (244, 'Kerry', 'Carmen', '479-974-9376', 'kcarmen6r@cnn.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (245, 'Herbie', 'Sotheron', '107-984-8080', 'hsotheron6s@opera.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (246, 'Stacia', 'Adiscot', '217-250-9606', 'sadiscot6t@pbs.org', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (247, 'Thaine', 'Mulliss', '871-607-6863', 'tmulliss6u@goo.ne.jp', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (248, 'Elaine', 'Bebis', '924-303-7951', 'ebebis6v@oracle.com', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (249, 'Ozzie', 'Jickles', '120-464-3777', 'ojickles6w@fda.gov', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (250, 'Homerus', 'Iannetti', '113-776-5644', 'hiannetti6x@bbb.org', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (251, 'Joletta', 'Stennard', '990-925-7850', 'jstennard6y@hostgator.com', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (252, 'Opalina', 'Arnow', '433-169-5400', 'oarnow6z@yellowpages.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (253, 'Agnella', 'Scapens', '281-942-1213', 'ascapens70@spotify.com', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (254, 'Betteann', 'Siely', '317-887-2413', 'bsiely71@salon.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (255, 'Trey', 'Primak', '725-304-0620', 'tprimak72@eventbrite.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (256, 'Jarrid', 'Smickle', '772-535-4500', 'jsmickle73@dedecms.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (257, 'Ellswerth', 'Bomfield', '434-841-3972', 'ebomfield74@elegantthemes.com', 'Metropolitan Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (258, 'Domenico', 'Paoletti', '858-170-8381', 'dpaoletti75@samsung.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (259, 'Kellia', 'Renad', '638-913-3094', 'krenad76@google.co.uk', 'Landmark Interpretation Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (260, 'Patrice', 'Gipp', '388-269-1801', 'pgipp77@dell.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (261, 'Amy', 'Deniskevich', '978-771-6504', 'adeniskevich78@i2i.jp', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (262, 'Aguste', 'Ceyssen', '816-570-6941', 'aceyssen79@delicious.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (263, 'Kevan', 'Cornall', '125-989-8101', 'kcornall7a@godaddy.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (264, 'Issi', 'Di Biagio', '113-940-3805', 'idibiagio7b@qq.com', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (265, 'Giacopo', 'Brekonridge', '757-914-8234', 'gbrekonridge7c@home.pl', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (266, 'Granny', 'Brierly', '530-377-6235', 'gbrierly7d@auda.org.au', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (267, 'Adair', 'Kirstein', '927-183-6612', 'akirstein7e@wikipedia.org', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (268, 'Johny', 'Lemar', '221-287-8740', 'jlemar7f@ox.ac.uk', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (269, 'Viv', 'Fearns', '584-663-3188', 'vfearns7g@archive.org', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (270, 'Celestine', 'MacAllister', '194-885-1492', 'cmacallister7h@privacy.gov.au', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (271, 'Dulcinea', 'Gallico', '617-742-5948', 'dgallico7i@google.fr', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (272, 'Adrianne', 'Viger', '733-212-3714', 'aviger7j@webmd.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (273, 'Mora', 'Browse', '930-874-0916', 'mbrowse7k@engadget.com', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (274, 'Camille', 'Maunder', '806-279-8860', 'cmaunder7l@typepad.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (275, 'Demetrius', 'MacHoste', '118-622-4969', 'dmachoste7m@slideshare.net', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (276, 'Rolland', 'Snipe', '159-990-5531', 'rsnipe7n@exblog.jp', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (277, 'Thia', 'Heaslip', '197-413-6139', 'theaslip7o@gnu.org', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (278, 'Isa', 'Rugg', '109-830-4112', 'irugg7p@prlog.org', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (279, 'Bidget', 'Boldt', '850-948-5917', 'bboldt7q@techcrunch.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (280, 'Rube', 'Ivamy', '637-735-1940', 'rivamy7r@360.cn', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (281, 'Phoebe', 'Flaverty', '193-395-6970', 'pflaverty7s@google.fr', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (282, 'Lanae', 'Clemett', '918-250-3568', 'lclemett7t@noaa.gov', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (283, 'Bartel', 'Duell', '469-903-2565', 'bduell7u@epa.gov', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (284, 'Cherrita', 'McAlester', '515-652-7584', 'cmcalester7v@opensource.org', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (285, 'Cordell', 'Lemm', '772-413-7405', 'clemm7w@epa.gov', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (286, 'Adan', 'Jacobovitz', '910-227-2339', 'ajacobovitz7x@fc2.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (287, 'Ana', 'Iggalden', '576-917-7995', 'aiggalden7y@loc.gov', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (288, 'Swen', 'Bolles', '913-717-1971', 'sbolles7z@sakura.ne.jp', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (289, 'Rene', 'Gaffney', '397-702-9213', 'rgaffney80@cdc.gov', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (290, 'Neils', 'Bernadot', '107-808-9068', 'nbernadot81@de.vu', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (291, 'Nike', 'Kamiyama', '404-661-5705', 'nkamiyama82@pinterest.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (292, 'Noll', 'Vassie', '107-491-2532', 'nvassie83@cdc.gov', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (293, 'Joanne', 'Brothers', '285-321-7031', 'jbrothers84@umn.edu', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (294, 'Lev', 'Fox', '764-624-7990', 'lfox85@163.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (295, 'Helen-elizabeth', 'Keston', '163-721-9304', 'hkeston86@unicef.org', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (296, 'Colleen', 'Frede', '361-157-1550', 'cfrede87@wired.com', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (297, 'Irving', 'Beynke', '702-664-5370', 'ibeynke88@engadget.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (298, 'Rianon', 'Keave', '768-337-5558', 'rkeave89@cmu.edu', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (299, 'Mirelle', 'Heisham', '207-567-1594', 'mheisham8a@whitehouse.gov', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (300, 'Tally', 'Schlagman', '907-901-0174', 'tschlagman8b@squarespace.com', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (301, 'Bryn', 'Kelwick', '655-237-7637', 'bkelwick8c@noaa.gov', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (302, 'Hayley', 'Swannie', '710-922-6570', 'hswannie8d@eepurl.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (303, 'Charmain', 'Bussey', '397-184-7009', 'cbussey8e@noaa.gov', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (304, 'Judith', 'Ayto', '489-667-6957', 'jayto8f@google.es', 'Metropolitan Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (305, 'Darnall', 'Weal', '680-183-4133', 'dweal8g@vistaprint.com', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (306, 'Jens', 'Hawtrey', '663-627-8278', 'jhawtrey8h@timesonline.co.uk', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (307, 'Greta', 'L''Amie', '653-706-9055', 'glamie8i@eventbrite.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (308, 'Angil', 'Walkowski', '499-529-5389', 'awalkowski8j@delicious.com', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (309, 'Sullivan', 'Reef', '526-790-8964', 'sreef8k@ed.gov', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (310, 'Hersch', 'Krishtopaittis', '458-192-9622', 'hkrishtopaittis8l@paginegialle.it', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (311, 'Sheeree', 'Seys', '299-247-8211', 'sseys8m@dagondesign.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (312, 'Anders', 'Crouse', '680-110-3671', 'acrouse8n@addthis.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (313, 'Peterus', 'Cator', '666-162-6373', 'pcator8o@ycombinator.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (314, 'Josefa', 'Larimer', '680-586-5512', 'jlarimer8p@goodreads.com', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (315, 'Sergio', 'Glowacki', '581-312-5075', 'sglowacki8q@europa.eu', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (316, 'Elmer', 'Fozzard', '534-582-2742', 'efozzard8r@intel.com', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (317, 'Susana', 'Bogey', '503-693-9076', 'sbogey8s@behance.net', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (318, 'Renell', 'Beloe', '228-360-6042', 'rbeloe8t@exblog.jp', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (319, 'Antonina', 'Michelin', '803-928-9311', 'amichelin8u@cisco.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (320, 'Freeland', 'Matten', '274-421-9555', 'fmatten8v@woothemes.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (321, 'Lemmy', 'Jermey', '913-458-9939', 'ljermey8w@cloudflare.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (322, 'Amberly', 'Jeremiah', '243-914-3048', 'ajeremiah8x@fc2.com', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (323, 'Valentine', 'Odgers', '363-234-2892', 'vodgers8y@mozilla.com', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (324, 'Jacquelynn', 'Pudden', '136-124-6213', 'jpudden8z@amazon.com', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (325, 'Garrick', 'Klimsch', '209-694-7161', 'gklimsch90@furl.net', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (326, 'Dewey', 'Loughan', '441-438-8861', 'dloughan91@studiopress.com', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (327, 'Emmalyn', 'Matuschek', '786-564-1252', 'ematuschek92@kickstarter.com', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (328, 'Nancee', 'Ledekker', '335-744-2621', 'nledekker93@epa.gov', 'Cultural Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (329, 'Maddalena', 'Thorrold', '598-189-9918', 'mthorrold94@who.int', 'National Park Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (330, 'Brittan', 'Vevers', '136-564-9777', 'bvevers95@shop-pro.jp', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (331, 'Douglas', 'Hubane', '602-799-8203', 'dhubane96@salon.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (332, 'Candida', 'Lean', '483-624-7316', 'clean97@e-recht24.de', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (333, 'Martguerita', 'Rockhall', '895-282-2394', 'mrockhall98@umn.edu', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (334, 'Elnar', 'Reuss', '849-713-5847', 'ereuss99@weibo.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (335, 'Barbabas', 'Iacopini', '202-955-7190', 'biacopini9a@fastcompany.com', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (336, 'Davidde', 'Lilloe', '777-302-2938', 'dlilloe9b@salon.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (337, 'Betti', 'Rustedge', '535-428-0304', 'brustedge9c@t.co', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (338, 'Brittan', 'Ingerson', '682-421-1541', 'bingerson9d@hexun.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (339, 'Casper', 'Byles', '289-875-1188', 'cbyles9e@hao123.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (340, 'Harlie', 'Harrema', '746-837-4061', 'hharrema9f@sourceforge.net', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (341, 'Connor', 'Pentecust', '396-552-1254', 'cpentecust9g@blogtalkradio.com', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (342, 'Domenic', 'Corbally', '698-138-1820', 'dcorbally9h@mozilla.org', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (343, 'Madonna', 'Kalisch', '911-722-7105', 'mkalisch9i@youtube.com', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (344, 'Lamond', 'Fluit', '361-652-1006', 'lfluit9j@quantcast.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (345, 'Karlens', 'Noli', '316-960-8308', 'knoli9k@edublogs.org', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (346, 'Sunny', 'Nanetti', '523-995-7755', 'snanetti9l@jigsy.com', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (347, 'Basilio', 'Pretti', '481-886-6964', 'bpretti9m@behance.net', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (348, 'Dorris', 'Arnison', '282-439-7185', 'darnison9n@blogger.com', 'Professional Travel School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (349, 'Darci', 'Thames', '865-378-4884', 'dthames9o@paypal.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (350, 'Urbain', 'Guile', '212-146-0279', 'uguile9p@youku.com', 'Modern Tourism Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (351, 'Edy', 'Bris', '399-954-5602', 'ebris9q@issuu.com', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (352, 'Micky', 'Thornber', '462-401-3548', 'mthornber9r@xrea.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (353, 'Kaitlin', 'Cottom', '256-857-0364', 'kcottom9s@360.cn', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (354, 'Marci', 'Coombs', '704-468-2999', 'mcoombs9t@jigsy.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (355, 'Moses', 'Tipper', '126-480-2066', 'mtipper9u@chron.com', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (356, 'Sydel', 'Vickar', '897-755-4406', 'svickar9v@uiuc.edu', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (357, 'Jo-anne', 'Cassell', '318-463-8746', 'jcassell9w@howstuffworks.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (358, 'Annalee', 'Blissett', '353-535-2834', 'ablissett9x@webmd.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (359, 'Costanza', 'Duckels', '265-471-7247', 'cduckels9y@gizmodo.com', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (360, 'Freddie', 'Hercock', '809-194-2066', 'fhercock9z@gravatar.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (361, 'Jared', 'Fetherston', '340-667-6206', 'jfetherstona0@digg.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (362, 'Amby', 'Cantu', '179-564-9961', 'acantua1@google.ca', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (363, 'Alan', 'Foulis', '140-845-6465', 'afoulisa2@unc.edu', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (364, 'Shelley', 'Widdowes', '474-232-5070', 'swiddowesa3@fc2.com', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (365, 'Lydie', 'Ofer', '130-620-6114', 'lofera4@hao123.com', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (366, 'Fredelia', 'Pester', '455-439-4787', 'fpestera5@deliciousdays.com', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (367, 'Abdel', 'Kinney', '610-963-7925', 'akinneya6@prnewswire.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (368, 'Leighton', 'Hay', '672-164-7088', 'lhaya7@simplemachines.org', 'Metropolitan Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (369, 'Flss', 'Monnery', '652-528-8589', 'fmonnerya8@scribd.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (370, 'Nealson', 'Allcroft', '612-407-8266', 'nallcrofta9@woothemes.com', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (371, 'Barbie', 'Paver', '508-399-1683', 'bpaveraa@alexa.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (372, 'Aloisia', 'Birney', '338-456-6235', 'abirneyab@seattletimes.com', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (373, 'Marla', 'Sperring', '204-304-6110', 'msperringac@photobucket.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (374, 'Tyler', 'Lifton', '784-194-2475', 'tliftonad@rambler.ru', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (375, 'Dinah', 'Shurey', '917-813-9369', 'dshureyae@fda.gov', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (376, 'Hazlett', 'Storie', '689-549-1783', 'hstorieaf@reuters.com', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (377, 'Averell', 'Berriball', '335-713-6773', 'aberriballag@typepad.com', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (378, 'Guenevere', 'Elks', '336-968-4480', 'gelksah@ask.com', 'World Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (379, 'Syd', 'Lottrington', '613-521-9521', 'slottringtonai@sun.com', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (380, 'Glyn', 'Beernaert', '268-321-0614', 'gbeernaertaj@vk.com', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (381, 'Felicle', 'Billie', '998-272-8885', 'fbillieak@gnu.org', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (382, 'Theo', 'Gerson', '371-156-6041', 'tgersonal@prnewswire.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (383, 'Wolfgang', 'Gatus', '157-245-1258', 'wgatusam@ameblo.jp', 'Insight Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (384, 'Mathian', 'Millsom', '359-371-2778', 'mmillsoman@biblegateway.com', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (385, 'Tudor', 'Wythe', '889-701-8830', 'twytheao@tuttocitta.it', 'Trekking Instructor Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (386, 'Marylinda', 'Manning', '472-311-7211', 'mmanningap@aboutads.info', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (387, 'Salomone', 'Knight', '730-490-0025', 'sknightaq@clickbank.net', 'Travel Master Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (388, 'Gillie', 'Castro', '220-915-7145', 'gcastroar@buzzfeed.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (389, 'Tito', 'Hudspith', '361-595-8703', 'thudspithas@theatlantic.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (390, 'Rubin', 'Huffey', '181-893-8424', 'rhuffeyat@ted.com', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (391, 'Keary', 'Thompson', '413-786-2116', 'kthompsonau@cisco.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (392, 'Tripp', 'Twelftree', '527-241-9550', 'ttwelftreeav@delicious.com', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (393, 'Hewett', 'Arminger', '440-139-6260', 'harmingeraw@home.pl', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (394, 'Matthaeus', 'Dolphin', '820-556-8121', 'mdolphinax@altervista.org', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (395, 'Constantine', 'Petzold', '499-612-2636', 'cpetzolday@zimbio.com', 'Coastal Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (396, 'Fern', 'Wetton', '610-927-6861', 'fwettonaz@odnoklassniki.ru', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (397, 'Jeffie', 'Domico', '382-690-4440', 'jdomicob0@bluehost.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (398, 'Bamby', 'De Vere', '632-980-3794', 'bdevereb1@usgs.gov', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (399, 'Georgette', 'Reedman', '448-609-1982', 'greedmanb2@instagram.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (400, 'Chaunce', 'Edmons', '149-890-1024', 'cedmonsb3@angelfire.com', 'Safari Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (401, 'Berky', 'Calabry', '876-404-3245', 'bcalabryb4@feedburner.com', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (402, 'Gaultiero', 'Barracks', '882-465-7031', 'gbarracksb5@paypal.com', 'Horizon Leadership College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (403, 'Tiena', 'Magrannell', '512-345-4341', 'tmagrannellb6@amazonaws.com', 'Trailblazer Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (404, 'Gallard', 'Thackray', '895-445-8650', 'gthackrayb7@amazon.de', 'Nature Discovery College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (405, 'Kaitlin', 'Brayne', '437-173-5985', 'kbrayneb8@cpanel.net', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (406, 'Micky', 'Painswick', '102-252-9980', 'mpainswickb9@buzzfeed.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (407, 'Lew', 'Treagus', '315-262-7831', 'ltreagusba@vkontakte.ru', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (408, 'Briggs', 'Winchcombe', '735-601-4895', 'bwinchcombebb@hostgator.com', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (409, 'Brittne', 'Truitt', '844-983-4650', 'btruittbc@harvard.edu', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (410, 'Tory', 'Brumby', '538-897-6590', 'tbrumbybd@time.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (411, 'Bartholomew', 'Leveret', '738-222-6096', 'bleveretbe@adobe.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (412, 'Billie', 'Prestie', '895-411-2284', 'bprestiebf@businessinsider.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (413, 'Finlay', 'Cufflin', '402-458-4889', 'fcufflinbg@w3.org', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (414, 'Julissa', 'Danet', '418-254-1948', 'jdanetbh@abc.net.au', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (415, 'Jehu', 'Soloway', '166-119-0385', 'jsolowaybi@yolasite.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (416, 'Louis', 'Snarr', '318-952-8776', 'lsnarrbj@hud.gov', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (417, 'Balduin', 'Nodin', '121-625-7940', 'bnodinbk@sphinn.com', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (418, 'Albie', 'Foldes', '502-888-5124', 'afoldesbl@chronoengine.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (419, 'Brittney', 'Moorcraft', '968-375-0285', 'bmoorcraftbm@hexun.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (420, 'Turner', 'Gaddie', '932-115-3223', 'tgaddiebn@sogou.com', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (421, 'Ronald', 'Trousdale', '149-598-0680', 'rtrousdalebo@icio.us', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (422, 'Emlynn', 'Bilam', '191-138-4485', 'ebilambp@google.ru', 'Urban Scouter Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (423, 'Davidde', 'Abramov', '534-660-2872', 'dabramovbq@hud.gov', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (424, 'Addie', 'Copplestone', '954-274-8215', 'acopplestonebr@theatlantic.com', 'Summit Leadership School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (425, 'Annmaria', 'Priver', '130-424-5729', 'apriverbs@mail.ru', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (426, 'Dorry', 'Ticic', '899-997-0070', 'dticicbt@posterous.com', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (427, 'Vilma', 'Kimber', '603-370-3340', 'vkimberbu@telegraph.co.uk', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (428, 'Jere', 'Peckham', '326-771-1942', 'jpeckhambv@e-recht24.de', 'Urban Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (429, 'Cairistiona', 'Labba', '514-428-1963', 'clabbabw@omniture.com', 'Adventure Leadership Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (430, 'Dorotea', 'Dunphy', '691-521-0351', 'ddunphybx@artisteer.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (431, 'Brinn', 'Whetson', '632-721-5406', 'bwhetsonby@livejournal.com', 'Wayfinder Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (432, 'Evin', 'Nathan', '579-489-7883', 'enathanbz@hostgator.com', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (433, 'Gwenni', 'Camble', '855-251-2315', 'gcamblec0@youtu.be', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (434, 'Emmaline', 'Zecchini', '717-587-6959', 'ezecchinic1@latimes.com', 'National Park Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (435, 'Kaleb', 'Spadeck', '767-363-9567', 'kspadeckc2@clickbank.net', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (436, 'Tam', 'Carnegy', '159-266-5933', 'tcarnegyc3@loc.gov', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (437, 'Tabor', 'Colby', '983-919-7539', 'tcolbyc4@princeton.edu', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (438, 'Nichole', 'Yosevitz', '820-599-0832', 'nyosevitzc5@ebay.com', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (439, 'Stephi', 'Cribbin', '851-511-2129', 'scribbinc6@apple.com', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (440, 'Ryan', 'Guichard', '214-615-7211', 'rguichardc7@wired.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (441, 'Sybila', 'Wringe', '679-341-9962', 'swringec8@squarespace.com', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (442, 'Julietta', 'Vankov', '879-700-2555', 'jvankovc9@ask.com', 'International Tour Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (443, 'Tabbatha', 'Dowda', '206-799-1005', 'tdowdaca@free.fr', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (444, 'Caril', 'Gye', '866-493-7098', 'cgyecb@nytimes.com', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (445, 'Felipe', 'Saterthwait', '213-443-2245', 'fsaterthwaitcc@etsy.com', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (446, 'Lindsey', 'Meharg', '253-732-0364', 'lmehargcd@artisteer.com', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (447, 'Gael', 'Sandels', '844-420-1118', 'gsandelsce@spotify.com', 'Landmark Interpretation Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (448, 'Leicester', 'Casbon', '439-957-4831', 'lcasboncf@apache.org', 'Narrative Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (449, 'Jillene', 'Mitrovic', '910-580-5526', 'jmitroviccg@state.gov', 'Wilderness Guide Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (450, 'Finn', 'Heaton', '742-613-2380', 'fheatonch@upenn.edu', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (451, 'Stacee', 'Braferton', '585-285-9660', 'sbrafertonci@opera.com', 'Travel & Tourism Tech');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (452, 'Diann', 'Bambrough', '419-631-8344', 'dbambroughcj@bluehost.com', 'Metropolitan Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (453, 'Griselda', 'Archambault', '259-566-8143', 'garchambaultck@bbc.co.uk', 'Heritage Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (454, 'Wally', 'Fitzmaurice', '392-127-1490', 'wfitzmauricecl@hostgator.com', 'Outdoor Education Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (455, 'Eldredge', 'Oen', '635-605-0968', 'eoencm@pagesperso-orange.fr', 'World Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (456, 'Reynolds', 'Riccard', '786-564-5052', 'rriccardcn@sbwire.com', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (457, 'Janek', 'Rothert', '922-288-9832', 'jrothertco@salon.com', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (458, 'Eleanore', 'Sands', '752-465-1470', 'esandscp@bloglines.com', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (459, 'Rogerio', 'Sissens', '469-529-6046', 'rsissenscq@digg.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (460, 'Prentiss', 'Derrick', '742-444-9924', 'pderrickcr@nps.gov', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (461, 'Lil', 'Guilloux', '725-372-9868', 'lguillouxcs@seattletimes.com', 'National Park Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (462, 'Ian', 'Pearcy', '912-870-0072', 'ipearcyct@slate.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (463, 'Danie', 'Manus', '302-424-2029', 'dmanuscu@blogtalkradio.com', 'Historical Path Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (464, 'Maxie', 'Gross', '677-736-4265', 'mgrosscv@phoca.cz', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (465, 'Thoma', 'Thirtle', '757-135-3921', 'tthirtlecw@dmoz.org', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (466, 'Seline', 'Bendley', '654-950-1012', 'sbendleycx@dagondesign.com', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (467, 'Roy', 'Coxwell', '949-718-6985', 'rcoxwellcy@arstechnica.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (468, 'Tulley', 'Iacovaccio', '634-424-7253', 'tiacovacciocz@thetimes.co.uk', 'Site Specialist Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (469, 'Izaak', 'Hollyland', '466-651-2998', 'ihollylandd0@reuters.com', 'Global Trek Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (470, 'Gibby', 'Chiddy', '446-509-9924', 'gchiddyd1@behance.net', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (471, 'Remus', 'Crimin', '403-708-0896', 'rcrimind2@time.com', 'Field Guide College');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (472, 'Wendeline', 'Waddam', '516-698-7645', 'wwaddamd3@latimes.com', 'Ancient History Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (473, 'Dannye', 'Hodgets', '227-981-5252', 'dhodgetsd4@ihg.com', 'Global Adventure School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (474, 'Darn', 'Conry', '138-505-0480', 'dconryd5@admin.ch', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (475, 'Johanna', 'William', '778-808-9391', 'jwilliamd6@walmart.com', 'Navigator Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (476, 'Ludvig', 'Moyers', '639-246-1920', 'lmoyersd7@springer.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (477, 'Rorie', 'Heck', '104-458-2948', 'rheckd8@wikipedia.org', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (478, 'Kaitlyn', 'Forcer', '602-435-7218', 'kforcerd9@xing.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (479, 'Ermentrude', 'Boddington', '120-660-8638', 'eboddingtonda@eepurl.com', 'Tourism Excellence Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (480, 'Kelsy', 'Banker', '452-460-2709', 'kbankerdb@myspace.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (481, 'Henriette', 'Caghy', '422-319-8043', 'hcaghydc@t.co', 'Tourism Pioneer School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (482, 'Aili', 'Budd', '225-692-5615', 'abudddd@wisc.edu', 'Tourism Strategy Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (483, 'Vittoria', 'Walkinshaw', '988-691-2075', 'vwalkinshawde@mlb.com', 'National Park Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (484, 'Alison', 'Fardy', '290-353-9925', 'afardydf@marketwatch.com', 'City Exploration Lab');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (485, 'Ignatius', 'Anthona', '961-253-3526', 'ianthonadg@ehow.com', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (486, 'Codie', 'Eddins', '777-176-9274', 'ceddinsdh@amazon.co.jp', 'Landmark Interpretation Center');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (487, 'Valentijn', 'Hardway', '354-377-8710', 'vhardwaydi@nps.gov', 'Global Voyager Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (488, 'Tami', 'Newlands', '620-582-6734', 'tnewlandsdj@hatena.ne.jp', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (489, 'Tallie', 'Vasyunichev', '722-620-4237', 'tvasyunichevdk@ehow.com', 'Discovery Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (490, 'Torr', 'Monckman', '635-446-8976', 'tmonckmandl@ow.ly', 'Eco-Tourism Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (491, 'Marijo', 'Lowbridge', '559-504-1323', 'mlowbridgedm@house.gov', 'Destination Guide Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (492, 'Arlan', 'Schwanden', '879-910-9121', 'aschwandendn@bigcartel.com', 'Backcountry Leadership Academy');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (493, 'Valentijn', 'Corrao', '392-192-4038', 'vcorraodo@dailymotion.com', 'Tourism Management Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (494, 'Carlen', 'Morcomb', '503-924-4829', 'cmorcombdp@blogspot.com', 'Travel Expert Institute');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (495, 'Issie', 'Rebanks', '659-219-8312', 'irebanksdq@wisc.edu', 'Elite Expedition School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (496, 'Cobby', 'Godsmark', '298-272-6306', 'cgodsmarkdr@myspace.com', 'Regional Tourism School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (497, 'Hilary', 'Hundall', '691-323-4431', 'hhundallds@people.com.cn', 'Compass Guide School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (498, 'Titus', 'Harkins', '457-147-1310', 'tharkinsdt@joomla.org', 'Legacy Heritage School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (499, 'Kial', 'Weatherby', '762-450-4223', 'kweatherbydu@whitehouse.gov', 'Cultural Exchange School');
insert into GUIDE (g_ID, g_first_name, g_last_name, g_phone, g_email, school) values (500, 'Devlen', 'Burborough', '688-585-5159', 'dburboroughdv@eventbrite.com', 'World Guide College');
