insert into STATION (s_name, s_address, descrip) values ('Horse', '5 Nevada Pass', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into STATION (s_name, s_address, descrip) values ('Host', '411 Nevada Pass', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Hotel', '13899 Orin Park', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Hour', '65967 Crowley Street', 'Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('House', '89266 Grayhawk Place', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Hover', '7 Eliot Court', 'Proin risus. Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Hub', '3187 Nobel Junction', 'Morbi a ipsum. Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Huge', '0 Kim Court', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Hull', '51 Troy Pass', 'In congue. Etiam justo.');
insert into STATION (s_name, s_address, descrip) values ('Human', '83092 Scofield Trail', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Hybrid', '5546 Fallview Court', 'Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Icon', '98 Graedel Lane', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Idea', '31 Darwin Center', 'Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Ideal', '0 Merrick Alley', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Idle', '80 South Alley', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Idol', '59529 East Way', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Image', '279 Arrowood Drive', 'Morbi a ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Impact', '8745 Stephen Point', 'Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Index', '041 Fulton Avenue', 'In congue. Etiam justo.');
insert into STATION (s_name, s_address, descrip) values ('Indigo', '96 Banding Point', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Info', '7908 Hoffman Terrace', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Inlet', '41219 Brentwood Crossing', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Inner', '167 Maywood Way', 'In congue. Etiam justo.');
insert into STATION (s_name, s_address, descrip) values ('Input', '17 Hanson Parkway', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Iron', '59792 Esch Parkway', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Island', '6 Glacier Hill Place', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Issue', '16348 Golf Course Terrace', 'Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Item', '5 Pennsylvania Trail', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Ivory', '13585 Huxley Lane', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Jade', '6562 Harper Pass', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Jasper', '9142 Grim Lane', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Jazz', '58 School Circle', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Jewel', '041 Del Sol Road', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into STATION (s_name, s_address, descrip) values ('Join', '27719 Schlimgen Lane', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Joint', '26991 Colorado Street', 'Etiam faucibus cursus urna. Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Jolt', '46 Mariners Cove Parkway', 'Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Journal', '3 Green Ridge Avenue', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Joy', '3512 Hollow Ridge Road', 'Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Judge', '7635 South Trail', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Juice', '1721 Spohn Drive', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Jump', '93 Oak Pass', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('June', '68252 Sutherland Drive', 'Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Jungle', '55086 Eastlawn Street', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Junior', '02373 Heffernan Center', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Juror', '6 Evergreen Parkway', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Jury', '51 Rowland Terrace', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Just', '99 Maywood Junction', 'Morbi quis tortor id nulla ultrices aliquet. Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, s_address, descrip) values ('Keel', '800 Jay Circle', 'Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('KeenתAdmiral', '72 Knutson Road', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Aero', '878 Clove Drive', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Akko', '04766 Manitowish Drive', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Alon', '5 Northport Parkway', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Alpha', '0424 Warner Terrace', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Alpine', '047 Magdeline Place', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Amber', '571 Mosinee Trail', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Anchor', '769 Mayer Parkway', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Annex', '80 Hansons Place', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Apex', '3245 Coleman Trail', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Arcadia', '22 Homewood Center', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Arch', '687 Mendota Road', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo.');
insert into STATION (s_name, s_address, descrip) values ('Arena', '9 Farwell Place', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Arid', '39 Esch Drive', 'Integer ac neque. Duis bibendum.');
insert into STATION (s_name, s_address, descrip) values ('Armada', '6052 Maple Wood Street', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Armor', '826 Crownhardt Junction', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Arrow', '8627 Sauthoff Trail', 'Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Aspect', '542 Rusk Lane', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Aster', '861 Vernon Circle', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Astral', '921 Kingsford Park', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Atrium', '1 Waywood Point', 'Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Aura', '16086 Golden Leaf Hill', 'Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Aurora', '5 Anthes Avenue', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Avalon', '91667 Sachtjen Center', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Avenue', '282 Caliangt Pass', 'Suspendisse potenti. Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Aviary', '339 Oakridge Alley', 'Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Badge', '6 Granby Lane', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Banner', '22 Farragut Street', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Bareket', '177 Sloan Junction', 'Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Baron', '041 Iowa Trail', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Base', '74 Utah Plaza', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Basin', '215 8th Court', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Bay', '02 Dakota Terrace', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Bayside', '03 Hudson Plaza', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Beacon', '0 Northwestern Junction', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Belfry', '1764 Anniversary Way', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Belgrave', '604 Gerald Terrace', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Belo', '7 Clove Street', 'Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Belt', '4 Sherman Avenue', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Berlin', '9 Lakeland Street', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Beta', '94654 Fremont Crossing', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Better', '386 Weeping Birch Alley', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Beyond', '20427 Forster Trail', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Bio', '7 Old Shore Park', 'Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Birch', '10 Atwood Way', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Bishop', '37 Drewry Circle', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Blaze', '63 Mariners Cove Drive', 'Proin risus.');
insert into STATION (s_name, s_address, descrip) values ('Blimp', '32808 Nova Terrace', 'Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Block', '6 Sachtjen Court', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Blue', '1 Forest Drive', 'Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Bluff', '0 Gina Parkway', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Bold', '33 Iowa Avenue', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Bolt', '60229 Eastlawn Drive', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Bond', '51 Dahle Junction', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Bonus', '15818 Cottonwood Park', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Boon', '91404 Michigan Park', 'In congue.');
insert into STATION (s_name, s_address, descrip) values ('Boost', '80 Manley Plaza', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Border', '002 Kim Trail', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Bottom', '11005 Bowman Terrace', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Bound', '2 Tomscot Junction', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Bounty', '26859 Mendota Point', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Brace', '0272 Mitchell Pass', 'Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Branch', '37 Service Alley', 'Aliquam erat volutpat. In congue.');
insert into STATION (s_name, s_address, descrip) values ('Brave', '5 Buell Point', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Bravo', '22 Jana Parkway', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Breeze', '90725 Quincy Alley', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Briar', '025 Sachtjen Road', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Brick', '70 West Alley', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Bridge', '6823 Judy Avenue', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Bright', '47421 Division Circle', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Broad', '030 Mosinee Park', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Broadview', '36280 6th Center', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Bronze', '9 Lawn Plaza', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Brook', '53 Anzinger Place', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Burst', '419 Main Park', 'Curabitur convallis.');
insert into STATION (s_name, s_address, descrip) values ('Cabin', '546 Luster Court', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Cable', '9 Heath Trail', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Cadet', '36497 Dunning Place', 'Aliquam erat volutpat. In congue.');
insert into STATION (s_name, s_address, descrip) values ('Cairo', '761 Graceland Lane', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Calm', '741 North Trail', 'Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Cameo', '47 Twin Pines Place', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Camp', '86 Sauthoff Avenue', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Canal', '312 Crest Line Pass', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Canopy', '313 Petterle Avenue', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Canvas', '6 Anniversary Pass', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Canyon', '087 Sugar Center', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Capital', '4200 Maple Parkway', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Captain', '2285 Granby Parkway', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Cargo', '497 Kennedy Way', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Carmel', '8332 3rd Terrace', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Case', '59 Oneill Street', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Castle', '370 Loftsgordon Hill', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Cause', '67578 Michigan Plaza', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Cave', '70348 Clemons Crossing', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Cedar', '42 Chinook Lane', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Cell', '11779 Melrose Drive', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Central', '97 Gerald Point', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Chain', '03 Clyde Gallagher Circle', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Chalk', '4400 Susan Lane', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Chapel', '03 Kennedy Way', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Charm', '7 Onsgard Point', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Chart', '00381 Talmadge Hill', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Chasm', '692 Namekagon Hill', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Chi', '93 Warbler Place', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Chief', '560 Comanche Street', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Choice', '6159 Troy Plaza', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Chord', '177 Talisman Park', 'Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Chrome', '0363 Mandrake Drive', 'Donec quis orci eget orci vehicula condimentum.');
insert into STATION (s_name, s_address, descrip) values ('Church', '5966 Stephen Park', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Cipher', '1652 Hovde Street', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Circle', '9239 Milwaukee Junction', 'Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Clan', '417 Comanche Avenue', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Clarity', '393 Eggendart Lane', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Classic', '3980 Hanson Crossing', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Clear', '309 Summerview Circle', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Clermont', '516 Spohn Trail', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Cliff', '03207 Northfield Crossing', 'Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Climb', '97407 Maple Wood Court', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Cloak', '80069 Bartillon Pass', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Clover', '60 Clyde Gallagher Parkway', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Coast', '816 Pankratz Circle', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Cobalt', '964 Sherman Place', 'Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Coin', '6290 Schiller Alley', 'Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Cold', '02587 Lyons Pass', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Colony', '9041 Ludington Street', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Column', '13 Namekagon Avenue', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Combat', '62 Eliot Way', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Comet', '4329 Vermont Parkway', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Common', '3580 4th Court', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Compass', '3 Manitowish Terrace', 'Proin risus.');
insert into STATION (s_name, s_address, descrip) values ('Concord', '411 Heffernan Park', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Copper', '659 Shasta Trail', 'Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Coral', '4967 Center Point', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Core', '68 Hermina Street', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Corner', '16985 Judy Plaza', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Cosmic', '7823 Hermina Lane', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Council', '26539 Twin Pines Drive', 'Vivamus in felis eu sapien cursus vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('County', '7 Transport Avenue', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Course', '397 Farragut Park', 'Etiam justo.');
insert into STATION (s_name, s_address, descrip) values ('Court', '948 Westridge Road', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Cove', '1567 Carey Trail', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Craft', '1881 Gale Place', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Crane', '4815 Blue Bill Park Drive', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, s_address, descrip) values ('Crater', '9149 Starling Drive', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Credit', '858 Fremont Terrace', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Creed', '7522 Vahlen Hill', 'Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Creek', '911 Alpine Circle', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Crest', '8 Quincy Parkway', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Cross', '7 Warbler Terrace', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Crown', '31 Scofield Lane', 'Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Cruise', '22538 Northwestern Place', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Cruz', '5 Maple Point', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, s_address, descrip) values ('Crystal', '4479 1st Court', 'Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Cube', '9369 Main Plaza', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Cult', '9745 Fordem Pass', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Curve', '1 Old Shore Hill', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Cyber', '3 Marquette Point', 'Curabitur convallis.');
insert into STATION (s_name, s_address, descrip) values ('Cycle', '666 Brickson Park Place', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Daily', '7110 Roth Trail', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Dale', '75 Springview Junction', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Dalton', '53 Bunting Lane', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Damp', '6 American Ash Center', 'Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into STATION (s_name, s_address, descrip) values ('Dancer', '1973 Little Fleur Way', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Daring', '25 Columbus Alley', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Dart', '93 Cherokee Trail', 'Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Dash', '27957 Upham Plaza', 'Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Dawn', '0202 Buell Hill', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Day', '844 Harper Pass', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Dean', '499 Oak Crossing', 'Suspendisse potenti. In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Dear', '308 East Plaza', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Debt', '5 4th Alley', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Decal', '0 Golf View Avenue', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Deck', '87385 Hollow Ridge Park', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Decree', '18541 Nova Avenue', 'Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Deep', '72 Westport Hill', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Dekel', '7 Glendale Place', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Delhi', '46 Gulseth Hill', 'Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Delta', '3855 Cascade Alley', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Dense', '8 Montana Way', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Depot', '8382 Springview Way', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Depth', '1 Chive Park', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Derby', '5388 Moulton Hill', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Desert', '5541 Southridge Point', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Design', '9530 Luster Pass', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Detail', '9242 Alpine Circle', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Device', '99594 Novick Point', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Dewberry', '42558 Sherman Park', 'Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Dial', '1 Myrtle Point', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Diamond', '11379 Burrows Lane', 'Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Diary', '9343 Nancy Terrace', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Dice', '2 Rowland Center', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Diesel', '761 Sachtjen Point', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Digi', '88 Sunnyside Way', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Digit', '6 Hazelcrest Drive', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Dion', '3487 Golf Course Park', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Direct', '8776 American Drive', 'Ut at dolor quis odio consequat varius. Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Disc', '389 Buhler Pass', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Distant', '020 Holy Cross Lane', 'Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Diver', '6075 Dapin Street', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Divide', '38843 Marcy Circle', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Divine', '8588 Maryland Crossing', 'Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Dock', '75 Oneill Street', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Dome', '9389 Vermont Lane', 'In eleifend quam a odio.');
insert into STATION (s_name, s_address, descrip) values ('Donor', '81 Crownhardt Lane', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Doom', '562 Dryden Point', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Door', '774 Washington Junction', 'Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Dose', '8 Monterey Trail', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Double', '6769 Algoma Crossing', 'Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Dover', '0 Kedzie Court', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Downriver', '8 Prairie Rose Hill', 'Aliquam erat volutpat. In congue.');
insert into STATION (s_name, s_address, descrip) values ('Downtown', '8287 East Way', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Draft', '931 Steensland Park', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Dragon', '969 Becker Hill', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Drain', '62963 Bultman Avenue', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Dream', '0996 Thompson Plaza', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, s_address, descrip) values ('Drift', '9410 Grayhawk Center', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Driftwood', '0437 Arizona Point', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Drill', '7132 Kedzie Pass', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Drink', '674 Donald Plaza', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Drive', '5920 Ilene Park', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Drone', '4 Mendota Point', 'Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Drop', '1000 Cascade Center', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Drum', '48041 Barby Way', 'Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Dry', '94 Brickson Park Street', 'Etiam faucibus cursus urna. Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Dual', '84550 Susan Drive', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Duct', '217 Oxford Hill', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Duel', '246 Rusk Point', 'Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Duke', '234 Mcbride Trail', 'Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Dune', '32 Duke Road', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Dusk', '7606 Northport Drive', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Dust', '10183 Carpenter Place', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Duty', '1 Roxbury Point', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Dwarf', '83972 Mandrake Park', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Dye', '2 Kennedy Terrace', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Dynamic', '7225 Mockingbird Junction', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Eagle', '88 Montana Parkway', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Early', '45 Surrey Avenue', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Earth', '39 Heffernan Alley', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Ease', '67930 Waubesa Alley', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('East', '422 Red Cloud Trail', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Eastgate', '793 Maywood Center', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Easton', '2426 Kings Terrace', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Echo', '8 Red Cloud Way', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Eco', '4608 Mayfield Parkway', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Edge', '78 Amoth Road', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Edgecliff', '8 Green Ridge Junction', 'In congue.');
insert into STATION (s_name, s_address, descrip) values ('Edit', '40 Clemons Point', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Effect', '7 Bowman Hill', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Eilat', '39 Scoville Plaza', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Eight', '5 Birchwood Court', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Elden', '04447 Acker Way', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Elder', '47083 Lukken Avenue', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Elect', '81 Derek Junction', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Elite', '6 Glacier Hill Alley', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Elmdale', '3 Loeprich Way', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Ember', '96 Lake View Plaza', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Emblem', '5 Redwing Center', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Emerald', '520 Mallard Court', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Engine', '94167 Dennis Terrace', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam. Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Entry', '636 Namekagon Terrace', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Envoy', '42688 Lake View Trail', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Enza', '319 Sherman Drive', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Epic', '89374 Gale Trail', 'Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Epoch', '3 Carey Alley', 'Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Epsilon', '419 Burning Wood Street', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Equal', '6 Garrison Plaza', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Era', '33503 Waubesa Terrace', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Erez', '1749 Armistice Point', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Error', '05114 Paget Trail', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Essay', '59 Nancy Alley', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Estate', '625 Rowland Drive', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Eta', '5296 Little Fleur Road', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Ether', '45 Esker Park', 'Proin risus. Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Ethics', '9 Alpine Alley', 'Phasellus sit amet erat. Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Event', '08 Morrow Way', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Ever', '049 Northland Place', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Evoke', '116 Amoth Street', 'Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Exact', '0929 Sage Circle', 'Phasellus sit amet erat. Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Exalt', '0 Toban Lane', 'Fusce consequat. Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Exam', '2 Ryan Hill', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Excel', '0151 Moulton Drive', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam.');
insert into STATION (s_name, s_address, descrip) values ('Exit', '763 Hintze Way', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Expert', '612 Service Lane', 'Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, s_address, descrip) values ('Extra', '117 Oakridge Street', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Eye', '3 Porter Trail', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Fable', '878 Bultman Point', 'Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Facet', '3656 Cardinal Lane', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Fact', '489 Comanche Court', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Fade', '4 Badeau Hill', 'Etiam vel augue.');
insert into STATION (s_name, s_address, descrip) values ('Fair', '27050 Burrows Drive', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Fairmont', '22027 Dixon Court', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Falcon', '25139 Porter Street', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Fall', '61 Sunnyside Avenue', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('False', '9 American Drive', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Fame', '2 Norway Maple Junction', 'Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Fancy', '5 Carey Place', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Fang', '07328 Hayes Park', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Fargo', '575 Badeau Crossing', 'Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Farm', '959 Armistice Center', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Fast', '006 Fisk Park', 'Donec semper sapien a libero. Nam dui.');
insert into STATION (s_name, s_address, descrip) values ('Fate', '7066 Blaine Park', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Fault', '496 Merchant Center', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem. Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Favor', '8 Coleman Junction', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Feast', '1556 Fairview Circle', 'Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Feature', '24 Victoria Hill', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Federal', '7992 Steensland Street', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Fellow', '77 Oakridge Point', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Felt', '427 Leroy Circle', 'Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Fence', '4116 Sunnyside Junction', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Fern', '3780 Lakewood Gardens Parkway', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Ferry', '84333 Straubel Crossing', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Fetch', '301 Rieder Junction', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Fever', '44245 Oak Valley Avenue', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Fiber', '5317 Hooker Circle', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Field', '943 Sunnyside Lane', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Fifth', '78 Darwin Road', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Fifty', '901 Milwaukee Court', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Fight', '46790 Morningstar Terrace', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Figure', '61478 Sloan Way', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('File', '3 Arapahoe Circle', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Fill', '5 Miller Circle', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Film', '50523 Gina Trail', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Filter', '21 Loeprich Pass', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Final', '8468 Farwell Center', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Finch', '23 Nobel Trail', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Find', '6997 Butterfield Way', 'Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Fine', '3452 Hanson Place', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Finish', '72093 7th Lane', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Finite', '141 Sunnyside Trail', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Fino', '30533 Lerdahl Avenue', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Fire', '697 Oxford Place', 'Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Firm', '29120 Bashford Plaza', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('First', '8 Sommers Place', 'Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Fish', '1176 Orin Park', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Five', '16616 Old Shore Circle', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Fixed', '64 Sutteridge Park', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Flag', '87 Morning Plaza', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Flame', '3685 Fairfield Parkway', 'Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Flare', '2097 Bartelt Circle', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Flash', '5652 Warbler Trail', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Flat', '0409 Lakeland Point', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Fleet', '9593 Parkside Plaza', 'Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Flesh', '59 Carey Junction', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Flex', '75767 Lindbergh Pass', 'Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Flick', '9897 Anderson Pass', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Flight', '8 Ridgeview Street', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Flint', '3607 Kim Point', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Float', '5008 Pepper Wood Lane', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Flock', '06787 Fremont Pass', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Flood', '026 Butternut Drive', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Floor', '168 Saint Paul Lane', 'Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Flora', '30833 Hagan Lane', 'Donec vitae nisi. Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Flour', '77 Bellgrove Place', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Flow', '76 Harper Plaza', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Fluid', '6634 Arkansas Drive', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Flush', '878 Doe Crossing Center', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Flux', '2957 Meadow Ridge Hill', 'Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Fly', '650 Corben Avenue', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Focus', '92 Morning Park', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Fog', '3258 Lake View Terrace', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Foil', '21144 Daystar Drive', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Fold', '2422 Bellgrove Pass', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Folk', '26 Lerdahl Park', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Font', '7368 Surrey Drive', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Food', '3 Center Trail', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Foot', '3446 Fairview Way', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Foothill', '49 Pearson Park', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Force', '807 Lien Circle', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Forest', '92 Dixon Hill', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Forge', '03 Graedel Junction', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Fork', '63 Eggendart Alley', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Form', '1 Fuller Court', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Fort', '17 Village Alley', 'Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Forth', '422 East Trail', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Fossil', '832 Bayside Avenue', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Found', '911 Messerschmidt Way', 'Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Four', '12 Mayfield Center', 'Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Fourth', '711 Bunker Hill Point', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Fox', '125 Luster Road', 'Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Foxrun', '41 Tomscot Avenue', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Fraction', '92597 Village Green Way', 'Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Frame', '5 Commercial Street', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Frank', '6 Montana Parkway', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Free', '4406 Victoria Court', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Freeze', '4 Brickson Park Terrace', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Freight', '285 Cottonwood Junction', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Fresh', '4 Ramsey Parkway', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Friar', '6 Lake View Street', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Friend', '9 Dexter Hill', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Front', '42346 Pine View Road', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Frost', '06783 Derek Court', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Frown', '65 Transport Crossing', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Fruit', '9 Bartillon Court', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Fuel', '91519 Duke Park', 'Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Full', '46 Knutson Plaza', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Fund', '9 Hanover Place', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Funny', '3889 Northland Avenue', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Fuse', '14 Hudson Pass', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Future', '234 Caliangt Junction', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Gable', '750 Troy Plaza', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Gain', '628 Menomonie Place', 'Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Galaxy', '01450 Dryden Road', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Gale', '64 Eagan Terrace', 'In congue.');
insert into STATION (s_name, s_address, descrip) values ('Gallery', '7 Delladonna Circle', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Game', '449 Jana Parkway', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Gamma', '7319 6th Crossing', 'Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Gap', '0 Hudson Park', 'Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Garage', '94802 Golf Course Center', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Garden', '8760 Commercial Pass', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Garlic', '988 Carberry Pass', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Gas', '50822 Magdeline Alley', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Gate', '0 Ramsey Way', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Gato', '540 Mendota Court', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Gauge', '414 Stephen Plaza', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Gaze', '27 Sachtjen Court', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Gear', '589 Dawn Hill', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Gem', '5755 Claremont Parkway', 'Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('General', '0 Lake View Terrace', 'Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Genius', '10371 Springs Place', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, s_address, descrip) values ('Genre', '64 Valley Edge Center', 'Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Gentle', '4 Roxbury Drive', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into STATION (s_name, s_address, descrip) values ('Genu', '2 Mcbride Junction', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Geo', '3 Old Gate Plaza', 'Nulla justo. Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Geva', '20077 Sugar Circle', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Ghost', '31166 Grasskamp Parkway', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Giant', '1 Linden Alley', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Gift', '74095 Nevada Way', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Gilded', '09 Ryan Lane', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Gill', '146 Melby Court', 'Nulla ut erat id mauris vulputate elementum. Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Ginger', '830 Fuller Junction', 'Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Gird', '10382 Birchwood Point', 'Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Girth', '2 Gateway Terrace', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Given', '11 Trailsway Crossing', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Glad', '424 Blaine Center', 'Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Glance', '2952 Marquette Park', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Glass', '839 Graedel Terrace', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Glencoe', '638 Orin Pass', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Glenview', '343 Ludington Parkway', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Glide', '4 Carpenter Point', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Glimp', '5360 Loftsgordon Plaza', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci.');
insert into STATION (s_name, s_address, descrip) values ('Globe', '518 Doe Crossing Parkway', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Gloom', '1009 Dorton Crossing', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Glory', '8 Scoville Center', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Gloss', '032 Hoffman Circle', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Glove', '49709 Gulseth Avenue', 'Morbi a ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Glow', '491 Bartelt Trail', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Glue', '51043 Kim Plaza', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Goal', '2802 Anthes Terrace', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Goat', '9 Packers Park', 'Etiam vel augue.');
insert into STATION (s_name, s_address, descrip) values ('Gold', '9127 Grayhawk Circle', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Golf', '39052 Miller Way', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Good', '01 Roxbury Terrace', 'Nunc purus. Phasellus in felis.');
