insert into STATION (s_name, s_address, descrip) values ('Main Entrance', '41640 Reindahl Road', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Visitor Center', '792 Lunder Pass', 'Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Historic Clock Tower', '0 Farragut Plaza', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Central Fountain', '11 Main Park', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, s_address, descrip) values ('Ancient Stone Bridge', '289 Dorton Trail', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Riverside Path', '42462 Muir Center', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Sunset Point', '43714 Farragut Center', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Grand Cathedral', '6794 Old Gate Trail', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Local Artisan Market', '8987 Mesta Avenue', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Hidden Garden', '16786 Orin Center', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Memorial Statue', '68 Nova Alley', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Old City Gate', '0 Pearson Crossing', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Panoramic Lookout', '172 Thierer Place', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Botanical Greenhouse', '830 Linden Place', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('City Hall Plaza', '20 Fieldstone Road', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, s_address, descrip) values ('Riverfront Pier', '7 Crowley Point', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Mountain Trailhead', '35 Eggendart Court', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Village Square', '85886 Bunker Hill Park', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Art Gallery Lane', '6169 Annamark Plaza', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Castle Courtyard', '5116 Ilene Parkway', 'Proin eu mi. Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Hidden Courtyard', '7 Harbort Park', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Waterfront Promenade', '98235 Debra Place', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Sculptural Park', '6991 Grasskamp Lane', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Gourmet Food Hall', '885 Scofield Avenue', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Victorian Row', '32907 Dakota Place', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Modern Art Muse', '4238 Sachtjen Drive', 'Morbi a ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Forest Clearing', '23511 Twin Pines Alley', 'Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Harbor Viewpoint', '71 Hoffman Street', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Museum Lobby', '86 Sullivan Place', 'Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Lighthouse Trail', '719 Reindahl Parkway', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Cobblestone Alley', '9 Florence Park', 'Proin risus.');
insert into STATION (s_name, s_address, descrip) values ('Skyline Balcony', '46 Huxley Parkway', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Urban Orchard', '6451 Erie Road', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('University Quad', '4201 Crescent Oaks Lane', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Theater District Sign', '20 Charing Cross Terrace', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Botanical Garden Gate', '822 Anzinger Point', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Waterfall Base', '936 Shasta Alley', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.');
insert into STATION (s_name, s_address, descrip) values ('Peak Summit', '32666 Moulton Terrace', 'Fusce consequat. Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Canal Bridge', '694 Pepper Wood Plaza', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Antique Shop Corner', '0651 Golf Center', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Heritage House', '0313 Morning Hill', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Liberty Square', '042 Coolidge Alley', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Eco-Trail Marker', '27015 Vermont Junction', 'In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Spice Market Entrance', '98 Sunbrook Crossing', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Brewery Courtyard', '621 Banding Alley', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Vineyard Row', '113 Brentwood Drive', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Street Art Wall', '873 Donald Point', 'Fusce consequat. Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Midnight Alley', '865 Warrior Crossing', 'Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Shadow Archway', '54235 Ludington Way', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Library Steps', '614 Luster Way', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Botanical Garden Pond', '82 Lawn Road', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Nature Boardwalk', '5252 Manley Avenue', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Hilltop Chapel', '84523 Ludington Drive', 'Etiam faucibus cursus urna. Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Downtown Hub', '33097 Jenifer Trail', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('East Gate', '27068 Sutherland Way', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('West Wing', '80461 Village Green Pass', 'Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('South Port', '19 Truax Terrace', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('North Ridge', '0 6th Junction', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Fortress Wall', '59 7th Road', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Royal Gardens', '9800 Little Fleur Place', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Old Mill', '0 Westerfield Hill', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Stone Circle', '6723 Knutson Street', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Sacred Grove', '52639 Luster Road', 'Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Canyon Rim', '82 Carioca Terrace', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Lake Shore', '2 Bowman Plaza', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Desert Oasis', '993 Artisan Alley', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Jungle Canopy', '5685 Thompson Place', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Safari Outpost', '952 Jay Street', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Cave Entrance', '42 Fallview Center', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Glacial Path', '22 Becker Plaza', 'Nulla mollis molestie lorem. Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Pine Forest', '8907 Sage Trail', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into STATION (s_name, s_address, descrip) values ('Meadow View', '14 Jackson Crossing', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Wildflower Field', '54220 Cordelia Place', 'Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Stream Crossing', '6 Roxbury Place', 'Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Rocky Ridge', '73318 Mccormick Trail', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Cliffside Stairs', '324 Bellgrove Place', 'Etiam justo. Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Beach Cove', '168 Thompson Road', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Coral Reef Point', '540 Mitchell Place', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Island Jetty', '576 Brickson Park Hill', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Port Authority', '3786 John Wall Alley', 'Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Rail Station Plaza', '9525 Bayside Pass', 'Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Metro Entrance', '712 Macpherson Avenue', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Bus Terminal Hub', '1 Waywood Hill', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Bike Rental Stand', '971 Anthes Lane', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Pedestrian Bridge', '186 Browning Drive', 'Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Skywalk Entry', '98333 Stephen Parkway', 'Integer ac neque. Duis bibendum.');
insert into STATION (s_name, s_address, descrip) values ('Rooftop Deck', '96 Kipling Lane', 'Nunc purus. Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Observation Tower', '11240 Badeau Drive', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Glass Elevator', '98196 Corscot Junction', 'Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Marble Arch', '0 Utah Hill', 'Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Clockwork Square', '61 Haas Road', 'Etiam justo. Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Neon Street', '284 Elgar Parkway', 'Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Jazz Club Corner', '10474 Atwood Street', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Opera House Foyer', '8041 Service Center', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Ballet Studio', '1 Carey Lane', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Cinema Row', '314 Waubesa Way', 'Morbi a ipsum. Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Puppet Theater', '75 Barnett Drive', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into STATION (s_name, s_address, descrip) values ('Toy Store Window', '14 West Crossing', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Candy Shop', '59 Maryland Center', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Bakery Corner', '56001 Lien Lane', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Cheese Cellar', '26 8th Pass', 'Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Wine Vault', '55 Ryan Circle', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Coffee Roastery', '1 Southridge Road', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Tea House', '6 Morningstar Road', 'Etiam justo.');
insert into STATION (s_name, s_address, descrip) values ('Chocolate Factory', '68 Texas Trail', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Farm Stand', '8 Gale Alley', 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Orchard Gate', '7 Nobel Terrace', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Harvest Barn', '3 Orin Lane', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Greenhouse Row', '8 Village Green Court', 'Pellentesque ultrices mattis odio. Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Flower Stall', '688 John Wall Circle', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Craft Workshop', '87 Forest Park', 'Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Potter’s Studio', '68 Bluestem Drive', 'Morbi vel lectus in quam fringilla rhoncus. Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Weaver’s Loom', '4 Oriole Parkway', 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Blacksmith Forge', '3 Oak Valley Parkway', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Industrial Loft', '1262 Kinsman Way', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Tech Hub', '693 Del Sol Pass', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Innovation Lab', '2269 Bayside Street', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Startup Space', '15 Commercial Trail', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Coworking Courtyard', '04336 Schurz Alley', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Fashion Boutique', '455 Haas Trail', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Tailor’s Shop', '5 Independence Park', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Jewelry Row', '019 Summerview Parkway', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.');
insert into STATION (s_name, s_address, descrip) values ('Diamond Vault', '70838 Clemons Lane', 'Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Luxury Lounge', '52584 Elgar Alley', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Spa Entrance', '18 Lillian Center', 'Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Meditation Hall', '02728 Armistice Point', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Yoga Studio', '44 Talisman Point', 'Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Zen Garden', '73 Esch Alley', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Reflection Pool', '19020 Moose Avenue', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Silent Corridor', '2099 Ridge Oak Way', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Morning Terrace', '2390 Hagan Avenue', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Evening Balcony', '54393 Quincy Place', 'Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, s_address, descrip) values ('Twilight Pier', '3554 Bultman Junction', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Starry Deck', '8 Debs Junction', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Moonlight Path', '43 Dottie Way', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Foggy Bridge', '878 Trailsway Terrace', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, s_address, descrip) values ('Misty Valley', '72280 Sutherland Place', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Thunder Peak', '08 Dexter Way', 'Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Sunny Glade', '6603 Holmberg Terrace', 'Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Breezy Point', '49 Mendota Trail', 'Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Calm Creek', '68028 Chinook Parkway', 'Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Rapid Run', '11797 Linden Park', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Shady Nook', '861 Clemons Trail', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Sunny Patch', '0383 Milwaukee Park', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Berry Bush', '6204 2nd Drive', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Apple Tree', '0749 Bunker Hill Trail', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Oak Grove', '9 Laurel Drive', 'Mauris lacinia sapien quis libero. Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Willow Pond', '18846 Bunting Park', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Lily Pad', '51 Glendale Hill', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Frog Pond', '17 Meadow Vale Crossing', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Butterfly Bush', '91 Rockefeller Park', 'Proin risus. Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Hummingbird Lane', '35 Mitchell Pass', 'Cras pellentesque volutpat dui. Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc.');
insert into STATION (s_name, s_address, descrip) values ('Bird Watch Tower', '21447 Mariners Cove Drive', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Fox Den', '79 Susan Crossing', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem. Duis aliquam convallis nunc.');
insert into STATION (s_name, s_address, descrip) values ('Deer Track', '143 Nancy Street', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.');
insert into STATION (s_name, s_address, descrip) values ('Wolf Path', '84565 Harbort Circle', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Bear Cave', '6 Warbler Point', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Eagle Nest', '1334 Kings Road', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Owl Tree', '37 Beilfuss Avenue', 'Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Squirrel Scramble', '80 Derek Road', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Rabbit Hole', '104 Melody Park', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Badger Set', '45 Toban Park', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Otter Slide', '57348 Reinke Lane', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Beaver Dam', '19 Raven Park', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Fish Ladder', '2 Mandrake Junction', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Shell Beach', '71 Messerschmidt Crossing', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Pebble Path', '642 Lien Trail', 'Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Sand Dune', '9 John Wall Plaza', 'Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Oasis Well', '4 2nd Terrace', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Nomad Camp', '5869 Derek Road', 'Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Caravan Stop', '0 Hollow Ridge Drive', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Trade Post', '3 Golf Drive', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat.');
insert into STATION (s_name, s_address, descrip) values ('Outlaw Hideout', '212 Jackson Court', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Pirate Cove', '322 Caliangt Plaza', 'Nam dui.');
insert into STATION (s_name, s_address, descrip) values ('Smuggler’s Tunnel', '25040 Stone Corner Center', 'Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('Bandit Camp', '302 Caliangt Hill', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Cursed Well', '50 Transport Alley', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Haunted Shack', '8 Kim Center', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Phantom Lane', '48940 Del Sol Center', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Mystery Gate', '43 Duke Place', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Riddle Wall', '58 Magdeline Circle', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Puzzle Box', '65784 Dexter Plaza', 'Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Enigma Room', '833 Glacier Hill Drive', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Secret Passage', '7 Artisan Alley', 'Suspendisse potenti. Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Hidden Door', '5 Center Pass', 'Nulla nisl. Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Vault Entry', '41 Kennedy Hill', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('Treasury Room', '750 Swallow Center', 'Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Trophy Hall', '2285 Saint Paul Center', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Banner Row', '97 Logan Alley', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Knight’s Table', '970 Dottie Drive', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis.');
insert into STATION (s_name, s_address, descrip) values ('Throne Room', '063 Red Cloud Court', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Banquet Hall', '28 Mosinee Lane', 'Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Armory', '08897 Doe Crossing Terrace', 'Etiam faucibus cursus urna. Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Dungeon Cell', '545 Burning Wood Avenue', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Tower Room', '4117 Bartillon Pass', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Spiral Stairs', '0 Arrowood Court', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus.');
insert into STATION (s_name, s_address, descrip) values ('Attic Window', '294 Shasta Terrace', 'Donec semper sapien a libero. Nam dui.');
insert into STATION (s_name, s_address, descrip) values ('Cellar Door', '18 Nelson Terrace', 'Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Garden Shed', '65633 Novick Lane', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Tool Workshop', '3092 Clove Drive', 'Aenean auctor gravida sem. Praesent id massa id nisl venenatis lacinia.');
insert into STATION (s_name, s_address, descrip) values ('Garage Bay', '983 Mallard Circle', 'Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Hangar Gate', '6 Vidon Alley', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Runway End', '1262 Arrowood Terrace', 'Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Launch Pad', '649 Golf Course Point', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Control Room', '0 Rieder Pass', 'Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Lab Bench', '25644 Harper Crossing', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Server Room', '4 Westerfield Point', 'Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Library Stacks', '88617 Del Sol Street', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Reading Nook', '74 Leroy Trail', 'Morbi ut odio. Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Study Desk', '53 Melody Park', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Scholar’s Hall', '326 Oneill Place', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Dean’s Office', '86232 Eastlawn Plaza', 'Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.');
insert into STATION (s_name, s_address, descrip) values ('Classroom A', '35707 Fulton Way', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Lecture Hall', '302 Russell Hill', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh. Quisque id justo sit amet sapien dignissim vestibulum.');
insert into STATION (s_name, s_address, descrip) values ('Lab Wing', '12 Mccormick Plaza', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Campus Green', '98047 Pond Way', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Alumni Walk', '585 Hollow Ridge Park', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Founder’s Hall', '8480 Dahle Trail', 'Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Victory Arch', '7860 Raven Pass', 'Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Medal Stand', '419 New Castle Parkway', 'Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Podium', '33 Tennyson Parkway', 'Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Finish Line', '67957 Dexter Hill', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Starting Block', '9 Anhalt Parkway', 'Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Sideline', '366 Arizona Point', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Dugout', '7 Buell Center', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Locker Room', '6201 Stoughton Junction', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Training Ground', '83 1st Alley', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Practice Field', '3 Cody Court', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Court Side', '3376 Anzinger Center', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Ring Side', '9 Vahlen Avenue', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Pit Stop', '9445 Kinsman Street', 'Vestibulum sed magna at nunc commodo placerat. Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Grandstand', '9866 Main Lane', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Bleachers', '37 3rd Street', 'Duis at velit eu est congue elementum. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Press Box', '5243 Hallows Pass', 'Nullam varius.');
insert into STATION (s_name, s_address, descrip) values ('VIP Box', '708 Little Fleur Place', 'Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Suite 101', '8430 Colorado Drive', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Lobby Bar', '08 Alpine Drive', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Hotel Lounge', '993 Talmadge Junction', 'Sed ante. Vivamus tortor.');
insert into STATION (s_name, s_address, descrip) values ('Suite Entrance', '8592 Kropf Place', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Rooftop Bar', '126 Vernon Way', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Basement Pub', '1924 Sheridan Drive', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Corner Tavern', '320 Kim Circle', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Bistro Table', '149 Roth Street', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Cafe Patio', '617 Clarendon Trail', 'Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Terrace Grill', '33224 Superior Park', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Kitchen Counter', '96482 Ramsey Street', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Chef’s Table', '5615 Northland Place', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Pantry', '6302 Gulseth Trail', 'In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.');
insert into STATION (s_name, s_address, descrip) values ('Larder', '287 South Circle', 'Integer ac neque.');
insert into STATION (s_name, s_address, descrip) values ('Cellar', '9 Clove Lane', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Attic', '7123 Service Hill', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Balcony', '0 Prentice Crossing', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Veranda', '61 Armistice Court', 'Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Porch', '12043 Lake View Terrace', 'Praesent lectus. Vestibulum quam sapien, varius ut, blandit non, interdum in, ante.');
insert into STATION (s_name, s_address, descrip) values ('Deck', '12784 Graedel Lane', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Patio', '6 Jay Parkway', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Courtyard', '8546 Waxwing Road', 'Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Square', '82 Browning Hill', 'In eleifend quam a odio. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Plaza', '01638 Utah Court', 'Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Circle', '78 Cottonwood Drive', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Crescent', '31926 Barby Way', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Row', '25 Claremont Parkway', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Mews', '69 Schiller Way', 'Nam dui.');
insert into STATION (s_name, s_address, descrip) values ('Lane', '6735 Village Green Road', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Alley', '5 West Court', 'Etiam vel augue.');
insert into STATION (s_name, s_address, descrip) values ('Street', '52 Brentwood Point', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Avenue', '5010 Red Cloud Crossing', 'Nulla tellus. In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Boulevard', '3729 Hayes Avenue', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Highway', '557 High Crossing Place', 'Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Road', '80 Monument Center', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Path', '89887 Laurel Crossing', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Trail', '4 Maple Wood Road', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi.');
insert into STATION (s_name, s_address, descrip) values ('Track', '10 Kings Terrace', 'Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('Way', '7456 Dottie Crossing', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Passage', '9042 Fremont Pass', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Tunnel', '494 Tomscot Road', 'Donec posuere metus vitae ipsum. Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Bridge', '63 Springview Terrace', 'Ut tellus. Nulla ut erat id mauris vulputate elementum.');
insert into STATION (s_name, s_address, descrip) values ('Overpass', '1750 Eliot Place', 'Pellentesque at nulla. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Underpass', '925 Browning Road', 'Aliquam sit amet diam in magna bibendum imperdiet.');
insert into STATION (s_name, s_address, descrip) values ('Crossing', '05944 Randy Lane', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Junction', '6900 Upham Way', 'Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Intersection', '38646 Mcbride Plaza', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Roundabout', '1281 Moulton Hill', 'Etiam faucibus cursus urna.');
insert into STATION (s_name, s_address, descrip) values ('Landmark', '24421 Annamark Road', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Marker', '20307 1st Lane', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Post', '42870 Prentice Hill', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Sign', '16 Trailsway Center', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.');
insert into STATION (s_name, s_address, descrip) values ('Beacon', '67 Killdeer Parkway', 'Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Light', '970 North Point', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Pillar', '486 Hudson Crossing', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Column', '7 Merrick Road', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, s_address, descrip) values ('Arch', '49719 Ridgeview Drive', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Gate', '754 Amoth Point', 'Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Wall', '751 6th Parkway', 'Integer tincidunt ante vel ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Fence', '93 Michigan Court', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Hedge', '8508 Wayridge Place', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Border', '955 Vahlen Point', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Edge', '8 Old Gate Parkway', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Rim', '0717 Golf View Avenue', 'Phasellus in felis. Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Verge', '7694 Hagan Pass', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Bank', '1978 Dixon Road', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Shore', '9 Pierstorff Hill', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Coast', '5806 Pawling Hill', 'Vivamus in felis eu sapien cursus vestibulum. Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Beach', '2 Forest Hill', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Cliff', '974 Arrowood Circle', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Peak', '84937 Lakewood Gardens Junction', 'Nunc rhoncus dui vel sem. Sed sagittis.');
insert into STATION (s_name, s_address, descrip) values ('Summit', '32191 Clarendon Parkway', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Crest', '731 Anzinger Trail', 'Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Ridge', '452 Esker Trail', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Slope', '582 Delaware Parkway', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Valley', '3 Forest Drive', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Basin', '7452 Homewood Hill', 'In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.');
insert into STATION (s_name, s_address, descrip) values ('Hollow', '8 Anthes Parkway', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Glade', '052 Mayfield Park', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Grove', '57 Little Fleur Trail', 'In sagittis dui vel nisl.');
insert into STATION (s_name, s_address, descrip) values ('Woods', '2179 Springview Junction', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla.');
insert into STATION (s_name, s_address, descrip) values ('Forest', '30 Hansons Alley', 'In hac habitasse platea dictumst. Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Wilds', '35668 Hallows Parkway', 'Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.');
insert into STATION (s_name, s_address, descrip) values ('Academic Atrium', '2 Riverside Place', 'Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Science Plaza', '123 Sunnyside Circle', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Engineering Block', '1 Everett Plaza', 'Nam tristique tortor eu pede.');
insert into STATION (s_name, s_address, descrip) values ('Robotics Lab', '7734 Green Ridge Drive', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('VR Simulation Room', '100 Claremont Terrace', 'In est risus, auctor sed, tristique in, tempus sit amet, sem.');
insert into STATION (s_name, s_address, descrip) values ('Cyber Security Center', '2395 Clarendon Crossing', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Data Farm', '5 Londonderry Crossing', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Al-Expert Hub', '9038 Shopko Hill', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Startup Garage', '2240 Golf Course Lane', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Incubator Wing', '76131 Vernon Plaza', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio.');
insert into STATION (s_name, s_address, descrip) values ('Mentorship Lounge', '4 Del Sol Alley', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('Pitch Deck', '452 Village Terrace', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Investor Gallery', '42819 Buhler Pass', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Patent Wall', '09718 Anzinger Road', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Research Archive', '597 Porter Center', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Ancient Manuscript Room', '47713 Tennyson Circle', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Philosophy Garden', '44603 Wayridge Drive', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Ethics Circle', '2 Chinook Alley', 'Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Logic Lane', '80458 Vidon Plaza', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Mathematics Hall', '5688 Bobwhite Junction', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Physics Amphitheater', '2117 Northport Pass', 'In quis justo. Maecenas rhoncus aliquam lacus.');
insert into STATION (s_name, s_address, descrip) values ('Chemistry Quad', '7098 Manufacturers Way', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Biology Greenhouse', '8 Roth Street', 'Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Genetic Trail', '604 Talmadge Road', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Deep Space Dish', '924 Mitchell Parkway', 'Integer non velit. Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue.');
insert into STATION (s_name, s_address, descrip) values ('Telescope Deck', '08 Green Ridge Lane', 'Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl. Aenean lectus.');
insert into STATION (s_name, s_address, descrip) values ('Observatory Dome', '55512 Mesta Junction', 'Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.');
insert into STATION (s_name, s_address, descrip) values ('Rocket Hangar', '3142 Towne Trail', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Avionics Bay', '37067 Continental Junction', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Flight Simulator', '41424 Evergreen Parkway', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Drone Port', '167 Washington Way', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Cargo Dock', '842 Warbler Parkway', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Logistics Center', '135 Dwight Lane', 'Aliquam non mauris. Morbi non lectus.');
insert into STATION (s_name, s_address, descrip) values ('Supply Chain Hub', '14297 Almo Plaza', 'Nunc nisl.');
insert into STATION (s_name, s_address, descrip) values ('Manufacturing Floor', '682 Monument Park', 'Vivamus vel nulla eget eros elementum pellentesque. Quisque porta volutpat erat.');
insert into STATION (s_name, s_address, descrip) values ('Assembly Line', '0 Kennedy Drive', 'Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Quality Control', '4 Sage Pass', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin interdum mauris non ligula pellentesque ultrices.');
insert into STATION (s_name, s_address, descrip) values ('Testing Range', '47717 Stang Street', 'Integer ac leo. Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Prototype Shop', '89 Badeau Street', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Design Studio', '9 Cherokee Park', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('UX Workshop', '487 Delaware Lane', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Branding Bay', '16 Hagan Crossing', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Marketing Loft', '80816 Alpine Park', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Media Studio', '10 Arizona Junction', 'Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Podcast Booth', '12265 International Point', 'Morbi non quam nec dui luctus rutrum. Nulla tellus.');
insert into STATION (s_name, s_address, descrip) values ('Green Room', '41987 Schurz Crossing', 'Donec semper sapien a libero.');
insert into STATION (s_name, s_address, descrip) values ('Sound Stage', '74 Pennsylvania Circle', 'Duis bibendum. Morbi non quam nec dui luctus rutrum.');
insert into STATION (s_name, s_address, descrip) values ('Editing Suite', '84652 1st Road', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Darkroom', '28723 Twin Pines Street', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Lithography Studio', '54902 Coolidge Road', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Sculpture Foundry', '59197 Amoth Way', 'Integer ac neque.');
insert into STATION (s_name, s_address, descrip) values ('Glass Blowing Pit', '266 Barnett Way', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Ceramic Kiln', '6 Doe Crossing Court', 'Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Textile Mill', '8 Westerfield Place', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Weaving Shed', '17126 Transport Trail', 'Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Fashion Atelier', '07 Oak Valley Alley', 'Proin risus.');
insert into STATION (s_name, s_address, descrip) values ('Runway Backstage', '19 Chive Plaza', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Makeup Mirror', '825 Anderson Pass', 'Etiam pretium iaculis justo. In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Costume Trunk', '589 Mallard Park', 'Nam dui. Proin leo odio, porttitor id, consequat in, consequat ut, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Prop Room', '9607 Eagle Crest Point', 'Maecenas ut massa quis augue luctus tincidunt.');
insert into STATION (s_name, s_address, descrip) values ('Scene Shop', '166 Dahle Point', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Rehearsal Hall', '4 Pearson Junction', 'Nulla ac enim.');
insert into STATION (s_name, s_address, descrip) values ('Orchestra Pit', '7325 Warbler Pass', 'Aliquam non mauris.');
insert into STATION (s_name, s_address, descrip) values ('Sheet Music Library', '28 Kropf Center', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Instrument Vault', '70 Eliot Circle', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue.');
insert into STATION (s_name, s_address, descrip) values ('Piano Room', '62 Logan Avenue', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor.');
insert into STATION (s_name, s_address, descrip) values ('Recording Booth', '225 Grim Center', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Soundboard', '91 Browning Alley', 'Fusce consequat. Nulla nisl.');
insert into STATION (s_name, s_address, descrip) values ('Mixer Station', '0 Sloan Park', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.');
insert into STATION (s_name, s_address, descrip) values ('DJ Booth', '67016 Hagan Circle', 'Morbi a ipsum. Integer a nibh.');
insert into STATION (s_name, s_address, descrip) values ('Dance Floor', '35 Main Hill', 'Suspendisse potenti.');
insert into STATION (s_name, s_address, descrip) values ('Nightclub Entry', '44316 Westport Point', 'In blandit ultrices enim.');
insert into STATION (s_name, s_address, descrip) values ('VIP Lounge', '14923 Mallard Court', 'Nunc nisl. Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Cocktail Bar', '290 Delladonna Road', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Mixology Station', '1 Saint Paul Alley', 'In sagittis dui vel nisl. Duis ac nibh.');
insert into STATION (s_name, s_address, descrip) values ('Wine Cellar Door', '1422 Burrows Crossing', 'Aenean sit amet justo.');
insert into STATION (s_name, s_address, descrip) values ('Sommelier Desk', '07 Vera Terrace', 'Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Cheese Aging Room', '66 Ronald Regan Center', 'Integer ac leo.');
insert into STATION (s_name, s_address, descrip) values ('Curing Room', '60573 Holmberg Park', 'Cras in purus eu magna vulputate luctus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.');
insert into STATION (s_name, s_address, descrip) values ('Smokehouse', '474 Corben Pass', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.');
insert into STATION (s_name, s_address, descrip) values ('Fermentation Lab', '4574 Randy Drive', 'In quis justo.');
insert into STATION (s_name, s_address, descrip) values ('Distillation Column', '4 Old Shore Street', 'Morbi vel lectus in quam fringilla rhoncus.');
insert into STATION (s_name, s_address, descrip) values ('Barrel Room', '6 Porter Plaza', 'Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Bottling Line', '6354 Warrior Alley', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue.');
insert into STATION (s_name, s_address, descrip) values ('Labeling Station', '254 Mesta Hill', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla.');
insert into STATION (s_name, s_address, descrip) values ('Distribution Center', '09 Lunder Trail', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est.');
insert into STATION (s_name, s_address, descrip) values ('Export Dock', '725 Vahlen Place', 'Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Customs Office', '900 Grayhawk Alley', 'Nullam sit amet turpis elementum ligula vehicula consequat.');
insert into STATION (s_name, s_address, descrip) values ('Immigration Gate', '164 Nancy Street', 'Maecenas tincidunt lacus at velit.');
insert into STATION (s_name, s_address, descrip) values ('Duty Free Lane', '53801 Truax Pass', 'Aliquam erat volutpat.');
insert into STATION (s_name, s_address, descrip) values ('Transit Lounge', '70503 Calypso Parkway', 'Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Boarding Gate', '82995 Moose Place', 'Aenean auctor gravida sem.');
insert into STATION (s_name, s_address, descrip) values ('Runway Threshold', '56 Spenser Road', 'Nullam porttitor lacus at turpis.');
insert into STATION (s_name, s_address, descrip) values ('Windsock', '22 Toban Trail', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Fuel Depot', '47 Luster Hill', 'Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Maintenance Bay', '5 Novick Street', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Engine Shop', '039 Oriole Center', 'Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.');
insert into STATION (s_name, s_address, descrip) values ('Spare Parts Rack', '240 Nelson Circle', 'Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Tool Crib', '6 Anzinger Lane', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa.');
insert into STATION (s_name, s_address, descrip) values ('Safety Station', '3630 Nobel Crossing', 'Curabitur convallis. Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('First Aid Post', '523 Anderson Pass', 'Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam.');
insert into STATION (s_name, s_address, descrip) values ('Triage Center', '1 Spohn Drive', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Medical Lab', '75622 Sunnyside Parkway', 'Praesent blandit.');
insert into STATION (s_name, s_address, descrip) values ('Radiology Wing', '3 Miller Pass', 'Etiam faucibus cursus urna. Ut tellus.');
insert into STATION (s_name, s_address, descrip) values ('Surgery Suite', '499 Linden Point', 'Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Recovery Room', '23 Farwell Avenue', 'Nullam varius. Nulla facilisi.');
insert into STATION (s_name, s_address, descrip) values ('Wellness Spa', '9 Cottonwood Crossing', 'Nulla facilisi. Cras non velit nec nisi vulputate nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Sauna Entrance', '72 Talisman Pass', 'In est risus, auctor sed, tristique in, tempus sit amet, sem. Fusce consequat.');
insert into STATION (s_name, s_address, descrip) values ('Steam Room', '212 Hovde Hill', 'Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Ice Bath', '5243 Upham Trail', 'Nunc rhoncus dui vel sem.');
insert into STATION (s_name, s_address, descrip) values ('Hydrotherapy Pool', '10736 2nd Way', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.');
insert into STATION (s_name, s_address, descrip) values ('Infinity Edge', '761 Oxford Road', 'Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.');
insert into STATION (s_name, s_address, descrip) values ('Sun Deck', '62 Declaration Court', 'Cras pellentesque volutpat dui.');
insert into STATION (s_name, s_address, descrip) values ('Cabana Row', '84 Forest Dale Way', 'Duis mattis egestas metus. Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Beach Bar', '4788 Warner Place', 'Maecenas pulvinar lobortis est. Phasellus sit amet erat.');
insert into STATION (s_name, s_address, descrip) values ('Volleyball Court', '0 Lawn Court', 'Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros. Vestibulum ac est lacinia nisi venenatis tristique.');
insert into STATION (s_name, s_address, descrip) values ('Tennis Net', '73 Nova Drive', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into STATION (s_name, s_address, descrip) values ('Basketball Hoop', '3486 Harper Lane', 'Aenean sit amet justo. Morbi ut odio.');
insert into STATION (s_name, s_address, descrip) values ('Goal Post', '664 Prairie Rose Pass', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit.');
insert into STATION (s_name, s_address, descrip) values ('Scoreboard', '38882 Mcguire Drive', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Referee Stand', '37 Warner Plaza', 'Sed accumsan felis.');
insert into STATION (s_name, s_address, descrip) values ('Coach’s Bench', '1 Drewry Circle', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum.');
insert into STATION (s_name, s_address, descrip) values ('Athlete Tunnel', '6316 Westend Park', 'Phasellus sit amet erat. Nulla tempus.');
insert into STATION (s_name, s_address, descrip) values ('Press Conference Room', '78 Anniversary Place', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Media Zone', '5 Karstens Parkway', 'Etiam vel augue. Vestibulum rutrum rutrum neque.');
insert into STATION (s_name, s_address, descrip) values ('Interview Wall', '334 Cascade Crossing', 'Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci.');
insert into STATION (s_name, s_address, descrip) values ('Hall of Fame', '11 Red Cloud Place', 'Pellentesque ultrices mattis odio.');
insert into STATION (s_name, s_address, descrip) values ('Legend Statues', '13142 Coolidge Pass', 'Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.');
insert into STATION (s_name, s_address, descrip) values ('Timeline Wall', '5324 West Point', 'Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Archive Basement', '89789 Bluestem Road', 'Donec vitae nisi.');
insert into STATION (s_name, s_address, descrip) values ('Records Room', '1 Old Shore Park', 'Aliquam erat volutpat. In congue.');
insert into STATION (s_name, s_address, descrip) values ('Digital Vault', '35607 Dwight Road', 'Quisque ut erat. Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Cryptography Cell', '90 Fordem Alley', 'Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.');
insert into STATION (s_name, s_address, descrip) values ('Underground Bunker', '27034 Johnson Crossing', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla.');
insert into STATION (s_name, s_address, descrip) values ('Operations Center', '0 Debs Center', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Situation Room', '35 Spenser Court', 'Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante.');
insert into STATION (s_name, s_address, descrip) values ('Strategy Table', '63 Carpenter Avenue', 'Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('War Room', '5586 Esker Park', 'Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.');
insert into STATION (s_name, s_address, descrip) values ('Command Post', '0 Badeau Crossing', 'Phasellus in felis.');
insert into STATION (s_name, s_address, descrip) values ('Tactical Bay', '8556 Springview Drive', 'Aliquam quis turpis eget elit sodales scelerisque.');
insert into STATION (s_name, s_address, descrip) values ('Armor Rack', '444 Ludington Court', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Shield Wall', '781 Briar Crest Street', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros.');
insert into STATION (s_name, s_address, descrip) values ('Watchtower Top', '2 Coolidge Place', 'Curabitur gravida nisi at nibh.');
insert into STATION (s_name, s_address, descrip) values ('Parapet', '4 Westend Trail', 'Donec quis orci eget orci vehicula condimentum. Curabitur in libero ut massa volutpat convallis.');
insert into STATION (s_name, s_address, descrip) values ('Battlement', '7207 Anzinger Court', 'Nulla suscipit ligula in lacus. Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Drawbridge', '8953 Grim Plaza', 'Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.');
insert into STATION (s_name, s_address, descrip) values ('Moat Edge', '46236 Everett Road', 'Proin eu mi.');
insert into STATION (s_name, s_address, descrip) values ('Keep Entrance', '456 Mayfield Park', 'Duis consequat dui nec nisi volutpat eleifend.');
insert into STATION (s_name, s_address, descrip) values ('Great Hall', '791 Hagan Terrace', 'Aenean fermentum.');
insert into STATION (s_name, s_address, descrip) values ('Kitchen Hearth', '36132 Division Street', 'Cras in purus eu magna vulputate luctus.');
insert into STATION (s_name, s_address, descrip) values ('Servant Quarters', '0 Doe Crossing Crossing', 'Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Stables', '57 Carpenter Parkway', 'Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede. Morbi porttitor lorem id ligula.');
insert into STATION (s_name, s_address, descrip) values ('Hay Loft', '04488 Red Cloud Alley', 'Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Paddock Gate', '77 Charing Cross Crossing', 'Etiam pretium iaculis justo.');
insert into STATION (s_name, s_address, descrip) values ('Training Ring', '18530 Reindahl Road', 'Quisque ut erat.');
insert into STATION (s_name, s_address, descrip) values ('Smithy', '12 Scoville Road', 'Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo.');
insert into STATION (s_name, s_address, descrip) values ('Armorer’s Bench', '43300 La Follette Park', 'Donec ut mauris eget massa tempor convallis.');
insert into STATION (s_name, s_address, descrip) values ('Fletcher’s Shop', '71 Pleasure Terrace', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo.');
insert into STATION (s_name, s_address, descrip) values ('Herbalist Garden', '9 Cody Road', 'Vivamus vestibulum sagittis sapien.');
insert into STATION (s_name, s_address, descrip) values ('Apothecary Shelf', '7503 Fordem Hill', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy.');
insert into STATION (s_name, s_address, descrip) values ('Alchemy Table', '89 Sage Way', 'Nunc purus.');
insert into STATION (s_name, s_address, descrip) values ('Crystal Chamber', '6815 Hoffman Junction', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem.');
insert into STATION (s_name, s_address, descrip) values ('Ritual Circle', '4 Carpenter Point', 'Suspendisse accumsan tortor quis turpis. Sed ante.');
insert into STATION (s_name, s_address, descrip) values ('Rune Stone', '3831 Chive Lane', 'Proin at turpis a pede posuere nonummy. Integer non velit.');
insert into STATION (s_name, s_address, descrip) values ('Oracle Seat', '9 Birchwood Pass', 'Praesent blandit. Nam nulla.');
insert into STATION (s_name, s_address, descrip) values ('Temple Altar', '47421 Center Trail', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Sacred Spring', '3673 Fisk Junction', 'Vivamus tortor. Duis mattis egestas metus.');
insert into STATION (s_name, s_address, descrip) values ('Pilgrim Path', '7054 Loeprich Court', 'Donec dapibus. Duis at velit eu est congue elementum.');
insert into STATION (s_name, s_address, descrip) values ('Hermit Cave', '42 Old Gate Street', 'Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.');
insert into STATION (s_name, s_address, descrip) values ('Meditation Rock', '22 Carpenter Park', 'Aenean lectus. Pellentesque eget nunc.');
insert into STATION (s_name, s_address, descrip) values ('Mountain Pass', '1 Golden Leaf Terrace', 'Curabitur at ipsum ac tellus semper interdum.');
insert into STATION (s_name, s_address, descrip) values ('Valley Floor', '4417 Fairfield Hill', 'Nullam molestie nibh in lectus. Pellentesque at nulla.');
insert into STATION (s_name, s_address, descrip) values ('River Bend', '504 Schlimgen Point', 'Sed accumsan felis. Ut at dolor quis odio consequat varius.');
insert into STATION (s_name, s_address, descrip) values ('Stream Bed', '1244 Graedel Way', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Pebble Bank', '73472 Troy Crossing', 'Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.');
insert into STATION (s_name, s_address, descrip) values ('Sand Bar', '93196 Dixon Terrace', 'Sed vel enim sit amet nunc viverra dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Tide Pool', '83 Golf Course Crossing', 'In hac habitasse platea dictumst.');
insert into STATION (s_name, s_address, descrip) values ('Kelp Forest', '33047 Fairview Drive', 'Praesent lectus.');
insert into STATION (s_name, s_address, descrip) values ('Deep Trench', '5674 La Follette Road', 'Donec dapibus.');
insert into STATION (s_name, s_address, descrip) values ('Underwater Cave', '80 Jana Plaza', 'Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis. Fusce posuere felis sed lacus.');
insert into STATION (s_name, s_address, descrip) values ('Sunken Wreck', '1 Mcbride Center', 'Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.');
insert into STATION (s_name, s_address, descrip) values ('Reef Edge', '3064 Elmside Alley', 'Duis at velit eu est congue elementum.');
