insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('City Pulse Walk', 41, 205, 'Sightseeing', 'Berlin Mitte', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Urban Legends Tour', 14, 213, 'Sightseeing', 'Santorini', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Concrete Jungle', 29, 182, 'Sightseeing', 'Venice Canals', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skyline Spectacle', 50, 73, 'Sightseeing', 'Amsterdam Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Metro Magic', 50, 140, 'Hiking', 'Santorini', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hidden Alleys', 22, 47, 'Hiking', 'Yellowstone Park', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Downtown Discovery', 33, 211, 'Hiking', 'Tel Aviv Coastline', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Grand Boulevard', 42, 172, 'Hiking', 'Bali Jungles', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('City Lights & Nights', 50, 111, 'Hiking', 'Grand Canyon', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Street Smart Saunter', 50, 192, 'Hiking', 'Prague Castle District', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pavement Perspectives', 11, 11, 'Hiking', 'Florence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Landmark Loop', 45, 185, 'Hiking', 'Grand Canyon', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Central Circuit', 32, 212, 'Hiking', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Borough Best', 37, 116, 'Hiking', 'Dublin Liberties', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('District Delights', 43, 191, 'Hiking', 'Madrid Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Capital Chronicles', 12, 55, 'Hiking', 'Vancouver Waterfront', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Metropolitan Mosaic', 20, 140, 'Hiking', 'Kyoto Temples', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sky-High Views', 32, 195, 'Sightseeing', 'Edinburgh Royal Mile', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Main Street Memories', 46, 30, 'Hiking', 'Vienna City Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Vibrant Village', 23, 141, 'Hiking', 'Vancouver Waterfront', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Town Square Tales', 33, 21, 'Sightseeing', 'Madrid Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Avenue Adventures', 37, 188, 'Hiking', 'Barcelona Gothic Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Modern Metropolis', 25, 3, 'Hiking', 'Swiss Alps', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The City Soul', 16, 53, 'Hiking', 'Amsterdam Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Urban Oasis Hunt', 40, 204, 'Sightseeing', 'Tel Aviv Coastline', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Neighborhood Nuances', 29, 6, 'Hiking', 'Swiss Alps', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Daily Grind', 40, 45, 'Hiking', 'Kyoto Temples', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sidewalk Stories', 40, 141, 'Sightseeing', 'Barcelona Gothic Quarter', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Crosswalk Culture', 35, 89, 'Sightseeing', 'Athens Acropolis', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Public Plaza Parade', 27, 112, 'Hiking', 'New Orleans', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Architectural Arc', 43, 28, 'Hiking', 'Seoul City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skyline Shadows', 49, 91, 'Sightseeing', 'Yellowstone Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Neon Nights', 14, 91, 'Sightseeing', 'Sydney Harbour', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brick & Mortar', 50, 84, 'Hiking', 'Santorini', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The City Core', 22, 179, 'Hiking', 'Cape Town Coast', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Waterfront Wonders', 44, 148, 'Hiking', 'Cairo Giza', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dockside Dreams', 15, 124, 'Sightseeing', 'Rome City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pier Perspectives', 18, 20, 'Sightseeing', 'Tel Aviv Coastline', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Harbor Highlights', 46, 224, 'Hiking', 'Venice Canals', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bridge & Tunnel', 16, 39, 'Hiking', 'Tokyo Shibuya', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The High-Rise Hike', 41, 29, 'Sightseeing', 'Madrid Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Alleyway Aesthetics', 15, 107, 'Sightseeing', 'French Quarter', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Subway Secrets', 17, 222, 'Hiking', 'Madrid Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Transit Triumphs', 23, 243, 'Hiking', 'Reykjavik', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Park & Promenade', 20, 187, 'Hiking', 'Cairo Giza', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Civic Center', 36, 28, 'Sightseeing', 'New Orleans', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cultural Quarter', 11, 72, 'Hiking', 'Vancouver Waterfront', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Entertainment District', 27, 178, 'Hiking', 'Hong Kong Island', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Financial Frontier', 38, 168, 'Sightseeing', 'Tokyo Shibuya', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Old Town Origins', 46, 73, 'Hiking', 'Amalfi Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Heritage Highlights', 20, 131, 'Hiking', 'Yosemite Valley', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancient Echoes', 11, 221, 'Sightseeing', 'Tel Aviv Coastline', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Timeless Traditions', 21, 59, 'Sightseeing', 'Machu Picchu', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Legacy Path', 25, 164, 'Sightseeing', 'Petra', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Roots & Routes', 21, 19, 'Hiking', 'Seoul City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('History Unveiled', 33, 133, 'Hiking', 'Dublin Liberties', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Past Perfect', 44, 128, 'Sightseeing', 'Santorini', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancestral Avenues', 17, 193, 'Hiking', 'Patagonia', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cultural Crossroads', 48, 219, 'Sightseeing', 'Dublin City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Folklore Follow', 44, 229, 'Hiking', 'Machu Picchu', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dynasty Discovery', 21, 90, 'Sightseeing', 'Vienna City Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Empire Eras', 31, 194, 'Hiking', 'Central Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Medieval Mysteries', 44, 16, 'Sightseeing', 'Amsterdam Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Renaissance Revelations', 44, 132, 'Hiking', 'Dublin City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Colonial Chronicles', 42, 10, 'Sightseeing', 'Dublin City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Landmark Lore', 10, 12, 'Hiking', 'Vienna City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Museum Mile', 22, 96, 'Sightseeing', 'Singapore Marina', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Monumental Moments', 33, 40, 'Sightseeing', 'Sydney Harbour', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sacred Sites', 33, 226, 'Sightseeing', 'Yosemite Valley', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Temple Trails', 41, 194, 'Hiking', 'Amsterdam Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cathedral Corners', 36, 121, 'Hiking', 'Rome City Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fortress Finds', 30, 144, 'Sightseeing', 'Reykjavik', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Castle Conquest', 11, 206, 'Hiking', 'Dublin City', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Palace Perspectives', 13, 144, 'Sightseeing', 'Patagonia', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ruins & Relics', 45, 241, 'Sightseeing', 'Dublin City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Antique Adventures', 13, 211, 'Hiking', 'New Orleans', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Golden Age', 16, 59, 'Hiking', 'Edinburgh Royal Mile', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vintage Voyage', 11, 88, 'Sightseeing', 'Amsterdam Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retro Road', 20, 12, 'Hiking', 'Old Town Prague', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Classic Culture', 38, 40, 'Hiking', 'Yosemite Valley', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Patriot Path', 41, 203, 'Hiking', 'Barcelona Gothic Quarter', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Liberty Lane', 45, 75, 'Sightseeing', 'Barcelona Las Ramblas', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Freedom Frontier', 12, 120, 'Hiking', 'Venice Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('War & Peace Walk', 28, 238, 'Hiking', 'Provence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Industrial Icons', 24, 83, 'Hiking', 'Hong Kong Island', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Victorian Views', 19, 118, 'Hiking', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Baroque Beauty', 40, 144, 'Hiking', 'Manhattan', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gothic Glories', 21, 50, 'Sightseeing', 'French Quarter', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancient Artifacts', 50, 3, 'Hiking', 'Dubai Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tribal Tracks', 22, 19, 'Sightseeing', 'Vancouver Waterfront', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Indigenous Insight', 24, 243, 'Sightseeing', 'Scottish Highlands', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Tradition Trail', 14, 96, 'Hiking', 'Hong Kong Island', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Masterpiece Morning', 32, 11, 'Sightseeing', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gallery Gazing', 15, 7, 'Hiking', 'Bali Jungles', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Curated Culture', 15, 77, 'Hiking', 'Patagonia', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Heritage Hues', 27, 216, 'Sightseeing', 'Kyoto Temples', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The History Hut', 43, 238, 'Sightseeing', 'Singapore Marina', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Epoch Explorations', 30, 180, 'Sightseeing', 'Machu Picchu', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Century Circuit', 27, 50, 'Sightseeing', 'Singapore Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Time Traveler’s Trek', 44, 248, 'Sightseeing', 'Provence', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wild Wanderer', 37, 36, 'Sightseeing', 'Dublin City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nature’s Nook', 46, 84, 'Hiking', 'Provence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Forest Frontiers', 45, 76, 'Sightseeing', 'Kyoto Temples', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mountain Majesty', 15, 99, 'Hiking', 'Amalfi Coast', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Valley Views', 45, 26, 'Sightseeing', 'Berlin Mitte', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Canyon Conquest', 12, 215, 'Hiking', 'Cape Town Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('River Rapids', 45, 203, 'Sightseeing', 'Amsterdam Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Lake Liberty', 21, 196, 'Sightseeing', 'Old Town Prague', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ocean Odysseys', 22, 137, 'Sightseeing', 'Florence', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Coastal Currents', 40, 184, 'Sightseeing', 'Grand Canyon', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Island Intervals', 15, 155, 'Sightseeing', 'New Orleans', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Jungle Jaunt', 26, 42, 'Hiking', 'Yellowstone Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Safari Solitude', 17, 32, 'Sightseeing', 'Tel Aviv Coastline', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Desert Dreams', 31, 225, 'Hiking', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Oasis Observations', 14, 135, 'Hiking', 'Rome City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Summit Seekers', 23, 84, 'Sightseeing', 'Istanbul Sultanahmet', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Trailblazer Tracks', 14, 96, 'Sightseeing', 'Rome City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Backcountry Bliss', 47, 139, 'Sightseeing', 'Reykjavik', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wilderness Way', 37, 249, 'Hiking', 'Yosemite Valley', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Flora & Fauna', 39, 106, 'Sightseeing', 'Provence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Botanical Best', 22, 62, 'Hiking', 'Florence', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Garden Glimpse', 15, 30, 'Sightseeing', 'Munich Old Town', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bloom & Blossom', 19, 160, 'Hiking', 'Scottish Highlands', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunrise Safari', 47, 102, 'Hiking', 'Central Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunset Serenity', 43, 160, 'Hiking', 'Yosemite Valley', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Starlight Sojourn', 21, 141, 'Hiking', 'Jerusalem Old City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Moonlight Meadow', 25, 212, 'Hiking', 'Yellowstone Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Eco-Explorer', 27, 33, 'Hiking', 'Barcelona Las Ramblas', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Green Getaway', 25, 54, 'Sightseeing', 'Prague Castle District', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sustainable Steps', 27, 21, 'Sightseeing', 'Yellowstone Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Great Outdoors', 50, 144, 'Hiking', 'Dublin City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Peak Performance', 44, 206, 'Sightseeing', 'Athens Acropolis', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ridge Runner', 18, 1, 'Sightseeing', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Meadow Muse', 31, 66, 'Hiking', 'Vienna City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Waterfall Wonders', 36, 159, 'Hiking', 'Amsterdam Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Stream Side Saunter', 14, 42, 'Hiking', 'Provence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Marshland Magic', 18, 89, 'Hiking', 'Munich Old Town', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Coastal Cliffs', 45, 64, 'Sightseeing', 'Patagonia', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sandy Shores', 25, 109, 'Sightseeing', 'Santorini', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Reef Revelations', 39, 118, 'Hiking', 'Dubai Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Arctic Adventures', 42, 197, 'Sightseeing', 'Dublin City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tundra Trails', 11, 139, 'Sightseeing', 'Petra', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Savanna Stroll', 16, 36, 'Hiking', 'Hong Kong Island', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rainforest Rhythms', 11, 74, 'Sightseeing', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Woodland Walk', 35, 24, 'Sightseeing', 'Singapore Marina', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pine Path', 29, 212, 'Hiking', 'Scottish Highlands', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Highland Hike', 23, 157, 'Sightseeing', 'Jerusalem Old City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Lowland Loop', 35, 15, 'Hiking', 'Scottish Highlands', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Earthly Escapes', 12, 31, 'Hiking', 'Vancouver Waterfront', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Horizon Hunt', 19, 208, 'Sightseeing', 'Barcelona Las Ramblas', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Taste Buds Tour', 21, 124, 'Sightseeing', 'Tel Aviv Coastline', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Culinary Conquest', 39, 175, 'Sightseeing', 'Dublin City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gourmet Gazette', 20, 138, 'Hiking', 'Tokyo Shibuya', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Flavor Fusion', 23, 196, 'Sightseeing', 'Dubai Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Savory Steps', 40, 31, 'Hiking', 'Barcelona Gothic Quarter', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sweet Street', 13, 185, 'Sightseeing', 'Central Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pastry Path', 25, 226, 'Sightseeing', 'Florence', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Baker’s Best', 49, 245, 'Sightseeing', 'Florence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Spice Route', 33, 182, 'Sightseeing', 'Kyoto Temples', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Market Munchies', 10, 124, 'Sightseeing', 'Berlin Mitte', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Farm to Fork', 14, 231, 'Hiking', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vineyard Voyage', 18, 194, 'Hiking', 'Yosemite Valley', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Winery Wonders', 26, 226, 'Sightseeing', 'Hong Kong Island', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brewery Best', 38, 228, 'Sightseeing', 'Dublin City', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pub Crawl Classics', 43, 218, 'Sightseeing', 'Prague Castle District', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Coffee Culture', 20, 178, 'Sightseeing', 'Scottish Highlands', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tea Time Trails', 18, 241, 'Sightseeing', 'Hong Kong Island', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Street Food Safari', 35, 174, 'Hiking', 'Patagonia', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Local Larder', 13, 93, 'Sightseeing', 'Amsterdam Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Chef’s Choice', 13, 136, 'Sightseeing', 'Dubai Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kitchen Kingdom', 19, 11, 'Sightseeing', 'Berlin Mitte', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Epicurean Escape', 39, 135, 'Hiking', 'Swiss Alps', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Tasting Table', 38, 159, 'Sightseeing', 'Lisbon Hills', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gastronomy Guide', 16, 175, 'Hiking', 'Florence', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Artisan Appetizers', 33, 230, 'Sightseeing', 'Venice Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cheese Circuit', 45, 122, 'Hiking', 'Venice Canals', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Chocolate Chaser', 41, 75, 'Sightseeing', 'Central Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dessert Discovery', 30, 200, 'Hiking', 'Scottish Highlands', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Seafood Sojourn', 22, 112, 'Sightseeing', 'Berlin Mitte', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('BBQ Belt', 33, 195, 'Sightseeing', 'San Francisco Bay', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vegan Ventures', 41, 44, 'Sightseeing', 'Yellowstone Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Organic Outing', 12, 92, 'Sightseeing', 'Dubai Marina', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Exotic Eats', 36, 243, 'Hiking', 'Cape Town Coast', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Traditional Tastes', 43, 84, 'Sightseeing', 'Tokyo Shibuya', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fusion Finds', 29, 238, 'Sightseeing', 'London South Bank', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brunch Bunch', 42, 95, 'Hiking', 'Lisbon Hills', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dinner District', 14, 184, 'Hiking', 'Seoul City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Morning Morsels', 37, 148, 'Sightseeing', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nightcap Nibbles', 11, 16, 'Hiking', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Picnic Parade', 39, 32, 'Sightseeing', 'Lisbon Hills', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Orchard Outing', 37, 224, 'Hiking', 'Barcelona Gothic Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Berry Best', 31, 157, 'Sightseeing', 'Seoul City', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Harvest Highlights', 43, 150, 'Hiking', 'Rome City Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fermentation Find', 11, 102, 'Sightseeing', 'New Orleans', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Distilled Dreams', 13, 227, 'Sightseeing', 'Prague Castle District', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sommelier’s Secret', 31, 157, 'Hiking', 'Amsterdam Canals', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tapas Trek', 36, 16, 'Sightseeing', 'Jerusalem Old City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Noodle Night', 29, 125, 'Hiking', 'Cairo Giza', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pizza Path', 44, 84, 'Hiking', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Full Plate', 44, 28, 'Sightseeing', 'Paris Montmartre', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Artistic Avenues', 37, 67, 'Hiking', 'Cape Town Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Creative Corners', 40, 93, 'Hiking', 'Cairo Giza', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mural Magic', 40, 79, 'Hiking', 'Scottish Highlands', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Graffiti Gaze', 13, 53, 'Sightseeing', 'Singapore Marina', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sculpture Safari', 40, 203, 'Sightseeing', 'Provence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Studio Steps', 19, 70, 'Sightseeing', 'Cape Town Coast', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gallery Glow', 15, 233, 'Hiking', 'San Francisco Bay', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Masterpiece Muse', 46, 43, 'Sightseeing', 'Amsterdam Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Design District', 18, 162, 'Hiking', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Crafty Circuit', 39, 39, 'Sightseeing', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Canvas Culture', 42, 63, 'Sightseeing', 'Patagonia', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Palette Path', 12, 208, 'Sightseeing', 'Edinburgh Royal Mile', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brushstroke Best', 41, 244, 'Hiking', 'Santorini', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Abstract Adventures', 46, 176, 'Sightseeing', 'Athens Acropolis', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Surrealism Sojourn', 46, 211, 'Hiking', 'San Francisco Bay', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Modern Muse', 41, 212, 'Hiking', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Classic Canvas', 39, 129, 'Sightseeing', 'Singapore Marina', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Portrait Parade', 45, 249, 'Hiking', 'Prague Castle District', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Landscape Lore', 30, 243, 'Hiking', 'Amsterdam Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Photography Phantoms', 19, 247, 'Sightseeing', 'Prague Castle District', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Snapshot Safari', 13, 222, 'Hiking', 'Amsterdam Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Visual Voyage', 29, 36, 'Sightseeing', 'Athens Acropolis', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Aesthetic Arc', 27, 3, 'Hiking', 'Jerusalem Old City', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Color Conquest', 26, 42, 'Sightseeing', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pattern Path', 44, 105, 'Sightseeing', 'Dublin City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Texture Trails', 12, 5, 'Sightseeing', 'Old Town Prague', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Artisan Alley', 35, 153, 'Sightseeing', 'Bali Jungles', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Maker’s Mile', 35, 164, 'Hiking', 'Prague Castle District', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Handcrafted Highlights', 16, 240, 'Hiking', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pottery Path', 37, 163, 'Sightseeing', 'Jerusalem Old City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Textile Trek', 14, 116, 'Sightseeing', 'Tokyo Shibuya', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fashion Frontier', 18, 232, 'Hiking', 'Patagonia', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Runway Routes', 31, 94, 'Sightseeing', 'Yellowstone Park', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Style Saunter', 45, 7, 'Hiking', 'Swiss Alps', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vogue Voyage', 19, 58, 'Hiking', 'Central Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cinema Circuit', 40, 1, 'Sightseeing', 'Rome City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hollywood Hunt', 12, 183, 'Hiking', 'Florence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Film Frame Follow', 14, 228, 'Sightseeing', 'Reykjavik', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Musical Magic', 12, 103, 'Hiking', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rhythm Routes', 45, 181, 'Sightseeing', 'Lisbon Hills', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Jazz Jaunt', 31, 214, 'Sightseeing', 'French Quarter', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rock & Roll Road', 16, 176, 'Hiking', 'Amsterdam Canals', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Operatic Odyssey', 50, 25, 'Sightseeing', 'Machu Picchu', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Theater Thrills', 45, 141, 'Sightseeing', 'Dubai Marina', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Broadway Best', 40, 116, 'Hiking', 'Dubai Marina', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Backstage Bliss', 12, 62, 'Sightseeing', 'Tel Aviv Coastline', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Performance Path', 26, 218, 'Sightseeing', 'Old Town Prague', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Creative Currents', 40, 39, 'Hiking', 'Hong Kong Island', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Inspiration Island', 43, 116, 'Sightseeing', 'Venice Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Visionary Views', 47, 37, 'Hiking', 'Manhattan', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ghostly Gaze', 19, 61, 'Sightseeing', 'Reykjavik', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Haunted Highlights', 11, 9, 'Hiking', 'Venice Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Phantom Path', 23, 236, 'Hiking', 'Hong Kong Island', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mystery Mile', 39, 47, 'Hiking', 'Venice Canals', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Shadow Sojourn', 32, 21, 'Sightseeing', 'Jerusalem Old City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Midnight Murmurs', 31, 10, 'Hiking', 'Paris Montmartre', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cryptic Circuit', 48, 211, 'Sightseeing', 'Edinburgh Royal Mile', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dark District', 29, 221, 'Sightseeing', 'Sydney Harbour', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Eerie Echoes', 23, 152, 'Hiking', 'Grand Canyon', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Spooky Steps', 39, 81, 'Sightseeing', 'Florence', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Spirits of the Past', 18, 54, 'Hiking', 'New Orleans', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Legend Lore', 32, 199, 'Sightseeing', 'Rome City Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mythic Moments', 38, 12, 'Sightseeing', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Twilight Trails', 16, 175, 'Sightseeing', 'Dublin Liberties', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('After Dark Adventures', 12, 1, 'Hiking', 'Vancouver Waterfront', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Moonlit Mysteries', 11, 170, 'Hiking', 'Amsterdam Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Foggy Frontier', 41, 94, 'Sightseeing', 'Dublin City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Chilling Chronicles', 41, 118, 'Hiking', 'Swiss Alps', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Paranormal Parade', 22, 116, 'Hiking', 'London South Bank', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Supernatural Saunter', 20, 114, 'Sightseeing', 'New Orleans', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gothic Ghost Walk', 37, 39, 'Hiking', 'Dublin Liberties', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cemetery Secrets', 33, 76, 'Hiking', 'Barcelona Las Ramblas', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tombstone Tales', 36, 33, 'Sightseeing', 'Rome City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancient Anathemata', 31, 64, 'Hiking', 'Provence', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Forbidden Finds', 10, 242, 'Sightseeing', 'Grand Canyon', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Secret Societies', 33, 146, 'Hiking', 'Dublin City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hidden History', 16, 6, 'Sightseeing', 'Tokyo Shibuya', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Masked Magic', 36, 249, 'Sightseeing', 'Machu Picchu', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Illusion Island', 36, 133, 'Sightseeing', 'Petra', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Enigma Escape', 32, 122, 'Sightseeing', 'Kyoto Temples', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Puzzling Path', 34, 183, 'Hiking', 'Tel Aviv Coastline', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Riddle Routes', 32, 243, 'Sightseeing', 'Seoul City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Crime & Consequence', 50, 174, 'Sightseeing', 'Florence', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Detective District', 50, 244, 'Hiking', 'Amsterdam Canals', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Noir Night', 22, 57, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sleuth Steps', 33, 105, 'Sightseeing', 'Grand Canyon', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Underworld Unveiled', 21, 108, 'Sightseeing', 'Old Town Prague', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rogue Roads', 41, 162, 'Sightseeing', 'Santorini', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Outlaw Odysseys', 37, 66, 'Hiking', 'Dubai Marina', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pirate’s Path', 49, 187, 'Sightseeing', 'New Orleans', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Smuggler’s Secret', 39, 7, 'Sightseeing', 'Manhattan', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bandit Best', 19, 234, 'Sightseeing', 'Cape Town Coast', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cursed Corners', 35, 97, 'Hiking', 'Barcelona Gothic Quarter', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bewitched Boulevard', 11, 245, 'Hiking', 'Dubai Marina', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sorcerer’s Sojourn', 16, 134, 'Sightseeing', 'Paris Montmartre', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Alchemist’s Arc', 26, 34, 'Hiking', 'Provence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mystical Muse', 14, 96, 'Sightseeing', 'Berlin Mitte', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Oracle Outing', 19, 50, 'Hiking', 'Kyoto Temples', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tarot Trails', 46, 149, 'Hiking', 'Bali Jungles', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zodiac Zigzag', 13, 6, 'Hiking', 'Tel Aviv Coastline', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pedal Power', 21, 195, 'Sightseeing', 'Madrid Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cycle Circuit', 46, 141, 'Hiking', 'Central Park', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bike & Brew', 16, 104, 'Hiking', 'Patagonia', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Two-Wheel Trek', 27, 239, 'Sightseeing', 'London South Bank', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rolling Routes', 18, 205, 'Sightseeing', 'London South Bank', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Jogger’s Jaunt', 41, 240, 'Hiking', 'Petra', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Marathon Mile', 13, 169, 'Sightseeing', 'Vancouver Waterfront', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sprint Steps', 21, 250, 'Hiking', 'Old Town Prague', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Active Adventures', 46, 100, 'Sightseeing', 'Florence', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fitness Frontier', 12, 17, 'Hiking', 'Lisbon Hills', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wellness Walk', 48, 37, 'Hiking', 'Vancouver Waterfront', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Yoga Yard', 24, 222, 'Hiking', 'Istanbul Sultanahmet', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zen Zone', 50, 178, 'Sightseeing', 'Jerusalem Old City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mindful Movements', 18, 215, 'Sightseeing', 'Manhattan', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Serenity Steps', 37, 100, 'Sightseeing', 'Lisbon Hills', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kayak Quest', 29, 108, 'Hiking', 'Reykjavik', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Paddle Path', 26, 108, 'Hiking', 'Dubai Marina', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Surf & Sand', 32, 162, 'Hiking', 'Lisbon Hills', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sail Away', 32, 49, 'Hiking', 'Patagonia', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nautical Night', 42, 133, 'Sightseeing', 'Amsterdam Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skateboard Safari', 17, 119, 'Sightseeing', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rollerblade Routes', 30, 49, 'Sightseeing', 'Kyoto Temples', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Climb & Conquer', 10, 129, 'Sightseeing', 'Singapore Marina', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bouldering Best', 35, 196, 'Hiking', 'Athens Acropolis', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('High-Wire Hike', 47, 46, 'Sightseeing', 'Singapore Marina', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zip-Line Zeal', 12, 175, 'Sightseeing', 'Reykjavik', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Paraglide Path', 31, 50, 'Sightseeing', 'London South Bank', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Balloon Best', 24, 84, 'Hiking', 'Petra', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Aerial Adventures', 20, 250, 'Hiking', 'Central Park', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skydiving Sojourn', 21, 186, 'Hiking', 'Manhattan', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Deep Sea Discovery', 36, 206, 'Sightseeing', 'Vienna City Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Snorkel Steps', 17, 61, 'Hiking', 'Central Park', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Scuba Safari', 25, 249, 'Sightseeing', 'Scottish Highlands', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Underwater Universe', 17, 99, 'Sightseeing', 'Scottish Highlands', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Snowshoe Sojourn', 30, 81, 'Sightseeing', 'Machu Picchu', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ski Slope Safari', 44, 216, 'Hiking', 'Old Town Prague', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ice Rink Routes', 16, 242, 'Hiking', 'Manhattan', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Winter Wonderland', 12, 48, 'Sightseeing', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sporty Spectacle', 36, 134, 'Hiking', 'Vienna City Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Stadium Stars', 10, 145, 'Hiking', 'Swiss Alps', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Arena Arc', 36, 196, 'Sightseeing', 'Barcelona Gothic Quarter', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Game Day Glimpse', 44, 67, 'Hiking', 'Berlin Mitte', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fan Frontier', 39, 199, 'Sightseeing', 'Hong Kong Island', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Goal Line Gaze', 11, 228, 'Hiking', 'Tel Aviv Coastline', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Court Side Circuit', 23, 83, 'Sightseeing', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pitch Perspectives', 39, 109, 'Sightseeing', 'Swiss Alps', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Olympic Odyssey', 24, 0, 'Sightseeing', 'Kyoto Temples', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Champion’s Choice', 30, 47, 'Sightseeing', 'Tokyo Shibuya', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Victory Voyage', 16, 153, 'Hiking', 'Patagonia', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Endurance Escape', 42, 140, 'Hiking', 'Dublin Liberties', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Family Fun Fest', 31, 194, 'Sightseeing', 'Central Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kid-Friendly Kingdom', 34, 18, 'Sightseeing', 'Berlin Mitte', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Playful Path', 16, 219, 'Hiking', 'Manhattan', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Toy Town Tour', 25, 142, 'Sightseeing', 'Lisbon Hills', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Magic Mile', 23, 80, 'Hiking', 'Kyoto Temples', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wonderland Walk', 42, 69, 'Sightseeing', 'Central Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fantasy Frontier', 40, 205, 'Hiking', 'Lisbon Hills', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fairy Tale Follow', 45, 128, 'Sightseeing', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Storybook Steps', 16, 233, 'Hiking', 'Yellowstone Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Animal Adventures', 18, 145, 'Hiking', 'Jerusalem Old City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zoo Zone', 15, 129, 'Sightseeing', 'Machu Picchu', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Aquarium Arc', 49, 168, 'Sightseeing', 'Old Town Prague', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Petting Path', 31, 6, 'Sightseeing', 'Reykjavik', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wildlife Watch', 21, 224, 'Hiking', 'Kyoto Temples', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Picnic Party', 20, 11, 'Sightseeing', 'New Orleans', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Playground Parade', 29, 200, 'Hiking', 'New Orleans', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Carnival Circuit', 19, 234, 'Hiking', 'Berlin Mitte', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fairground Finds', 13, 220, 'Hiking', 'Yosemite Valley', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Theme Park Thrills', 14, 93, 'Sightseeing', 'Swiss Alps', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rollercoaster Routes', 17, 67, 'Hiking', 'Reykjavik', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Candy Cane Lane', 17, 18, 'Sightseeing', 'Provence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sweet Shop Sojourn', 46, 240, 'Sightseeing', 'Manhattan', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ice Cream Island', 26, 128, 'Hiking', 'Vancouver Waterfront', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Balloon Boulevard', 32, 185, 'Hiking', 'French Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Circus Celebrations', 15, 179, 'Sightseeing', 'Sydney Harbour', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Puppet Parade', 27, 221, 'Sightseeing', 'Dublin City', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Toy Box Trek', 20, 55, 'Sightseeing', 'Vancouver Waterfront', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Game On Garden', 48, 41, 'Hiking', 'Prague Castle District', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Puzzle Park', 16, 162, 'Sightseeing', 'Barcelona Gothic Quarter', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Maze Magic', 26, 74, 'Hiking', 'Manhattan', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Science Secrets', 42, 220, 'Hiking', 'Bali Jungles', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Discovery District', 48, 119, 'Sightseeing', 'Yellowstone Park', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Inventor’s Island', 13, 196, 'Sightseeing', 'Yosemite Valley', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Robot Routes', 11, 151, 'Hiking', 'Munich Old Town', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Space Safari', 43, 75, 'Hiking', 'Amsterdam Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Planetarium Path', 21, 29, 'Sightseeing', 'Swiss Alps', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rocket Road', 32, 101, 'Sightseeing', 'Florence', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dino Discovery', 50, 234, 'Sightseeing', 'Edinburgh Royal Mile', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fossil Find', 30, 32, 'Hiking', 'Barcelona Gothic Quarter', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Prehistoric Path', 30, 155, 'Hiking', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Knight’s Quest', 34, 181, 'Sightseeing', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Princess Parade', 44, 17, 'Hiking', 'Amalfi Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wizard’s Walk', 20, 116, 'Hiking', 'Prague Castle District', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Superhero Steps', 45, 90, 'Hiking', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cartoon Circuit', 24, 190, 'Hiking', 'Prague Castle District', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hobby Horse Hunt', 27, 146, 'Hiking', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kite Krusade', 32, 46, 'Sightseeing', 'Barcelona Las Ramblas', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bubble Boulevard', 26, 149, 'Hiking', 'Munich Old Town', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Treasure Trove', 49, 156, 'Sightseeing', 'Dublin Liberties', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gold Mine Gaze', 29, 243, 'Hiking', 'Lisbon Hills', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Luxury Lane', 39, 172, 'Sightseeing', 'Provence', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Elegant Escapes', 34, 128, 'Hiking', 'London South Bank', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Posh Path', 38, 167, 'Hiking', 'Florence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Diamond District', 38, 113, 'Hiking', 'Vancouver Waterfront', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Golden Glimpse', 18, 195, 'Sightseeing', 'Amalfi Coast', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Velvet Voyage', 34, 229, 'Hiking', 'Petra', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Silk Road Saunter', 26, 76, 'Sightseeing', 'Hong Kong Island', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('High Society Sojourn', 21, 236, 'Sightseeing', 'Manhattan', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Boutique Best', 42, 9, 'Hiking', 'Yellowstone Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retail Revelations', 21, 98, 'Hiking', 'Tel Aviv Coastline', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Shopaholic Safari', 40, 19, 'Sightseeing', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Window Shopping Walk', 38, 219, 'Sightseeing', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fashion Forward', 46, 137, 'Hiking', 'Amalfi Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Glamour Gaze', 17, 24, 'Hiking', 'Bali Jungles', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Spa Serenity', 46, 75, 'Sightseeing', 'Dubai Marina', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wellness Wonders', 44, 179, 'Hiking', 'Swiss Alps', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retreat Routes', 37, 159, 'Sightseeing', 'London South Bank', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Relaxation Road', 38, 205, 'Hiking', 'Amsterdam Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tranquility Trail', 38, 93, 'Sightseeing', 'Yellowstone Park', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bliss Boulevard', 37, 4, 'Hiking', 'Paris Montmartre', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Resort Revelations', 41, 203, 'Hiking', 'Santorini', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hotel Highlights', 11, 74, 'Sightseeing', 'Rome City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Manor Muse', 22, 224, 'Sightseeing', 'London South Bank', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Estate Explorations', 23, 20, 'Hiking', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mansion Magic', 17, 181, 'Sightseeing', 'Istanbul Sultanahmet', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Penthouse Perspectives', 30, 41, 'Hiking', 'Amalfi Coast', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Yacht Yard', 29, 205, 'Sightseeing', 'Paris Montmartre', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Limousine Lore', 36, 84, 'Sightseeing', 'Edinburgh Royal Mile', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('First Class Follow', 48, 230, 'Hiking', 'Patagonia', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Elite Escapades', 20, 95, 'Sightseeing', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Private Paradise', 37, 194, 'Sightseeing', 'Old Town Prague', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Exclusive Echoes', 39, 143, 'Hiking', 'Seoul City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hidden Gems', 22, 121, 'Sightseeing', 'Amsterdam Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Secret Sanctuary', 50, 44, 'Sightseeing', 'Florence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Quiet Quarters', 28, 247, 'Sightseeing', 'Istanbul Sultanahmet', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Peaceful Path', 33, 27, 'Sightseeing', 'Cairo Giza', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Serene Sojourn', 50, 77, 'Hiking', 'Vancouver Waterfront', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Calm Currents', 33, 66, 'Sightseeing', 'Madrid Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gentle Gaze', 24, 38, 'Hiking', 'Amalfi Coast', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Leisurely Loop', 37, 199, 'Sightseeing', 'San Francisco Bay', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Slow Lane Saunter', 38, 69, 'Sightseeing', 'Patagonia', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Easy Breezy', 20, 199, 'Hiking', 'Paris Montmartre', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunny Side Up', 32, 167, 'Hiking', 'Jerusalem Old City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Carefree Circuit', 45, 50, 'Sightseeing', 'Machu Picchu', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Happy Hour Hunt', 42, 125, 'Sightseeing', 'San Francisco Bay', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunset Spirits', 17, 138, 'Sightseeing', 'Scottish Highlands', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Twilight Toast', 16, 7, 'Sightseeing', 'Cape Town Coast', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Evening Elegance', 14, 59, 'Hiking', 'Edinburgh Royal Mile', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nightfall Nuances', 47, 216, 'Hiking', 'Machu Picchu', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dreamy Destinations', 13, 249, 'Hiking', 'Kyoto Temples', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Oddity Odyssey', 18, 218, 'Hiking', 'Sydney Harbour', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Peculiar Path', 41, 234, 'Sightseeing', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Strange Steps', 36, 145, 'Sightseeing', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Weird & Wonderful', 36, 225, 'Hiking', 'Scottish Highlands', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Curious Circuit', 13, 194, 'Hiking', 'Cape Town Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bizarre Boulevard', 18, 241, 'Sightseeing', 'Bali Jungles', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Offbeat Outing', 30, 181, 'Sightseeing', 'Central Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Quirky Quarters', 18, 48, 'Hiking', 'New Orleans', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Unusual Universe', 42, 200, 'Sightseeing', 'Kyoto Temples', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rare Routes', 29, 112, 'Hiking', 'Vienna City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Eccentric Escapes', 41, 85, 'Hiking', 'San Francisco Bay', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Funky Frontier', 48, 243, 'Sightseeing', 'Old Town Prague', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retro Revival', 35, 41, 'Hiking', 'Barcelona Gothic Quarter', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kitsch Kingdom', 25, 228, 'Sightseeing', 'Florence', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vintage Vibes', 46, 10, 'Sightseeing', 'Reykjavik', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Thrift Shop Trek', 50, 1, 'Hiking', 'Edinburgh Royal Mile', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Flea Market Follow', 25, 155, 'Hiking', 'Cairo Giza', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Antique Arc', 15, 211, 'Sightseeing', 'Athens Acropolis', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Curiosities Circuit', 18, 173, 'Hiking', 'Seoul City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Collector’s Choice', 43, 22, 'Hiking', 'Paris Montmartre', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nerd Night', 37, 73, 'Hiking', 'Kyoto Temples', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Geek Gaze', 40, 196, 'Hiking', 'Scottish Highlands', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tech Trek', 40, 81, 'Sightseeing', 'Berlin Mitte', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Digital District', 25, 134, 'Hiking', 'Athens Acropolis', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Startup Safari', 37, 90, 'Sightseeing', 'Yellowstone Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Innovation Island', 30, 108, 'Hiking', 'Jerusalem Old City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Future Frontiers', 37, 56, 'Sightseeing', 'Venice Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sci-Fi Sojourn', 17, 21, 'Sightseeing', 'Provence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Steampunk Steps', 46, 182, 'Hiking', 'Vancouver Waterfront', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cyber Circuit', 15, 31, 'Hiking', 'Edinburgh Royal Mile', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Street Art Safari', 30, 32, 'Sightseeing', 'Prague Castle District', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vinyl Voyage', 49, 65, 'Sightseeing', 'Athens Acropolis', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Record Road', 15, 28, 'Hiking', 'Scottish Highlands', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bookworm Boulevard', 21, 70, 'Hiking', 'Dublin Liberties', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Library Lore', 42, 194, 'Sightseeing', 'Madrid Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Literary Legend', 37, 246, 'Sightseeing', 'Florence', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Writer’s Walk', 41, 128, 'Sightseeing', 'Provence', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Poet’s Path', 46, 95, 'Hiking', 'Scottish Highlands', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Language Lab', 18, 143, 'Sightseeing', 'Hong Kong Island', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Polyglot Parade', 28, 92, 'Sightseeing', 'Vancouver Waterfront', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Math Magic', 26, 173, 'Sightseeing', 'Dublin City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Geometry Gaze', 31, 89, 'Sightseeing', 'Manhattan', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Logic Lane', 14, 21, 'Hiking', 'Singapore Marina', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Soundscape Safari', 46, 189, 'Hiking', 'Singapore Marina', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Acoustic Adventures', 29, 211, 'Hiking', 'Tel Aviv Coastline', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Echo Exploration', 13, 112, 'Sightseeing', 'Dubai Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Shadow Steps', 26, 67, 'Hiking', 'London South Bank', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Reflection Routes', 28, 11, 'Sightseeing', 'Lisbon Hills', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mirror Magic', 20, 141, 'Hiking', 'Bali Jungles', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Final Frontier', 27, 198, 'Sightseeing', 'Santorini', 0, 4);