insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('City Pulse Walk', 47, 59, 'Sightseeing', 'Amsterdam Canals', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Urban Legends Tour', 49, 114, 'Sightseeing', 'Vienna City Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Concrete Jungle', 34, 18, 'Hiking', 'Tel Aviv Coastline', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skyline Spectacle', 46, 229, 'Hiking', 'Hong Kong Island', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Metro Magic', 42, 208, 'Hiking', 'Lisbon Hills', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hidden Alleys', 47, 116, 'Sightseeing', 'Berlin Mitte', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Downtown Discovery', 32, 49, 'Sightseeing', 'Central Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Grand Boulevard', 44, 100, 'Sightseeing', 'Berlin Mitte', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('City Lights & Nights', 36, 245, 'Hiking', 'Singapore Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Street Smart Saunter', 49, 220, 'Sightseeing', 'Prague Castle District', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pavement Perspectives', 43, 207, 'Sightseeing', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Landmark Loop', 41, 18, 'Hiking', 'Tokyo Shibuya', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Central Circuit', 39, 5, 'Sightseeing', 'Kyoto Temples', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Borough Best', 12, 193, 'Sightseeing', 'Jerusalem Old City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('District Delights', 35, 171, 'Sightseeing', 'Vienna City Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Capital Chronicles', 45, 146, 'Sightseeing', 'Bali Jungles', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Metropolitan Mosaic', 35, 133, 'Sightseeing', 'Athens Acropolis', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sky-High Views', 19, 91, 'Hiking', 'New Orleans', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Main Street Memories', 33, 41, 'Hiking', 'Cairo Giza', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Vibrant Village', 17, 36, 'Sightseeing', 'Amsterdam Canals', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Town Square Tales', 34, 182, 'Sightseeing', 'Scottish Highlands', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Avenue Adventures', 46, 77, 'Sightseeing', 'Santorini', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Modern Metropolis', 36, 171, 'Hiking', 'Jerusalem Old City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The City Soul', 19, 133, 'Sightseeing', 'Jerusalem Old City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Urban Oasis Hunt', 35, 188, 'Sightseeing', 'Edinburgh Royal Mile', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Neighborhood Nuances', 18, 136, 'Hiking', 'Rome City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Daily Grind', 44, 67, 'Hiking', 'Barcelona Gothic Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sidewalk Stories', 37, 89, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Crosswalk Culture', 38, 73, 'Hiking', 'Petra', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Public Plaza Parade', 26, 120, 'Hiking', 'Bali Jungles', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Architectural Arc', 16, 195, 'Sightseeing', 'Cairo Giza', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skyline Shadows', 47, 81, 'Hiking', 'Vancouver Waterfront', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Neon Nights', 45, 229, 'Hiking', 'New Orleans', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brick & Mortar', 25, 105, 'Hiking', 'Amalfi Coast', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The City Core', 35, 50, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Waterfront Wonders', 20, 66, 'Sightseeing', 'Tokyo Shibuya', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dockside Dreams', 15, 249, 'Hiking', 'Old Town Prague', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pier Perspectives', 14, 144, 'Hiking', 'Lisbon Hills', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Harbor Highlights', 47, 217, 'Sightseeing', 'Yellowstone Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bridge & Tunnel', 15, 169, 'Hiking', 'Athens Acropolis', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The High-Rise Hike', 17, 77, 'Sightseeing', 'Barcelona Las Ramblas', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Alleyway Aesthetics', 50, 10, 'Hiking', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Subway Secrets', 21, 0, 'Hiking', 'Grand Canyon', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Transit Triumphs', 22, 30, 'Sightseeing', 'Seoul City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Park & Promenade', 44, 121, 'Sightseeing', 'Sydney Harbour', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Civic Center', 41, 38, 'Sightseeing', 'Hong Kong Island', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cultural Quarter', 50, 248, 'Sightseeing', 'Kyoto Temples', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Entertainment District', 27, 79, 'Sightseeing', 'Madrid Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Financial Frontier', 13, 200, 'Sightseeing', 'Yosemite Valley', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Old Town Origins', 10, 122, 'Sightseeing', 'Santorini', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Heritage Highlights', 30, 6, 'Sightseeing', 'Swiss Alps', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancient Echoes', 12, 60, 'Hiking', 'Rome City Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Timeless Traditions', 21, 60, 'Hiking', 'Barcelona Las Ramblas', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Legacy Path', 41, 59, 'Hiking', 'Barcelona Las Ramblas', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Roots & Routes', 26, 242, 'Hiking', 'Bali Jungles', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('History Unveiled', 43, 248, 'Hiking', 'Manhattan', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Past Perfect', 35, 221, 'Hiking', 'Tel Aviv Coastline', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancestral Avenues', 37, 84, 'Sightseeing', 'Dublin Liberties', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cultural Crossroads', 13, 220, 'Hiking', 'Reykjavik', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Folklore Follow', 33, 125, 'Hiking', 'Manhattan', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dynasty Discovery', 47, 176, 'Sightseeing', 'Lisbon Hills', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Empire Eras', 42, 29, 'Hiking', 'Kyoto Temples', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Medieval Mysteries', 19, 181, 'Sightseeing', 'Barcelona Gothic Quarter', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Renaissance Revelations', 25, 26, 'Sightseeing', 'Barcelona Gothic Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Colonial Chronicles', 40, 132, 'Sightseeing', 'New Orleans', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Landmark Lore', 30, 144, 'Sightseeing', 'Dublin City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Museum Mile', 30, 31, 'Hiking', 'Tokyo Shibuya', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Monumental Moments', 28, 67, 'Sightseeing', 'Petra', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sacred Sites', 45, 154, 'Hiking', 'Dubai Marina', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Temple Trails', 15, 43, 'Sightseeing', 'Edinburgh Royal Mile', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cathedral Corners', 11, 114, 'Sightseeing', 'Dublin City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fortress Finds', 14, 97, 'Hiking', 'San Francisco Bay', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Castle Conquest', 36, 209, 'Sightseeing', 'Cairo Giza', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Palace Perspectives', 26, 29, 'Hiking', 'Prague Castle District', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ruins & Relics', 18, 46, 'Hiking', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Antique Adventures', 19, 76, 'Sightseeing', 'Reykjavik', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Golden Age', 27, 62, 'Hiking', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vintage Voyage', 41, 54, 'Sightseeing', 'Vienna City Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retro Road', 47, 12, 'Sightseeing', 'Manhattan', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Classic Culture', 22, 221, 'Hiking', 'Petra', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Patriot Path', 42, 146, 'Sightseeing', 'Central Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Liberty Lane', 48, 151, 'Hiking', 'Reykjavik', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Freedom Frontier', 46, 194, 'Sightseeing', 'Tel Aviv Coastline', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('War & Peace Walk', 42, 59, 'Hiking', 'Venice Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Industrial Icons', 28, 242, 'Hiking', 'Edinburgh Royal Mile', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Victorian Views', 50, 67, 'Hiking', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Baroque Beauty', 30, 198, 'Hiking', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gothic Glories', 14, 54, 'Hiking', 'Manhattan', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancient Artifacts', 12, 4, 'Hiking', 'New Orleans', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tribal Tracks', 12, 186, 'Sightseeing', 'Tokyo Shibuya', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Indigenous Insight', 18, 132, 'Sightseeing', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Tradition Trail', 31, 210, 'Hiking', 'Manhattan', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Masterpiece Morning', 26, 35, 'Hiking', 'Berlin Mitte', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gallery Gazing', 48, 166, 'Hiking', 'Kyoto Temples', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Curated Culture', 25, 221, 'Sightseeing', 'Florence', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Heritage Hues', 19, 82, 'Hiking', 'Tokyo Shibuya', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The History Hut', 46, 245, 'Hiking', 'Grand Canyon', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Epoch Explorations', 16, 27, 'Hiking', 'Amsterdam Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Century Circuit', 28, 88, 'Hiking', 'Provence', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Time Traveler’s Trek', 12, 139, 'Sightseeing', 'Dublin Liberties', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wild Wanderer', 16, 111, 'Hiking', 'Dublin Liberties', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nature’s Nook', 50, 110, 'Sightseeing', 'Provence', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Forest Frontiers', 31, 18, 'Hiking', 'French Quarter', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mountain Majesty', 32, 52, 'Hiking', 'Singapore Marina', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Valley Views', 34, 163, 'Hiking', 'Vancouver Waterfront', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Canyon Conquest', 35, 4, 'Sightseeing', 'Provence', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('River Rapids', 36, 82, 'Hiking', 'French Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Lake Liberty', 49, 139, 'Sightseeing', 'Cape Town Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ocean Odysseys', 20, 166, 'Sightseeing', 'Central Park', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Coastal Currents', 43, 187, 'Sightseeing', 'Amalfi Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Island Intervals', 37, 4, 'Sightseeing', 'Seoul City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Jungle Jaunt', 39, 138, 'Sightseeing', 'Reykjavik', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Safari Solitude', 21, 199, 'Sightseeing', 'Sydney Harbour', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Desert Dreams', 19, 54, 'Hiking', 'Barcelona Gothic Quarter', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Oasis Observations', 30, 99, 'Hiking', 'Machu Picchu', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Summit Seekers', 27, 168, 'Hiking', 'Hong Kong Island', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Trailblazer Tracks', 29, 86, 'Hiking', 'Cape Town Coast', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Backcountry Bliss', 30, 19, 'Sightseeing', 'Tokyo Shibuya', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wilderness Way', 48, 119, 'Hiking', 'Tel Aviv Coastline', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Flora & Fauna', 21, 224, 'Hiking', 'Cape Town Coast', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Botanical Best', 14, 194, 'Hiking', 'Manhattan', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Garden Glimpse', 39, 23, 'Sightseeing', 'Kyoto Temples', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bloom & Blossom', 43, 66, 'Sightseeing', 'San Francisco Bay', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunrise Safari', 23, 97, 'Hiking', 'Scottish Highlands', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunset Serenity', 16, 202, 'Sightseeing', 'Tokyo Shibuya', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Starlight Sojourn', 43, 214, 'Hiking', 'Singapore Marina', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Moonlight Meadow', 23, 62, 'Hiking', 'Cairo Giza', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Eco-Explorer', 13, 123, 'Hiking', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Green Getaway', 31, 47, 'Hiking', 'Dublin Liberties', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sustainable Steps', 19, 247, 'Sightseeing', 'New Orleans', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Great Outdoors', 37, 225, 'Sightseeing', 'Athens Acropolis', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Peak Performance', 35, 181, 'Hiking', 'Yellowstone Park', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ridge Runner', 14, 218, 'Sightseeing', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Meadow Muse', 49, 92, 'Sightseeing', 'Swiss Alps', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Waterfall Wonders', 32, 148, 'Hiking', 'Vienna City Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Stream Side Saunter', 18, 35, 'Hiking', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Marshland Magic', 23, 240, 'Sightseeing', 'Dublin Liberties', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Coastal Cliffs', 44, 163, 'Hiking', 'Machu Picchu', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sandy Shores', 15, 26, 'Sightseeing', 'Petra', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Reef Revelations', 31, 155, 'Hiking', 'Amsterdam Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Arctic Adventures', 48, 71, 'Sightseeing', 'Seoul City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tundra Trails', 39, 179, 'Hiking', 'Amsterdam Canals', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Savanna Stroll', 21, 37, 'Hiking', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rainforest Rhythms', 14, 125, 'Hiking', 'New Orleans', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Woodland Walk', 18, 244, 'Hiking', 'Petra', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pine Path', 35, 250, 'Hiking', 'Santorini', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Highland Hike', 13, 43, 'Hiking', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Lowland Loop', 24, 7, 'Hiking', 'Munich Old Town', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Earthly Escapes', 25, 72, 'Hiking', 'Reykjavik', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Horizon Hunt', 18, 249, 'Hiking', 'Manhattan', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Taste Buds Tour', 19, 117, 'Hiking', 'Swiss Alps', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Culinary Conquest', 17, 239, 'Sightseeing', 'Madrid Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gourmet Gazette', 31, 220, 'Hiking', 'Paris Montmartre', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Flavor Fusion', 45, 196, 'Sightseeing', 'Berlin Mitte', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Savory Steps', 13, 110, 'Hiking', 'Jerusalem Old City', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sweet Street', 36, 240, 'Sightseeing', 'Lisbon Hills', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pastry Path', 45, 32, 'Hiking', 'Amalfi Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Baker’s Best', 32, 3, 'Hiking', 'Petra', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Spice Route', 42, 207, 'Sightseeing', 'Florence', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Market Munchies', 29, 57, 'Hiking', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Farm to Fork', 31, 41, 'Sightseeing', 'Old Town Prague', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vineyard Voyage', 38, 122, 'Hiking', 'Patagonia', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Winery Wonders', 22, 36, 'Hiking', 'Cape Town Coast', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brewery Best', 12, 191, 'Sightseeing', 'Tel Aviv Coastline', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pub Crawl Classics', 46, 38, 'Sightseeing', 'Santorini', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Coffee Culture', 22, 39, 'Sightseeing', 'Petra', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tea Time Trails', 16, 38, 'Sightseeing', 'Vancouver Waterfront', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Street Food Safari', 40, 16, 'Sightseeing', 'Swiss Alps', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Local Larder', 38, 176, 'Sightseeing', 'Cape Town Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Chef’s Choice', 11, 246, 'Hiking', 'Reykjavik', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kitchen Kingdom', 25, 188, 'Hiking', 'Bali Jungles', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Epicurean Escape', 12, 6, 'Sightseeing', 'Tel Aviv Coastline', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Tasting Table', 17, 65, 'Hiking', 'Bali Jungles', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gastronomy Guide', 37, 13, 'Hiking', 'Scottish Highlands', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Artisan Appetizers', 38, 159, 'Hiking', 'Rome City Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cheese Circuit', 21, 216, 'Hiking', 'Petra', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Chocolate Chaser', 48, 82, 'Sightseeing', 'Paris Montmartre', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dessert Discovery', 22, 44, 'Hiking', 'London South Bank', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Seafood Sojourn', 38, 113, 'Hiking', 'Petra', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('BBQ Belt', 37, 102, 'Hiking', 'London South Bank', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vegan Ventures', 18, 7, 'Hiking', 'Istanbul Sultanahmet', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Organic Outing', 27, 198, 'Sightseeing', 'Sydney Harbour', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Exotic Eats', 31, 52, 'Sightseeing', 'Tel Aviv Coastline', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Traditional Tastes', 41, 119, 'Hiking', 'Dubai Marina', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fusion Finds', 44, 43, 'Hiking', 'Seoul City', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brunch Bunch', 18, 9, 'Sightseeing', 'London South Bank', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dinner District', 39, 211, 'Hiking', 'Prague Castle District', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Morning Morsels', 24, 207, 'Sightseeing', 'Athens Acropolis', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nightcap Nibbles', 38, 21, 'Sightseeing', 'Venice Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Picnic Parade', 47, 145, 'Hiking', 'Machu Picchu', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Orchard Outing', 25, 184, 'Hiking', 'Santorini', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Berry Best', 17, 67, 'Sightseeing', 'French Quarter', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Harvest Highlights', 48, 216, 'Hiking', 'Cape Town Coast', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fermentation Find', 29, 195, 'Sightseeing', 'Tel Aviv Coastline', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Distilled Dreams', 22, 135, 'Sightseeing', 'Munich Old Town', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sommelier’s Secret', 25, 61, 'Sightseeing', 'Manhattan', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tapas Trek', 28, 5, 'Sightseeing', 'Edinburgh Royal Mile', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Noodle Night', 18, 233, 'Sightseeing', 'Petra', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pizza Path', 48, 1, 'Sightseeing', 'Florence', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('The Full Plate', 34, 247, 'Hiking', 'Santorini', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Artistic Avenues', 16, 58, 'Hiking', 'Patagonia', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Creative Corners', 21, 223, 'Hiking', 'Athens Acropolis', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mural Magic', 41, 63, 'Hiking', 'Dubai Marina', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Graffiti Gaze', 30, 204, 'Hiking', 'Dubai Marina', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sculpture Safari', 33, 250, 'Hiking', 'Old Town Prague', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Studio Steps', 40, 176, 'Sightseeing', 'Hong Kong Island', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gallery Glow', 49, 151, 'Hiking', 'Central Park', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Masterpiece Muse', 38, 183, 'Hiking', 'Cairo Giza', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Design District', 17, 240, 'Hiking', 'Amsterdam Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Crafty Circuit', 50, 25, 'Hiking', 'Munich Old Town', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Canvas Culture', 18, 121, 'Sightseeing', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Palette Path', 45, 153, 'Hiking', 'Yosemite Valley', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Brushstroke Best', 11, 78, 'Sightseeing', 'Kyoto Temples', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Abstract Adventures', 28, 153, 'Sightseeing', 'Central Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Surrealism Sojourn', 24, 57, 'Hiking', 'Petra', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Modern Muse', 41, 72, 'Hiking', 'Reykjavik', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Classic Canvas', 26, 26, 'Sightseeing', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Portrait Parade', 22, 203, 'Sightseeing', 'Santorini', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Landscape Lore', 36, 192, 'Hiking', 'Rome City Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Photography Phantoms', 34, 131, 'Hiking', 'San Francisco Bay', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Snapshot Safari', 19, 87, 'Sightseeing', 'Grand Canyon', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Visual Voyage', 29, 229, 'Hiking', 'London South Bank', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Aesthetic Arc', 47, 27, 'Sightseeing', 'Venice Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Color Conquest', 26, 128, 'Sightseeing', 'French Quarter', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pattern Path', 17, 68, 'Hiking', 'Central Park', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Texture Trails', 48, 201, 'Sightseeing', 'Amalfi Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Artisan Alley', 27, 59, 'Hiking', 'Old Town Prague', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Maker’s Mile', 42, 190, 'Sightseeing', 'Venice Canals', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Handcrafted Highlights', 40, 158, 'Sightseeing', 'San Francisco Bay', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pottery Path', 39, 65, 'Hiking', 'Machu Picchu', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Textile Trek', 15, 178, 'Sightseeing', 'Lisbon Hills', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fashion Frontier', 13, 246, 'Sightseeing', 'Scottish Highlands', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Runway Routes', 43, 169, 'Hiking', 'Central Park', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Style Saunter', 40, 160, 'Hiking', 'Manhattan', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vogue Voyage', 36, 130, 'Hiking', 'Central Park', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cinema Circuit', 19, 149, 'Hiking', 'Florence', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hollywood Hunt', 50, 96, 'Hiking', 'Scottish Highlands', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Film Frame Follow', 25, 131, 'Hiking', 'Sydney Harbour', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Musical Magic', 37, 215, 'Hiking', 'Jerusalem Old City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rhythm Routes', 10, 149, 'Sightseeing', 'Barcelona Las Ramblas', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Jazz Jaunt', 32, 108, 'Sightseeing', 'Machu Picchu', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rock & Roll Road', 20, 77, 'Sightseeing', 'Edinburgh Royal Mile', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Operatic Odyssey', 11, 234, 'Hiking', 'Venice Canals', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Theater Thrills', 49, 116, 'Sightseeing', 'Berlin Mitte', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Broadway Best', 40, 31, 'Sightseeing', 'Amalfi Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Backstage Bliss', 15, 140, 'Hiking', 'Petra', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Performance Path', 29, 164, 'Sightseeing', 'Vienna City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Creative Currents', 48, 121, 'Hiking', 'Berlin Mitte', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Inspiration Island', 42, 47, 'Sightseeing', 'Istanbul Sultanahmet', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Visionary Views', 10, 147, 'Hiking', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ghostly Gaze', 25, 246, 'Sightseeing', 'Sydney Harbour', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Haunted Highlights', 24, 227, 'Sightseeing', 'Lisbon Hills', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Phantom Path', 47, 171, 'Hiking', 'Amalfi Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mystery Mile', 19, 244, 'Hiking', 'Yosemite Valley', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Shadow Sojourn', 32, 112, 'Sightseeing', 'Bali Jungles', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Midnight Murmurs', 26, 14, 'Hiking', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cryptic Circuit', 45, 6, 'Hiking', 'Vienna City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dark District', 47, 35, 'Sightseeing', 'Rome City Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Eerie Echoes', 28, 16, 'Hiking', 'Rome City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Spooky Steps', 42, 194, 'Hiking', 'Yellowstone Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Spirits of the Past', 25, 187, 'Sightseeing', 'Rome City Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Legend Lore', 19, 70, 'Hiking', 'Sydney Harbour', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mythic Moments', 37, 114, 'Sightseeing', 'Kyoto Temples', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Twilight Trails', 24, 72, 'Sightseeing', 'Jerusalem Old City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('After Dark Adventures', 45, 250, 'Hiking', 'Vienna City Center', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Moonlit Mysteries', 49, 50, 'Sightseeing', 'Venice Canals', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Foggy Frontier', 18, 238, 'Hiking', 'Yosemite Valley', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Chilling Chronicles', 21, 99, 'Sightseeing', 'Tokyo Shibuya', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Paranormal Parade', 12, 44, 'Sightseeing', 'Provence', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Supernatural Saunter', 35, 54, 'Hiking', 'New Orleans', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gothic Ghost Walk', 10, 11, 'Sightseeing', 'Venice Canals', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cemetery Secrets', 38, 115, 'Sightseeing', 'French Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tombstone Tales', 39, 142, 'Hiking', 'Cape Town Coast', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ancient Anathemata', 36, 221, 'Hiking', 'San Francisco Bay', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Forbidden Finds', 45, 65, 'Sightseeing', 'Dubai Marina', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Secret Societies', 37, 48, 'Hiking', 'Edinburgh Royal Mile', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hidden History', 13, 42, 'Sightseeing', 'London South Bank', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Masked Magic', 31, 203, 'Hiking', 'Lisbon Hills', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Illusion Island', 45, 88, 'Hiking', 'Swiss Alps', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Enigma Escape', 44, 114, 'Sightseeing', 'London South Bank', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Puzzling Path', 25, 107, 'Sightseeing', 'London South Bank', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Riddle Routes', 23, 109, 'Sightseeing', 'Dublin Liberties', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Crime & Consequence', 13, 123, 'Sightseeing', 'Swiss Alps', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Detective District', 26, 175, 'Sightseeing', 'Yellowstone Park', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Noir Night', 32, 210, 'Sightseeing', 'Bali Jungles', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sleuth Steps', 48, 44, 'Sightseeing', 'Tel Aviv Coastline', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Underworld Unveiled', 49, 67, 'Hiking', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rogue Roads', 48, 191, 'Hiking', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Outlaw Odysseys', 11, 12, 'Hiking', 'Amsterdam Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pirate’s Path', 27, 185, 'Sightseeing', 'Barcelona Las Ramblas', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Smuggler’s Secret', 47, 247, 'Hiking', 'Cairo Giza', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bandit Best', 32, 194, 'Hiking', 'Barcelona Gothic Quarter', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cursed Corners', 49, 54, 'Sightseeing', 'Seoul City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bewitched Boulevard', 42, 58, 'Hiking', 'Scottish Highlands', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sorcerer’s Sojourn', 22, 89, 'Sightseeing', 'Reykjavik', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Alchemist’s Arc', 33, 78, 'Hiking', 'Paris Montmartre', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mystical Muse', 16, 7, 'Sightseeing', 'Istanbul Sultanahmet', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Oracle Outing', 30, 106, 'Sightseeing', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tarot Trails', 25, 108, 'Sightseeing', 'Berlin Mitte', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zodiac Zigzag', 22, 246, 'Sightseeing', 'Manhattan', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pedal Power', 37, 240, 'Hiking', 'Madrid Center', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cycle Circuit', 11, 56, 'Hiking', 'Amsterdam Canals', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bike & Brew', 32, 70, 'Hiking', 'Yosemite Valley', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Two-Wheel Trek', 16, 243, 'Sightseeing', 'Petra', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rolling Routes', 18, 154, 'Sightseeing', 'Seoul City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Jogger’s Jaunt', 33, 190, 'Sightseeing', 'Machu Picchu', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Marathon Mile', 36, 120, 'Sightseeing', 'Cape Town Coast', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sprint Steps', 42, 62, 'Sightseeing', 'Amalfi Coast', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Active Adventures', 19, 159, 'Sightseeing', 'Jerusalem Old City', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fitness Frontier', 14, 227, 'Hiking', 'Old Town Prague', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wellness Walk', 16, 5, 'Hiking', 'Cairo Giza', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Yoga Yard', 26, 226, 'Sightseeing', 'Scottish Highlands', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zen Zone', 30, 157, 'Sightseeing', 'Santorini', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mindful Movements', 14, 0, 'Sightseeing', 'Cape Town Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Serenity Steps', 50, 147, 'Hiking', 'Barcelona Las Ramblas', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kayak Quest', 20, 142, 'Sightseeing', 'Yellowstone Park', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Paddle Path', 29, 6, 'Hiking', 'Hong Kong Island', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Surf & Sand', 22, 228, 'Sightseeing', 'Kyoto Temples', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sail Away', 20, 235, 'Hiking', 'Madrid Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nautical Night', 26, 43, 'Sightseeing', 'Prague Castle District', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skateboard Safari', 24, 14, 'Hiking', 'Rome City Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rollerblade Routes', 21, 234, 'Hiking', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Climb & Conquer', 26, 213, 'Sightseeing', 'Yellowstone Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bouldering Best', 17, 233, 'Hiking', 'Seoul City', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('High-Wire Hike', 49, 47, 'Hiking', 'Dublin City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zip-Line Zeal', 15, 204, 'Sightseeing', 'French Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Paraglide Path', 37, 209, 'Hiking', 'Central Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Balloon Best', 10, 112, 'Hiking', 'Barcelona Las Ramblas', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Aerial Adventures', 32, 143, 'Hiking', 'Barcelona Gothic Quarter', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Skydiving Sojourn', 32, 47, 'Sightseeing', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Deep Sea Discovery', 48, 129, 'Sightseeing', 'Singapore Marina', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Snorkel Steps', 46, 49, 'Hiking', 'Paris Montmartre', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Scuba Safari', 37, 117, 'Sightseeing', 'Seoul City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Underwater Universe', 18, 146, 'Hiking', 'Barcelona Las Ramblas', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Snowshoe Sojourn', 19, 77, 'Sightseeing', 'Florence', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ski Slope Safari', 26, 117, 'Hiking', 'London South Bank', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ice Rink Routes', 38, 85, 'Hiking', 'Rome City Center', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Winter Wonderland', 32, 55, 'Sightseeing', 'Dublin Liberties', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sporty Spectacle', 10, 3, 'Sightseeing', 'New Orleans', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Stadium Stars', 26, 237, 'Sightseeing', 'Singapore Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Arena Arc', 13, 33, 'Sightseeing', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Game Day Glimpse', 11, 193, 'Hiking', 'Singapore Marina', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fan Frontier', 45, 10, 'Sightseeing', 'Vienna City Center', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Goal Line Gaze', 39, 202, 'Sightseeing', 'Vancouver Waterfront', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Court Side Circuit', 35, 136, 'Sightseeing', 'Dublin City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pitch Perspectives', 37, 238, 'Sightseeing', 'Yellowstone Park', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Olympic Odyssey', 50, 158, 'Sightseeing', 'Dublin Liberties', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Champion’s Choice', 17, 240, 'Sightseeing', 'Sydney Harbour', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Victory Voyage', 24, 76, 'Sightseeing', 'Amsterdam Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Endurance Escape', 44, 200, 'Hiking', 'Cape Town Coast', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Family Fun Fest', 28, 11, 'Sightseeing', 'Seoul City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kid-Friendly Kingdom', 39, 130, 'Sightseeing', 'Grand Canyon', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Playful Path', 30, 193, 'Sightseeing', 'Dublin City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Toy Town Tour', 35, 208, 'Sightseeing', 'French Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Magic Mile', 31, 21, 'Hiking', 'Petra', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wonderland Walk', 18, 183, 'Sightseeing', 'Vancouver Waterfront', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fantasy Frontier', 40, 21, 'Sightseeing', 'French Quarter', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fairy Tale Follow', 40, 4, 'Hiking', 'Barcelona Las Ramblas', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Storybook Steps', 16, 161, 'Hiking', 'London South Bank', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Animal Adventures', 34, 224, 'Hiking', 'Athens Acropolis', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Zoo Zone', 50, 130, 'Hiking', 'Edinburgh Royal Mile', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Aquarium Arc', 12, 113, 'Hiking', 'Berlin Mitte', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Petting Path', 47, 17, 'Sightseeing', 'Yosemite Valley', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wildlife Watch', 27, 19, 'Hiking', 'Athens Acropolis', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Picnic Party', 37, 148, 'Hiking', 'Seoul City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Playground Parade', 48, 156, 'Sightseeing', 'Tokyo Shibuya', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Carnival Circuit', 21, 89, 'Hiking', 'Dublin City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fairground Finds', 12, 81, 'Hiking', 'Vancouver Waterfront', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Theme Park Thrills', 20, 15, 'Hiking', 'Seoul City', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rollercoaster Routes', 29, 203, 'Sightseeing', 'Yellowstone Park', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Candy Cane Lane', 35, 21, 'Sightseeing', 'Dublin Liberties', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sweet Shop Sojourn', 11, 135, 'Sightseeing', 'Madrid Center', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Ice Cream Island', 16, 109, 'Hiking', 'Barcelona Las Ramblas', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Balloon Boulevard', 35, 86, 'Sightseeing', 'Machu Picchu', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Circus Celebrations', 21, 171, 'Sightseeing', 'Prague Castle District', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Puppet Parade', 29, 69, 'Hiking', 'Istanbul Sultanahmet', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Toy Box Trek', 26, 20, 'Sightseeing', 'Kyoto Temples', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Game On Garden', 11, 227, 'Sightseeing', 'Istanbul Sultanahmet', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Puzzle Park', 10, 231, 'Sightseeing', 'New Orleans', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Maze Magic', 50, 136, 'Sightseeing', 'Jerusalem Old City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Science Secrets', 49, 223, 'Sightseeing', 'Lisbon Hills', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Discovery District', 23, 53, 'Hiking', 'Istanbul Sultanahmet', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Inventor’s Island', 17, 106, 'Sightseeing', 'Singapore Marina', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Robot Routes', 20, 19, 'Hiking', 'Provence', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Space Safari', 33, 89, 'Hiking', 'Yosemite Valley', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Planetarium Path', 26, 245, 'Hiking', 'Vienna City Center', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rocket Road', 43, 166, 'Hiking', 'Amsterdam Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dino Discovery', 36, 27, 'Sightseeing', 'London South Bank', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fossil Find', 36, 23, 'Hiking', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Prehistoric Path', 39, 37, 'Sightseeing', 'Munich Old Town', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Knight’s Quest', 28, 54, 'Sightseeing', 'New Orleans', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Princess Parade', 25, 110, 'Hiking', 'Cairo Giza', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wizard’s Walk', 29, 126, 'Hiking', 'Sydney Harbour', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Superhero Steps', 26, 250, 'Hiking', 'Jerusalem Old City', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cartoon Circuit', 40, 147, 'Hiking', 'Old Town Prague', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hobby Horse Hunt', 34, 138, 'Hiking', 'Athens Acropolis', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kite Krusade', 17, 42, 'Sightseeing', 'Yellowstone Park', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bubble Boulevard', 14, 209, 'Sightseeing', 'Munich Old Town', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Treasure Trove', 41, 66, 'Sightseeing', 'Sydney Harbour', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gold Mine Gaze', 35, 213, 'Hiking', 'French Quarter', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Luxury Lane', 29, 180, 'Hiking', 'Madrid Center', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Elegant Escapes', 18, 80, 'Hiking', 'Seoul City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Posh Path', 49, 38, 'Sightseeing', 'Edinburgh Royal Mile', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Diamond District', 36, 6, 'Hiking', 'Berlin Mitte', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Golden Glimpse', 30, 147, 'Hiking', 'Central Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Velvet Voyage', 36, 127, 'Hiking', 'Tokyo Shibuya', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Silk Road Saunter', 24, 231, 'Hiking', 'Grand Canyon', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('High Society Sojourn', 19, 205, 'Hiking', 'Prague Castle District', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Boutique Best', 47, 172, 'Sightseeing', 'Swiss Alps', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retail Revelations', 29, 163, 'Hiking', 'Reykjavik', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Shopaholic Safari', 18, 41, 'Hiking', 'Berlin Mitte', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Window Shopping Walk', 24, 82, 'Sightseeing', 'Vancouver Waterfront', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Fashion Forward', 13, 100, 'Hiking', 'Barcelona Las Ramblas', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Glamour Gaze', 44, 97, 'Sightseeing', 'Grand Canyon', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Spa Serenity', 14, 156, 'Hiking', 'Amsterdam Canals', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Wellness Wonders', 33, 21, 'Sightseeing', 'Rome City Center', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retreat Routes', 36, 162, 'Sightseeing', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Relaxation Road', 12, 87, 'Hiking', 'Amalfi Coast', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tranquility Trail', 16, 25, 'Hiking', 'Provence', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bliss Boulevard', 38, 206, 'Sightseeing', 'Tel Aviv Coastline', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Resort Revelations', 34, 69, 'Hiking', 'Petra', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hotel Highlights', 33, 201, 'Hiking', 'Dubai Marina', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Manor Muse', 39, 119, 'Sightseeing', 'Patagonia', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Estate Explorations', 29, 96, 'Sightseeing', 'French Quarter', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mansion Magic', 42, 215, 'Sightseeing', 'London South Bank', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Penthouse Perspectives', 25, 133, 'Sightseeing', 'Swiss Alps', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Yacht Yard', 21, 214, 'Hiking', 'Swiss Alps', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Limousine Lore', 24, 95, 'Hiking', 'Paris Montmartre', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('First Class Follow', 27, 154, 'Sightseeing', 'Amalfi Coast', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Elite Escapades', 36, 206, 'Hiking', 'Barcelona Las Ramblas', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Private Paradise', 30, 100, 'Sightseeing', 'Cape Town Coast', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Exclusive Echoes', 47, 9, 'Sightseeing', 'Seoul City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Hidden Gems', 49, 184, 'Sightseeing', 'Munich Old Town', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Secret Sanctuary', 34, 183, 'Hiking', 'Dublin Liberties', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Quiet Quarters', 48, 127, 'Sightseeing', 'Amsterdam Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Peaceful Path', 20, 228, 'Sightseeing', 'Barcelona Las Ramblas', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Serene Sojourn', 38, 105, 'Hiking', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Calm Currents', 33, 195, 'Sightseeing', 'Amalfi Coast', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Gentle Gaze', 12, 103, 'Hiking', 'Venice Canals', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Leisurely Loop', 50, 13, 'Sightseeing', 'Tel Aviv Coastline', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Slow Lane Saunter', 19, 62, 'Sightseeing', 'Yellowstone Park', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Easy Breezy', 36, 2, 'Sightseeing', 'Amsterdam Canals', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunny Side Up', 18, 81, 'Sightseeing', 'San Francisco Bay', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Carefree Circuit', 42, 106, 'Sightseeing', 'Petra', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Happy Hour Hunt', 39, 142, 'Hiking', 'Dublin City', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sunset Spirits', 17, 94, 'Hiking', 'Vancouver Waterfront', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Twilight Toast', 18, 205, 'Hiking', 'Venice Canals', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Evening Elegance', 37, 31, 'Hiking', 'Venice Canals', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nightfall Nuances', 40, 71, 'Hiking', 'Munich Old Town', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Dreamy Destinations', 46, 118, 'Hiking', 'Athens Acropolis', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Oddity Odyssey', 25, 24, 'Sightseeing', 'Manhattan', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Peculiar Path', 21, 87, 'Sightseeing', 'Barcelona Las Ramblas', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Strange Steps', 42, 203, 'Sightseeing', 'Santorini', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Weird & Wonderful', 12, 38, 'Sightseeing', 'Yellowstone Park', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Curious Circuit', 45, 226, 'Hiking', 'Berlin Mitte', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bizarre Boulevard', 23, 195, 'Hiking', 'Dublin Liberties', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Offbeat Outing', 26, 192, 'Sightseeing', 'Central Park', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Quirky Quarters', 30, 28, 'Sightseeing', 'Paris Montmartre', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Unusual Universe', 31, 128, 'Hiking', 'Reykjavik', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Rare Routes', 37, 153, 'Hiking', 'Singapore Marina', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Eccentric Escapes', 16, 250, 'Hiking', 'Provence', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Funky Frontier', 34, 119, 'Hiking', 'Istanbul Sultanahmet', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Retro Revival', 40, 7, 'Hiking', 'Machu Picchu', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Kitsch Kingdom', 34, 222, 'Hiking', 'Singapore Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vintage Vibes', 10, 190, 'Sightseeing', 'Grand Canyon', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Thrift Shop Trek', 14, 61, 'Sightseeing', 'Grand Canyon', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Flea Market Follow', 40, 128, 'Hiking', 'Rome City Center', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Antique Arc', 13, 93, 'Hiking', 'Edinburgh Royal Mile', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Curiosities Circuit', 13, 123, 'Hiking', 'Kyoto Temples', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Collector’s Choice', 18, 197, 'Sightseeing', 'London South Bank', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Nerd Night', 15, 3, 'Hiking', 'Central Park', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Geek Gaze', 33, 114, 'Sightseeing', 'San Francisco Bay', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Tech Trek', 33, 67, 'Hiking', 'Swiss Alps', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Digital District', 17, 102, 'Sightseeing', 'Dublin City', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Startup Safari', 41, 194, 'Sightseeing', 'Athens Acropolis', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Innovation Island', 41, 126, 'Sightseeing', 'Venice Canals', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Future Frontiers', 29, 107, 'Hiking', 'Istanbul Sultanahmet', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Sci-Fi Sojourn', 45, 43, 'Sightseeing', 'Provence', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Steampunk Steps', 15, 95, 'Hiking', 'Cairo Giza', 1, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Cyber Circuit', 21, 57, 'Sightseeing', 'Yosemite Valley', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Street Art Safari', 13, 149, 'Sightseeing', 'Grand Canyon', 1, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Vinyl Voyage', 24, 12, 'Sightseeing', 'Lisbon Hills', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Record Road', 30, 157, 'Sightseeing', 'Provence', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Bookworm Boulevard', 12, 142, 'Hiking', 'Istanbul Sultanahmet', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Library Lore', 46, 120, 'Hiking', 'French Quarter', 0, 3);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Literary Legend', 29, 129, 'Hiking', 'Dubai Marina', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Writer’s Walk', 41, 111, 'Hiking', 'Cairo Giza', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Poet’s Path', 17, 77, 'Sightseeing', 'Central Park', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Language Lab', 31, 235, 'Sightseeing', 'Amsterdam Canals', 1, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Polyglot Parade', 39, 228, 'Hiking', 'Amalfi Coast', 0, 2);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Math Magic', 41, 178, 'Sightseeing', 'Barcelona Las Ramblas', 1, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Geometry Gaze', 33, 226, 'Hiking', 'Scottish Highlands', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Pattern Path', 30, 54, 'Hiking', 'Munich Old Town', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Soundscape Safari', 47, 122, 'Sightseeing', 'Tokyo Shibuya', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Acoustic Adventures', 16, 165, 'Hiking', 'Tel Aviv Coastline', 0, 5);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Echo Exploration', 17, 35, 'Hiking', 'Hong Kong Island', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Shadow Steps', 12, 204, 'Sightseeing', 'Florence', 0, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Reflection Routes', 35, 225, 'Hiking', 'Dublin City', 0, 4);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Mirror Magic', 50, 3, 'Sightseeing', 'Rome City Center', 1, 1);
insert into TOUR (t_name, max_participants, price, t_type, area, accessibility, t_level) values ('Final Frontier', 13, 30, 'Sightseeing', 'Dublin City', 1, 3);
